/*
 * d3d9_native_hooks.h -- per-method native entry points
 *
 * GENERATED by research/dxmt/src/d3d9shim/gen_d3d9_thunks.py from
 * research/dxmt/src/d3d9shim/d3d9_api.py.  REGENERATE, DO NOT EDIT.
 *
 * The slot number IS the ABI -- a hand edit that inserts or drops one line
 * silently sends every later call to the wrong function.  d3d9_api.py is the
 * only place any of this may be changed.
 *
 * Copyright 2026 Will Faust
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef __MADEIRA_D3D9_NATIVE_HOOKS_H
#define __MADEIRA_D3D9_NATIVE_HOOKS_H

#include "d3d9shim_ops.h"

/* A native object reference: an index + generation into the native table,
 * never a host pointer (invariant 4).  0 is "none". */
typedef uint64_t d3d9_native_handle;

/* What a handle points at.  The glue stores the CANONICAL interface pointer
 * for the kind (the one named beside each value below) and every lookup is
 * checked against it, so a handle of the wrong kind is D3DERR_INVALIDCALL
 * rather than a wild cast.  0 is reserved: d3d9_native_handle_lookup() reads
 * it as "any kind", which only the teardown sweep ever asks for. */
enum d3d9_native_kind {
    D3D9_NATIVE_KIND_NONE = 0,
    D3D9_NATIVE_KIND_D3D9                  =  1, /* IDirect3D9Ex */
    D3D9_NATIVE_KIND_DEVICE                =  2, /* IDirect3DDevice9Ex */
    D3D9_NATIVE_KIND_SWAPCHAIN             =  3, /* IDirect3DSwapChain9Ex */
    D3D9_NATIVE_KIND_SURFACE               =  4, /* IDirect3DSurface9 */
    D3D9_NATIVE_KIND_TEXTURE               =  5, /* IDirect3DTexture9 */
    D3D9_NATIVE_KIND_CUBETEXTURE           =  6, /* IDirect3DCubeTexture9 */
    D3D9_NATIVE_KIND_VOLUMETEXTURE         =  7, /* IDirect3DVolumeTexture9 */
    D3D9_NATIVE_KIND_VOLUME                =  8, /* IDirect3DVolume9 */
    D3D9_NATIVE_KIND_VERTEXBUFFER          =  9, /* IDirect3DVertexBuffer9 */
    D3D9_NATIVE_KIND_INDEXBUFFER           = 10, /* IDirect3DIndexBuffer9 */
    D3D9_NATIVE_KIND_VERTEXDECL            = 11, /* IDirect3DVertexDeclaration9 */
    D3D9_NATIVE_KIND_VERTEXSHADER          = 12, /* IDirect3DVertexShader9 */
    D3D9_NATIVE_KIND_PIXELSHADER           = 13, /* IDirect3DPixelShader9 */
    D3D9_NATIVE_KIND_STATEBLOCK            = 14, /* IDirect3DStateBlock9 */
    D3D9_NATIVE_KIND_QUERY                 = 15, /* IDirect3DQuery9 */
    D3D9_NATIVE_KIND_COUNT
};

#ifdef __cplusplus
extern "C" {
#endif


/* Called once, from _d3d9_init, after the hash handshake passes. */
extern int d3d9_native_init(void);
/* Called from ios_wow_reclaim_dead_windows() BEFORE the PROT_NONE replace
 * and before ios_jit_purge_window() -- native objects hold host pointers
 * INTO the arena (8.9-5). */
extern void d3d9_native_process_teardown(void *peb);

/* One hook per vtable slot.  The glue implements these against MTLD3D9* in
 * step 4; `local` slots are listed too, so the table below is total and a
 * later reclassification is a one-line change in d3d9_api.py. */

/* IDirect3D9Ex::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_D3D9Ex_QueryInterface(d3d9_native_handle self, const GUID *iid, d3d9_native_handle *out);
/* IDirect3D9Ex::AddRef -- slot 1, local */
extern ULONG d3d9_native_D3D9Ex_AddRef(d3d9_native_handle self);
/* IDirect3D9Ex::Release -- slot 2, defer */
extern ULONG d3d9_native_D3D9Ex_Release(d3d9_native_handle self);
/* IDirect3D9Ex::RegisterSoftwareDevice -- slot 3, local */
extern HRESULT d3d9_native_D3D9Ex_RegisterSoftwareDevice(d3d9_native_handle self, void * init);
/* IDirect3D9Ex::GetAdapterCount -- slot 4, sync */
extern UINT d3d9_native_D3D9Ex_GetAdapterCount(d3d9_native_handle self);
/* IDirect3D9Ex::GetAdapterIdentifier -- slot 5, sync */
extern HRESULT d3d9_native_D3D9Ex_GetAdapterIdentifier(d3d9_native_handle self, UINT adapter_idx, DWORD flags, D3DADAPTER_IDENTIFIER9 *identifier);
/* IDirect3D9Ex::GetAdapterModeCount -- slot 6, sync */
extern UINT d3d9_native_D3D9Ex_GetAdapterModeCount(d3d9_native_handle self, UINT adapter_idx, D3DFORMAT format);
/* IDirect3D9Ex::EnumAdapterModes -- slot 7, sync */
extern HRESULT d3d9_native_D3D9Ex_EnumAdapterModes(d3d9_native_handle self, UINT adapter_idx, D3DFORMAT format, UINT mode_idx, D3DDISPLAYMODE *mode);
/* IDirect3D9Ex::GetAdapterDisplayMode -- slot 8, sync */
extern HRESULT d3d9_native_D3D9Ex_GetAdapterDisplayMode(d3d9_native_handle self, UINT adapter_idx, D3DDISPLAYMODE *mode);
/* IDirect3D9Ex::CheckDeviceType -- slot 9, sync */
extern HRESULT d3d9_native_D3D9Ex_CheckDeviceType(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, D3DFORMAT display_format, D3DFORMAT backbuffer_format, WINBOOL windowed);
/* IDirect3D9Ex::CheckDeviceFormat -- slot 10, sync */
extern HRESULT d3d9_native_D3D9Ex_CheckDeviceFormat(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, D3DFORMAT adapter_format, DWORD usage, D3DRESOURCETYPE resource_type, D3DFORMAT format);
/* IDirect3D9Ex::CheckDeviceMultiSampleType -- slot 11, sync */
extern HRESULT d3d9_native_D3D9Ex_CheckDeviceMultiSampleType(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, D3DFORMAT surface_format, WINBOOL windowed, D3DMULTISAMPLE_TYPE multisample_type, DWORD *quality_levels);
/* IDirect3D9Ex::CheckDepthStencilMatch -- slot 12, sync */
extern HRESULT d3d9_native_D3D9Ex_CheckDepthStencilMatch(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, D3DFORMAT adapter_format, D3DFORMAT rt_format, D3DFORMAT ds_format);
/* IDirect3D9Ex::CheckDeviceFormatConversion -- slot 13, sync */
extern HRESULT d3d9_native_D3D9Ex_CheckDeviceFormatConversion(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, D3DFORMAT src_format, D3DFORMAT dst_format);
/* IDirect3D9Ex::GetDeviceCaps -- slot 14, sync */
extern HRESULT d3d9_native_D3D9Ex_GetDeviceCaps(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, D3DCAPS9 *caps);
/* IDirect3D9Ex::GetAdapterMonitor -- slot 15, sync */
extern HMONITOR d3d9_native_D3D9Ex_GetAdapterMonitor(d3d9_native_handle self, UINT adapter_idx);
/* IDirect3D9Ex::CreateDevice -- slot 16, sync */
extern HRESULT d3d9_native_D3D9Ex_CreateDevice(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, HWND focus_window, DWORD flags, D3DPRESENT_PARAMETERS *parameters, d3d9_native_handle *device);
/* IDirect3D9Ex::GetAdapterModeCountEx -- slot 17, sync */
extern UINT d3d9_native_D3D9Ex_GetAdapterModeCountEx(d3d9_native_handle self, UINT adapter_idx, const D3DDISPLAYMODEFILTER *filter);
/* IDirect3D9Ex::EnumAdapterModesEx -- slot 18, sync */
extern HRESULT d3d9_native_D3D9Ex_EnumAdapterModesEx(d3d9_native_handle self, UINT adapter_idx, const D3DDISPLAYMODEFILTER *filter, UINT mode_idx, D3DDISPLAYMODEEX *mode);
/* IDirect3D9Ex::GetAdapterDisplayModeEx -- slot 19, sync */
extern HRESULT d3d9_native_D3D9Ex_GetAdapterDisplayModeEx(d3d9_native_handle self, UINT adapter_idx, D3DDISPLAYMODEEX *mode, D3DDISPLAYROTATION *rotation);
/* IDirect3D9Ex::CreateDeviceEx -- slot 20, sync */
extern HRESULT d3d9_native_D3D9Ex_CreateDeviceEx(d3d9_native_handle self, UINT adapter_idx, D3DDEVTYPE device_type, HWND focus_window, DWORD flags, D3DPRESENT_PARAMETERS *parameters, const D3DDISPLAYMODEEX *mode, d3d9_native_handle *device);
/* IDirect3D9Ex::GetAdapterLUID -- slot 21, sync */
extern HRESULT d3d9_native_D3D9Ex_GetAdapterLUID(d3d9_native_handle self, UINT adapter_idx, LUID *luid);
/* IDirect3DDevice9Ex::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_Device9Ex_QueryInterface(d3d9_native_handle self, const GUID *iid, d3d9_native_handle *out);
/* IDirect3DDevice9Ex::AddRef -- slot 1, local */
extern ULONG d3d9_native_Device9Ex_AddRef(d3d9_native_handle self);
/* IDirect3DDevice9Ex::Release -- slot 2, defer */
extern ULONG d3d9_native_Device9Ex_Release(d3d9_native_handle self);
/* IDirect3DDevice9Ex::TestCooperativeLevel -- slot 3, sync */
extern HRESULT d3d9_native_Device9Ex_TestCooperativeLevel(d3d9_native_handle self);
/* IDirect3DDevice9Ex::GetAvailableTextureMem -- slot 4, sync */
extern UINT d3d9_native_Device9Ex_GetAvailableTextureMem(d3d9_native_handle self);
/* IDirect3DDevice9Ex::EvictManagedResources -- slot 5, sync */
extern HRESULT d3d9_native_Device9Ex_EvictManagedResources(d3d9_native_handle self);
/* IDirect3DDevice9Ex::GetDirect3D -- slot 6, local */
extern HRESULT d3d9_native_Device9Ex_GetDirect3D(d3d9_native_handle self, d3d9_native_handle *d3d9);
/* IDirect3DDevice9Ex::GetDeviceCaps -- slot 7, sync */
extern HRESULT d3d9_native_Device9Ex_GetDeviceCaps(d3d9_native_handle self, D3DCAPS9 *caps);
/* IDirect3DDevice9Ex::GetDisplayMode -- slot 8, sync */
extern HRESULT d3d9_native_Device9Ex_GetDisplayMode(d3d9_native_handle self, UINT swapchain_idx, D3DDISPLAYMODE *mode);
/* IDirect3DDevice9Ex::GetCreationParameters -- slot 9, sync */
extern HRESULT d3d9_native_Device9Ex_GetCreationParameters(d3d9_native_handle self, D3DDEVICE_CREATION_PARAMETERS *parameters);
/* IDirect3DDevice9Ex::SetCursorProperties -- slot 10, sync */
extern HRESULT d3d9_native_Device9Ex_SetCursorProperties(d3d9_native_handle self, UINT hotspot_x, UINT hotspot_y, d3d9_native_handle bitmap);
/* IDirect3DDevice9Ex::SetCursorPosition -- slot 11, local */
extern void d3d9_native_Device9Ex_SetCursorPosition(d3d9_native_handle self, int x, int y, DWORD flags);
/* IDirect3DDevice9Ex::ShowCursor -- slot 12, local */
extern WINBOOL d3d9_native_Device9Ex_ShowCursor(d3d9_native_handle self, WINBOOL show);
/* IDirect3DDevice9Ex::CreateAdditionalSwapChain -- slot 13, sync */
extern HRESULT d3d9_native_Device9Ex_CreateAdditionalSwapChain(d3d9_native_handle self, D3DPRESENT_PARAMETERS *parameters, d3d9_native_handle *swapchain);
/* IDirect3DDevice9Ex::GetSwapChain -- slot 14, resolve */
extern HRESULT d3d9_native_Device9Ex_GetSwapChain(d3d9_native_handle self, UINT swapchain_idx, d3d9_native_handle *swapchain);
/* IDirect3DDevice9Ex::GetNumberOfSwapChains -- slot 15, sync */
extern UINT d3d9_native_Device9Ex_GetNumberOfSwapChains(d3d9_native_handle self);
/* IDirect3DDevice9Ex::Reset -- slot 16, sync */
extern HRESULT d3d9_native_Device9Ex_Reset(d3d9_native_handle self, D3DPRESENT_PARAMETERS *parameters);
/* IDirect3DDevice9Ex::Present -- slot 17, sync */
extern HRESULT d3d9_native_Device9Ex_Present(d3d9_native_handle self, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region);
/* IDirect3DDevice9Ex::GetBackBuffer -- slot 18, resolve */
extern HRESULT d3d9_native_Device9Ex_GetBackBuffer(d3d9_native_handle self, UINT swapchain_idx, UINT backbuffer_idx, D3DBACKBUFFER_TYPE backbuffer_type, d3d9_native_handle *backbuffer);
/* IDirect3DDevice9Ex::GetRasterStatus -- slot 19, sync */
extern HRESULT d3d9_native_Device9Ex_GetRasterStatus(d3d9_native_handle self, UINT swapchain_idx, D3DRASTER_STATUS *raster_status);
/* IDirect3DDevice9Ex::SetDialogBoxMode -- slot 20, sync */
extern HRESULT d3d9_native_Device9Ex_SetDialogBoxMode(d3d9_native_handle self, WINBOOL enable);
/* IDirect3DDevice9Ex::SetGammaRamp -- slot 21, sync */
extern void d3d9_native_Device9Ex_SetGammaRamp(d3d9_native_handle self, UINT swapchain_idx, DWORD flags, const D3DGAMMARAMP *ramp);
/* IDirect3DDevice9Ex::GetGammaRamp -- slot 22, sync */
extern void d3d9_native_Device9Ex_GetGammaRamp(d3d9_native_handle self, UINT swapchain_idx, D3DGAMMARAMP *ramp);
/* IDirect3DDevice9Ex::CreateTexture -- slot 23, sync */
extern HRESULT d3d9_native_Device9Ex_CreateTexture(d3d9_native_handle self, UINT width, UINT height, UINT levels, DWORD usage, D3DFORMAT format, D3DPOOL pool, d3d9_native_handle *texture, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::CreateVolumeTexture -- slot 24, sync */
extern HRESULT d3d9_native_Device9Ex_CreateVolumeTexture(d3d9_native_handle self, UINT width, UINT height, UINT depth, UINT levels, DWORD usage, D3DFORMAT format, D3DPOOL pool, d3d9_native_handle *texture, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::CreateCubeTexture -- slot 25, sync */
extern HRESULT d3d9_native_Device9Ex_CreateCubeTexture(d3d9_native_handle self, UINT edge_length, UINT levels, DWORD usage, D3DFORMAT format, D3DPOOL pool, d3d9_native_handle *texture, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::CreateVertexBuffer -- slot 26, sync */
extern HRESULT d3d9_native_Device9Ex_CreateVertexBuffer(d3d9_native_handle self, UINT size, DWORD usage, DWORD fvf, D3DPOOL pool, d3d9_native_handle *buffer, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::CreateIndexBuffer -- slot 27, sync */
extern HRESULT d3d9_native_Device9Ex_CreateIndexBuffer(d3d9_native_handle self, UINT size, DWORD usage, D3DFORMAT format, D3DPOOL pool, d3d9_native_handle *buffer, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::CreateRenderTarget -- slot 28, sync */
extern HRESULT d3d9_native_Device9Ex_CreateRenderTarget(d3d9_native_handle self, UINT width, UINT height, D3DFORMAT format, D3DMULTISAMPLE_TYPE multisample_type, DWORD multisample_quality, WINBOOL lockable, d3d9_native_handle *surface, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::CreateDepthStencilSurface -- slot 29, sync */
extern HRESULT d3d9_native_Device9Ex_CreateDepthStencilSurface(d3d9_native_handle self, UINT width, UINT height, D3DFORMAT format, D3DMULTISAMPLE_TYPE multisample_type, DWORD multisample_quality, WINBOOL discard, d3d9_native_handle *surface, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::UpdateSurface -- slot 30, sync */
extern HRESULT d3d9_native_Device9Ex_UpdateSurface(d3d9_native_handle self, d3d9_native_handle src_surface, const RECT *src_rect, d3d9_native_handle dst_surface, const POINT *dst_point);
/* IDirect3DDevice9Ex::UpdateTexture -- slot 31, sync */
extern HRESULT d3d9_native_Device9Ex_UpdateTexture(d3d9_native_handle self, d3d9_native_handle src_texture, d3d9_native_handle dst_texture);
/* IDirect3DDevice9Ex::GetRenderTargetData -- slot 32, sync */
extern HRESULT d3d9_native_Device9Ex_GetRenderTargetData(d3d9_native_handle self, d3d9_native_handle render_target, d3d9_native_handle dst_surface);
/* IDirect3DDevice9Ex::GetFrontBufferData -- slot 33, sync */
extern HRESULT d3d9_native_Device9Ex_GetFrontBufferData(d3d9_native_handle self, UINT swapchain_idx, d3d9_native_handle dst_surface);
/* IDirect3DDevice9Ex::StretchRect -- slot 34, sync */
extern HRESULT d3d9_native_Device9Ex_StretchRect(d3d9_native_handle self, d3d9_native_handle src_surface, const RECT *src_rect, d3d9_native_handle dst_surface, const RECT *dst_rect, D3DTEXTUREFILTERTYPE filter);
/* IDirect3DDevice9Ex::ColorFill -- slot 35, sync */
extern HRESULT d3d9_native_Device9Ex_ColorFill(d3d9_native_handle self, d3d9_native_handle surface, const RECT *rect, D3DCOLOR colour);
/* IDirect3DDevice9Ex::CreateOffscreenPlainSurface -- slot 36, sync */
extern HRESULT d3d9_native_Device9Ex_CreateOffscreenPlainSurface(d3d9_native_handle self, UINT width, UINT height, D3DFORMAT format, D3DPOOL pool, d3d9_native_handle *surface, HANDLE *shared_handle);
/* IDirect3DDevice9Ex::SetRenderTarget -- slot 37, defer */
extern HRESULT d3d9_native_Device9Ex_SetRenderTarget(d3d9_native_handle self, DWORD idx, d3d9_native_handle surface);
/* IDirect3DDevice9Ex::GetRenderTarget -- slot 38, resolve */
extern HRESULT d3d9_native_Device9Ex_GetRenderTarget(d3d9_native_handle self, DWORD idx, d3d9_native_handle *surface);
/* IDirect3DDevice9Ex::SetDepthStencilSurface -- slot 39, defer */
extern HRESULT d3d9_native_Device9Ex_SetDepthStencilSurface(d3d9_native_handle self, d3d9_native_handle depth_stencil);
/* IDirect3DDevice9Ex::GetDepthStencilSurface -- slot 40, resolve */
extern HRESULT d3d9_native_Device9Ex_GetDepthStencilSurface(d3d9_native_handle self, d3d9_native_handle *depth_stencil);
/* IDirect3DDevice9Ex::BeginScene -- slot 41, defer */
extern HRESULT d3d9_native_Device9Ex_BeginScene(d3d9_native_handle self);
/* IDirect3DDevice9Ex::EndScene -- slot 42, defer */
extern HRESULT d3d9_native_Device9Ex_EndScene(d3d9_native_handle self);
/* IDirect3DDevice9Ex::Clear -- slot 43, defer */
extern HRESULT d3d9_native_Device9Ex_Clear(d3d9_native_handle self, DWORD rect_count, const D3DRECT *rects, DWORD flags, D3DCOLOR colour, float z, DWORD stencil);
/* IDirect3DDevice9Ex::SetTransform -- slot 44, defer */
extern HRESULT d3d9_native_Device9Ex_SetTransform(d3d9_native_handle self, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
/* IDirect3DDevice9Ex::GetTransform -- slot 45, sync */
extern HRESULT d3d9_native_Device9Ex_GetTransform(d3d9_native_handle self, D3DTRANSFORMSTATETYPE State, D3DMATRIX *matrix);
/* IDirect3DDevice9Ex::MultiplyTransform -- slot 46, defer */
extern HRESULT d3d9_native_Device9Ex_MultiplyTransform(d3d9_native_handle self, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
/* IDirect3DDevice9Ex::SetViewport -- slot 47, defer */
extern HRESULT d3d9_native_Device9Ex_SetViewport(d3d9_native_handle self, const D3DVIEWPORT9 *viewport);
/* IDirect3DDevice9Ex::GetViewport -- slot 48, sync */
extern HRESULT d3d9_native_Device9Ex_GetViewport(d3d9_native_handle self, D3DVIEWPORT9 *viewport);
/* IDirect3DDevice9Ex::SetMaterial -- slot 49, defer */
extern HRESULT d3d9_native_Device9Ex_SetMaterial(d3d9_native_handle self, const D3DMATERIAL9 *material);
/* IDirect3DDevice9Ex::GetMaterial -- slot 50, sync */
extern HRESULT d3d9_native_Device9Ex_GetMaterial(d3d9_native_handle self, D3DMATERIAL9 *material);
/* IDirect3DDevice9Ex::SetLight -- slot 51, defer */
extern HRESULT d3d9_native_Device9Ex_SetLight(d3d9_native_handle self, DWORD idx, const D3DLIGHT9 *light);
/* IDirect3DDevice9Ex::GetLight -- slot 52, sync */
extern HRESULT d3d9_native_Device9Ex_GetLight(d3d9_native_handle self, DWORD idx, D3DLIGHT9 *light);
/* IDirect3DDevice9Ex::LightEnable -- slot 53, defer */
extern HRESULT d3d9_native_Device9Ex_LightEnable(d3d9_native_handle self, DWORD idx, WINBOOL enable);
/* IDirect3DDevice9Ex::GetLightEnable -- slot 54, sync */
extern HRESULT d3d9_native_Device9Ex_GetLightEnable(d3d9_native_handle self, DWORD idx, WINBOOL *enable);
/* IDirect3DDevice9Ex::SetClipPlane -- slot 55, defer */
extern HRESULT d3d9_native_Device9Ex_SetClipPlane(d3d9_native_handle self, DWORD idx, const float *plane);
/* IDirect3DDevice9Ex::GetClipPlane -- slot 56, sync */
extern HRESULT d3d9_native_Device9Ex_GetClipPlane(d3d9_native_handle self, DWORD idx, float *plane);
/* IDirect3DDevice9Ex::SetRenderState -- slot 57, defer */
extern HRESULT d3d9_native_Device9Ex_SetRenderState(d3d9_native_handle self, D3DRENDERSTATETYPE state, DWORD value);
/* IDirect3DDevice9Ex::GetRenderState -- slot 58, sync */
extern HRESULT d3d9_native_Device9Ex_GetRenderState(d3d9_native_handle self, D3DRENDERSTATETYPE state, DWORD *value);
/* IDirect3DDevice9Ex::CreateStateBlock -- slot 59, sync */
extern HRESULT d3d9_native_Device9Ex_CreateStateBlock(d3d9_native_handle self, D3DSTATEBLOCKTYPE type, d3d9_native_handle *stateblock);
/* IDirect3DDevice9Ex::BeginStateBlock -- slot 60, sync */
extern HRESULT d3d9_native_Device9Ex_BeginStateBlock(d3d9_native_handle self);
/* IDirect3DDevice9Ex::EndStateBlock -- slot 61, sync */
extern HRESULT d3d9_native_Device9Ex_EndStateBlock(d3d9_native_handle self, d3d9_native_handle *stateblock);
/* IDirect3DDevice9Ex::SetClipStatus -- slot 62, defer */
extern HRESULT d3d9_native_Device9Ex_SetClipStatus(d3d9_native_handle self, const D3DCLIPSTATUS9 *clip_status);
/* IDirect3DDevice9Ex::GetClipStatus -- slot 63, sync */
extern HRESULT d3d9_native_Device9Ex_GetClipStatus(d3d9_native_handle self, D3DCLIPSTATUS9 *clip_status);
/* IDirect3DDevice9Ex::GetTexture -- slot 64, local */
extern HRESULT d3d9_native_Device9Ex_GetTexture(d3d9_native_handle self, DWORD stage, d3d9_native_handle *texture);
/* IDirect3DDevice9Ex::SetTexture -- slot 65, defer */
extern HRESULT d3d9_native_Device9Ex_SetTexture(d3d9_native_handle self, DWORD stage, d3d9_native_handle texture);
/* IDirect3DDevice9Ex::GetTextureStageState -- slot 66, sync */
extern HRESULT d3d9_native_Device9Ex_GetTextureStageState(d3d9_native_handle self, DWORD stage, D3DTEXTURESTAGESTATETYPE state, DWORD *value);
/* IDirect3DDevice9Ex::SetTextureStageState -- slot 67, defer */
extern HRESULT d3d9_native_Device9Ex_SetTextureStageState(d3d9_native_handle self, DWORD stage, D3DTEXTURESTAGESTATETYPE state, DWORD value);
/* IDirect3DDevice9Ex::GetSamplerState -- slot 68, sync */
extern HRESULT d3d9_native_Device9Ex_GetSamplerState(d3d9_native_handle self, DWORD sampler_idx, D3DSAMPLERSTATETYPE state, DWORD *value);
/* IDirect3DDevice9Ex::SetSamplerState -- slot 69, defer */
extern HRESULT d3d9_native_Device9Ex_SetSamplerState(d3d9_native_handle self, DWORD sampler_idx, D3DSAMPLERSTATETYPE state, DWORD value);
/* IDirect3DDevice9Ex::ValidateDevice -- slot 70, sync */
extern HRESULT d3d9_native_Device9Ex_ValidateDevice(d3d9_native_handle self, DWORD *pass_count);
/* IDirect3DDevice9Ex::SetPaletteEntries -- slot 71, defer */
extern HRESULT d3d9_native_Device9Ex_SetPaletteEntries(d3d9_native_handle self, UINT palette_idx, const PALETTEENTRY *entries);
/* IDirect3DDevice9Ex::GetPaletteEntries -- slot 72, sync */
extern HRESULT d3d9_native_Device9Ex_GetPaletteEntries(d3d9_native_handle self, UINT palette_idx, PALETTEENTRY *entries);
/* IDirect3DDevice9Ex::SetCurrentTexturePalette -- slot 73, defer */
extern HRESULT d3d9_native_Device9Ex_SetCurrentTexturePalette(d3d9_native_handle self, UINT palette_idx);
/* IDirect3DDevice9Ex::GetCurrentTexturePalette -- slot 74, sync */
extern HRESULT d3d9_native_Device9Ex_GetCurrentTexturePalette(d3d9_native_handle self, UINT *palette_idx);
/* IDirect3DDevice9Ex::SetScissorRect -- slot 75, defer */
extern HRESULT d3d9_native_Device9Ex_SetScissorRect(d3d9_native_handle self, const RECT *rect);
/* IDirect3DDevice9Ex::GetScissorRect -- slot 76, sync */
extern HRESULT d3d9_native_Device9Ex_GetScissorRect(d3d9_native_handle self, RECT *rect);
/* IDirect3DDevice9Ex::SetSoftwareVertexProcessing -- slot 77, defer */
extern HRESULT d3d9_native_Device9Ex_SetSoftwareVertexProcessing(d3d9_native_handle self, WINBOOL software);
/* IDirect3DDevice9Ex::GetSoftwareVertexProcessing -- slot 78, sync */
extern WINBOOL d3d9_native_Device9Ex_GetSoftwareVertexProcessing(d3d9_native_handle self);
/* IDirect3DDevice9Ex::SetNPatchMode -- slot 79, defer */
extern HRESULT d3d9_native_Device9Ex_SetNPatchMode(d3d9_native_handle self, float segment_count);
/* IDirect3DDevice9Ex::GetNPatchMode -- slot 80, sync */
extern float d3d9_native_Device9Ex_GetNPatchMode(d3d9_native_handle self);
/* IDirect3DDevice9Ex::DrawPrimitive -- slot 81, defer */
extern HRESULT d3d9_native_Device9Ex_DrawPrimitive(d3d9_native_handle self, D3DPRIMITIVETYPE primitive_type, UINT start_vertex, UINT primitive_count);
/* IDirect3DDevice9Ex::DrawIndexedPrimitive -- slot 82, defer */
extern HRESULT d3d9_native_Device9Ex_DrawIndexedPrimitive(d3d9_native_handle self, D3DPRIMITIVETYPE primitive_type, INT base_vertex_idx, UINT min_vertex_idx, UINT vertex_count, UINT start_idx, UINT primitive_count);
/* IDirect3DDevice9Ex::DrawPrimitiveUP -- slot 83, sync */
extern HRESULT d3d9_native_Device9Ex_DrawPrimitiveUP(d3d9_native_handle self, D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void *data, UINT stride);
/* IDirect3DDevice9Ex::DrawIndexedPrimitiveUP -- slot 84, sync */
extern HRESULT d3d9_native_Device9Ex_DrawIndexedPrimitiveUP(d3d9_native_handle self, D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void *index_data, D3DFORMAT index_format, const void *data, UINT stride);
/* IDirect3DDevice9Ex::ProcessVertices -- slot 85, sync */
extern HRESULT d3d9_native_Device9Ex_ProcessVertices(d3d9_native_handle self, UINT src_start_idx, UINT dst_idx, UINT vertex_count, d3d9_native_handle dst_buffer, d3d9_native_handle declaration, DWORD flags);
/* IDirect3DDevice9Ex::CreateVertexDeclaration -- slot 86, sync */
extern HRESULT d3d9_native_Device9Ex_CreateVertexDeclaration(d3d9_native_handle self, const D3DVERTEXELEMENT9 *elements, d3d9_native_handle *declaration);
/* IDirect3DDevice9Ex::SetVertexDeclaration -- slot 87, defer */
extern HRESULT d3d9_native_Device9Ex_SetVertexDeclaration(d3d9_native_handle self, d3d9_native_handle declaration);
/* IDirect3DDevice9Ex::GetVertexDeclaration -- slot 88, local */
extern HRESULT d3d9_native_Device9Ex_GetVertexDeclaration(d3d9_native_handle self, d3d9_native_handle *declaration);
/* IDirect3DDevice9Ex::SetFVF -- slot 89, defer */
extern HRESULT d3d9_native_Device9Ex_SetFVF(d3d9_native_handle self, DWORD fvf);
/* IDirect3DDevice9Ex::GetFVF -- slot 90, sync */
extern HRESULT d3d9_native_Device9Ex_GetFVF(d3d9_native_handle self, DWORD *fvf);
/* IDirect3DDevice9Ex::CreateVertexShader -- slot 91, sync */
extern HRESULT d3d9_native_Device9Ex_CreateVertexShader(d3d9_native_handle self, const DWORD *byte_code, d3d9_native_handle *shader);
/* IDirect3DDevice9Ex::SetVertexShader -- slot 92, defer */
extern HRESULT d3d9_native_Device9Ex_SetVertexShader(d3d9_native_handle self, d3d9_native_handle shader);
/* IDirect3DDevice9Ex::GetVertexShader -- slot 93, local */
extern HRESULT d3d9_native_Device9Ex_GetVertexShader(d3d9_native_handle self, d3d9_native_handle *shader);
/* IDirect3DDevice9Ex::SetVertexShaderConstantF -- slot 94, defer */
extern HRESULT d3d9_native_Device9Ex_SetVertexShaderConstantF(d3d9_native_handle self, UINT reg_idx, const float *data, UINT count);
/* IDirect3DDevice9Ex::GetVertexShaderConstantF -- slot 95, sync */
extern HRESULT d3d9_native_Device9Ex_GetVertexShaderConstantF(d3d9_native_handle self, UINT reg_idx, float *data, UINT count);
/* IDirect3DDevice9Ex::SetVertexShaderConstantI -- slot 96, defer */
extern HRESULT d3d9_native_Device9Ex_SetVertexShaderConstantI(d3d9_native_handle self, UINT reg_idx, const int *data, UINT count);
/* IDirect3DDevice9Ex::GetVertexShaderConstantI -- slot 97, sync */
extern HRESULT d3d9_native_Device9Ex_GetVertexShaderConstantI(d3d9_native_handle self, UINT reg_idx, int *data, UINT count);
/* IDirect3DDevice9Ex::SetVertexShaderConstantB -- slot 98, defer */
extern HRESULT d3d9_native_Device9Ex_SetVertexShaderConstantB(d3d9_native_handle self, UINT reg_idx, const WINBOOL *data, UINT count);
/* IDirect3DDevice9Ex::GetVertexShaderConstantB -- slot 99, sync */
extern HRESULT d3d9_native_Device9Ex_GetVertexShaderConstantB(d3d9_native_handle self, UINT reg_idx, WINBOOL *data, UINT count);
/* IDirect3DDevice9Ex::SetStreamSource -- slot 100, defer */
extern HRESULT d3d9_native_Device9Ex_SetStreamSource(d3d9_native_handle self, UINT stream_idx, d3d9_native_handle buffer, UINT offset, UINT stride);
/* IDirect3DDevice9Ex::GetStreamSource -- slot 101, local */
extern HRESULT d3d9_native_Device9Ex_GetStreamSource(d3d9_native_handle self, UINT stream_idx, d3d9_native_handle *buffer, UINT *offset, UINT *stride);
/* IDirect3DDevice9Ex::SetStreamSourceFreq -- slot 102, defer */
extern HRESULT d3d9_native_Device9Ex_SetStreamSourceFreq(d3d9_native_handle self, UINT stream_idx, UINT frequency);
/* IDirect3DDevice9Ex::GetStreamSourceFreq -- slot 103, sync */
extern HRESULT d3d9_native_Device9Ex_GetStreamSourceFreq(d3d9_native_handle self, UINT stream_idx, UINT *frequency);
/* IDirect3DDevice9Ex::SetIndices -- slot 104, defer */
extern HRESULT d3d9_native_Device9Ex_SetIndices(d3d9_native_handle self, d3d9_native_handle buffer);
/* IDirect3DDevice9Ex::GetIndices -- slot 105, local */
extern HRESULT d3d9_native_Device9Ex_GetIndices(d3d9_native_handle self, d3d9_native_handle *buffer);
/* IDirect3DDevice9Ex::CreatePixelShader -- slot 106, sync */
extern HRESULT d3d9_native_Device9Ex_CreatePixelShader(d3d9_native_handle self, const DWORD *byte_code, d3d9_native_handle *shader);
/* IDirect3DDevice9Ex::SetPixelShader -- slot 107, defer */
extern HRESULT d3d9_native_Device9Ex_SetPixelShader(d3d9_native_handle self, d3d9_native_handle shader);
/* IDirect3DDevice9Ex::GetPixelShader -- slot 108, local */
extern HRESULT d3d9_native_Device9Ex_GetPixelShader(d3d9_native_handle self, d3d9_native_handle *shader);
/* IDirect3DDevice9Ex::SetPixelShaderConstantF -- slot 109, defer */
extern HRESULT d3d9_native_Device9Ex_SetPixelShaderConstantF(d3d9_native_handle self, UINT reg_idx, const float *data, UINT count);
/* IDirect3DDevice9Ex::GetPixelShaderConstantF -- slot 110, sync */
extern HRESULT d3d9_native_Device9Ex_GetPixelShaderConstantF(d3d9_native_handle self, UINT reg_idx, float *data, UINT count);
/* IDirect3DDevice9Ex::SetPixelShaderConstantI -- slot 111, defer */
extern HRESULT d3d9_native_Device9Ex_SetPixelShaderConstantI(d3d9_native_handle self, UINT reg_idx, const int *data, UINT count);
/* IDirect3DDevice9Ex::GetPixelShaderConstantI -- slot 112, sync */
extern HRESULT d3d9_native_Device9Ex_GetPixelShaderConstantI(d3d9_native_handle self, UINT reg_idx, int *data, UINT count);
/* IDirect3DDevice9Ex::SetPixelShaderConstantB -- slot 113, defer */
extern HRESULT d3d9_native_Device9Ex_SetPixelShaderConstantB(d3d9_native_handle self, UINT reg_idx, const WINBOOL *data, UINT count);
/* IDirect3DDevice9Ex::GetPixelShaderConstantB -- slot 114, sync */
extern HRESULT d3d9_native_Device9Ex_GetPixelShaderConstantB(d3d9_native_handle self, UINT reg_idx, WINBOOL *data, UINT count);
/* IDirect3DDevice9Ex::DrawRectPatch -- slot 115, sync */
extern HRESULT d3d9_native_Device9Ex_DrawRectPatch(d3d9_native_handle self, UINT handle, const float *segment_count, const D3DRECTPATCH_INFO *patch_info);
/* IDirect3DDevice9Ex::DrawTriPatch -- slot 116, sync */
extern HRESULT d3d9_native_Device9Ex_DrawTriPatch(d3d9_native_handle self, UINT handle, const float *segment_count, const D3DTRIPATCH_INFO *patch_info);
/* IDirect3DDevice9Ex::DeletePatch -- slot 117, sync */
extern HRESULT d3d9_native_Device9Ex_DeletePatch(d3d9_native_handle self, UINT handle);
/* IDirect3DDevice9Ex::CreateQuery -- slot 118, sync */
extern HRESULT d3d9_native_Device9Ex_CreateQuery(d3d9_native_handle self, D3DQUERYTYPE type, d3d9_native_handle *query);
/* IDirect3DDevice9Ex::SetConvolutionMonoKernel -- slot 119, sync */
extern HRESULT d3d9_native_Device9Ex_SetConvolutionMonoKernel(d3d9_native_handle self, UINT width, UINT height, const float *rows, const float *columns);
/* IDirect3DDevice9Ex::ComposeRects -- slot 120, sync */
extern HRESULT d3d9_native_Device9Ex_ComposeRects(d3d9_native_handle self, d3d9_native_handle src_surface, d3d9_native_handle dst_surface, d3d9_native_handle src_descs, UINT rect_count, d3d9_native_handle dst_descs, D3DCOMPOSERECTSOP operation, INT offset_x, INT offset_y);
/* IDirect3DDevice9Ex::PresentEx -- slot 121, sync */
extern HRESULT d3d9_native_Device9Ex_PresentEx(d3d9_native_handle self, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region, DWORD flags);
/* IDirect3DDevice9Ex::GetGPUThreadPriority -- slot 122, sync */
extern HRESULT d3d9_native_Device9Ex_GetGPUThreadPriority(d3d9_native_handle self, INT *priority);
/* IDirect3DDevice9Ex::SetGPUThreadPriority -- slot 123, sync */
extern HRESULT d3d9_native_Device9Ex_SetGPUThreadPriority(d3d9_native_handle self, INT priority);
/* IDirect3DDevice9Ex::WaitForVBlank -- slot 124, sync */
extern HRESULT d3d9_native_Device9Ex_WaitForVBlank(d3d9_native_handle self, UINT swapchain_idx);
/* IDirect3DDevice9Ex::CheckResourceResidency -- slot 125, sync */
extern HRESULT d3d9_native_Device9Ex_CheckResourceResidency(d3d9_native_handle self, const uint32_t *resources, UINT32 resource_count);
/* IDirect3DDevice9Ex::SetMaximumFrameLatency -- slot 126, sync */
extern HRESULT d3d9_native_Device9Ex_SetMaximumFrameLatency(d3d9_native_handle self, UINT max_latency);
/* IDirect3DDevice9Ex::GetMaximumFrameLatency -- slot 127, sync */
extern HRESULT d3d9_native_Device9Ex_GetMaximumFrameLatency(d3d9_native_handle self, UINT *max_latency);
/* IDirect3DDevice9Ex::CheckDeviceState -- slot 128, sync */
extern HRESULT d3d9_native_Device9Ex_CheckDeviceState(d3d9_native_handle self, HWND dst_window);
/* IDirect3DDevice9Ex::CreateRenderTargetEx -- slot 129, sync */
extern HRESULT d3d9_native_Device9Ex_CreateRenderTargetEx(d3d9_native_handle self, UINT width, UINT height, D3DFORMAT format, D3DMULTISAMPLE_TYPE multisample_type, DWORD multisample_quality, WINBOOL lockable, d3d9_native_handle *surface, HANDLE *shared_handle, DWORD usage);
/* IDirect3DDevice9Ex::CreateOffscreenPlainSurfaceEx -- slot 130, sync */
extern HRESULT d3d9_native_Device9Ex_CreateOffscreenPlainSurfaceEx(d3d9_native_handle self, UINT width, UINT Height, D3DFORMAT format, D3DPOOL pool, d3d9_native_handle *surface, HANDLE *shared_handle, DWORD usage);
/* IDirect3DDevice9Ex::CreateDepthStencilSurfaceEx -- slot 131, sync */
extern HRESULT d3d9_native_Device9Ex_CreateDepthStencilSurfaceEx(d3d9_native_handle self, UINT width, UINT height, D3DFORMAT format, D3DMULTISAMPLE_TYPE multisample_type, DWORD multisample_quality, WINBOOL discard, d3d9_native_handle *surface, HANDLE *shared_handle, DWORD usage);
/* IDirect3DDevice9Ex::ResetEx -- slot 132, sync */
extern HRESULT d3d9_native_Device9Ex_ResetEx(d3d9_native_handle self, D3DPRESENT_PARAMETERS *parameters, const D3DDISPLAYMODEEX *mode);
/* IDirect3DDevice9Ex::GetDisplayModeEx -- slot 133, sync */
extern HRESULT d3d9_native_Device9Ex_GetDisplayModeEx(d3d9_native_handle self, UINT swapchain_idx, D3DDISPLAYMODEEX *mode, D3DDISPLAYROTATION *rotation);
/* IDirect3DSwapChain9Ex::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_SwapChain9Ex_QueryInterface(d3d9_native_handle self, const GUID *iid, d3d9_native_handle *out);
/* IDirect3DSwapChain9Ex::AddRef -- slot 1, local */
extern ULONG d3d9_native_SwapChain9Ex_AddRef(d3d9_native_handle self);
/* IDirect3DSwapChain9Ex::Release -- slot 2, defer */
extern ULONG d3d9_native_SwapChain9Ex_Release(d3d9_native_handle self);
/* IDirect3DSwapChain9Ex::Present -- slot 3, sync */
extern HRESULT d3d9_native_SwapChain9Ex_Present(d3d9_native_handle self, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region, DWORD flags);
/* IDirect3DSwapChain9Ex::GetFrontBufferData -- slot 4, sync */
extern HRESULT d3d9_native_SwapChain9Ex_GetFrontBufferData(d3d9_native_handle self, d3d9_native_handle dst_surface);
/* IDirect3DSwapChain9Ex::GetBackBuffer -- slot 5, resolve */
extern HRESULT d3d9_native_SwapChain9Ex_GetBackBuffer(d3d9_native_handle self, UINT backbuffer_idx, D3DBACKBUFFER_TYPE backbuffer_type, d3d9_native_handle *backbuffer);
/* IDirect3DSwapChain9Ex::GetRasterStatus -- slot 6, sync */
extern HRESULT d3d9_native_SwapChain9Ex_GetRasterStatus(d3d9_native_handle self, D3DRASTER_STATUS *raster_status);
/* IDirect3DSwapChain9Ex::GetDisplayMode -- slot 7, sync */
extern HRESULT d3d9_native_SwapChain9Ex_GetDisplayMode(d3d9_native_handle self, D3DDISPLAYMODE *mode);
/* IDirect3DSwapChain9Ex::GetDevice -- slot 8, local */
extern HRESULT d3d9_native_SwapChain9Ex_GetDevice(d3d9_native_handle self, d3d9_native_handle *device);
/* IDirect3DSwapChain9Ex::GetPresentParameters -- slot 9, sync */
extern HRESULT d3d9_native_SwapChain9Ex_GetPresentParameters(d3d9_native_handle self, D3DPRESENT_PARAMETERS *parameters);
/* IDirect3DSwapChain9Ex::GetLastPresentCount -- slot 10, sync */
extern HRESULT d3d9_native_SwapChain9Ex_GetLastPresentCount(d3d9_native_handle self, UINT *last_present_count);
/* IDirect3DSwapChain9Ex::GetPresentStats -- slot 11, sync */
extern HRESULT d3d9_native_SwapChain9Ex_GetPresentStats(d3d9_native_handle self, D3DPRESENTSTATS *stats);
/* IDirect3DSwapChain9Ex::GetDisplayModeEx -- slot 12, sync */
extern HRESULT d3d9_native_SwapChain9Ex_GetDisplayModeEx(d3d9_native_handle self, D3DDISPLAYMODEEX *mode, D3DDISPLAYROTATION *rotation);
/* IDirect3DSurface9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_Surface9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DSurface9::AddRef -- slot 1, local */
extern ULONG d3d9_native_Surface9_AddRef(d3d9_native_handle self);
/* IDirect3DSurface9::Release -- slot 2, defer */
extern ULONG d3d9_native_Surface9_Release(d3d9_native_handle self);
/* IDirect3DSurface9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_Surface9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DSurface9::SetPrivateData -- slot 4, sync */
extern HRESULT d3d9_native_Surface9_SetPrivateData(d3d9_native_handle self, const GUID *guid, const BYTE *data, DWORD data_size, DWORD flags);
/* IDirect3DSurface9::GetPrivateData -- slot 5, sync */
extern HRESULT d3d9_native_Surface9_GetPrivateData(d3d9_native_handle self, const GUID *refguid, BYTE *pData, DWORD *pSizeOfData);
/* IDirect3DSurface9::FreePrivateData -- slot 6, sync */
extern HRESULT d3d9_native_Surface9_FreePrivateData(d3d9_native_handle self, const GUID *refguid);
/* IDirect3DSurface9::SetPriority -- slot 7, defer */
extern DWORD d3d9_native_Surface9_SetPriority(d3d9_native_handle self, DWORD PriorityNew);
/* IDirect3DSurface9::GetPriority -- slot 8, sync */
extern DWORD d3d9_native_Surface9_GetPriority(d3d9_native_handle self);
/* IDirect3DSurface9::PreLoad -- slot 9, defer */
extern void d3d9_native_Surface9_PreLoad(d3d9_native_handle self);
/* IDirect3DSurface9::GetType -- slot 10, local */
extern D3DRESOURCETYPE d3d9_native_Surface9_GetType(d3d9_native_handle self);
/* IDirect3DSurface9::GetContainer -- slot 11, local */
extern HRESULT d3d9_native_Surface9_GetContainer(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppContainer);
/* IDirect3DSurface9::GetDesc -- slot 12, sync */
extern HRESULT d3d9_native_Surface9_GetDesc(d3d9_native_handle self, D3DSURFACE_DESC *pDesc);
/* IDirect3DSurface9::LockRect -- slot 13, sync */
extern HRESULT d3d9_native_Surface9_LockRect(d3d9_native_handle self, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
/* IDirect3DSurface9::UnlockRect -- slot 14, sync */
extern HRESULT d3d9_native_Surface9_UnlockRect(d3d9_native_handle self);
/* IDirect3DSurface9::GetDC -- slot 15, sync */
extern HRESULT d3d9_native_Surface9_GetDC(d3d9_native_handle self, HANDLE phdc);
/* IDirect3DSurface9::ReleaseDC -- slot 16, sync */
extern HRESULT d3d9_native_Surface9_ReleaseDC(d3d9_native_handle self, HANDLE hdc);
/* IDirect3DTexture9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_Texture9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DTexture9::AddRef -- slot 1, local */
extern ULONG d3d9_native_Texture9_AddRef(d3d9_native_handle self);
/* IDirect3DTexture9::Release -- slot 2, defer */
extern ULONG d3d9_native_Texture9_Release(d3d9_native_handle self);
/* IDirect3DTexture9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_Texture9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DTexture9::SetPrivateData -- slot 4, sync */
extern HRESULT d3d9_native_Texture9_SetPrivateData(d3d9_native_handle self, const GUID *guid, const BYTE *data, DWORD data_size, DWORD flags);
/* IDirect3DTexture9::GetPrivateData -- slot 5, sync */
extern HRESULT d3d9_native_Texture9_GetPrivateData(d3d9_native_handle self, const GUID *refguid, BYTE *pData, DWORD *pSizeOfData);
/* IDirect3DTexture9::FreePrivateData -- slot 6, sync */
extern HRESULT d3d9_native_Texture9_FreePrivateData(d3d9_native_handle self, const GUID *refguid);
/* IDirect3DTexture9::SetPriority -- slot 7, defer */
extern DWORD d3d9_native_Texture9_SetPriority(d3d9_native_handle self, DWORD PriorityNew);
/* IDirect3DTexture9::GetPriority -- slot 8, sync */
extern DWORD d3d9_native_Texture9_GetPriority(d3d9_native_handle self);
/* IDirect3DTexture9::PreLoad -- slot 9, defer */
extern void d3d9_native_Texture9_PreLoad(d3d9_native_handle self);
/* IDirect3DTexture9::GetType -- slot 10, local */
extern D3DRESOURCETYPE d3d9_native_Texture9_GetType(d3d9_native_handle self);
/* IDirect3DTexture9::SetLOD -- slot 11, defer */
extern DWORD d3d9_native_Texture9_SetLOD(d3d9_native_handle self, DWORD LODNew);
/* IDirect3DTexture9::GetLOD -- slot 12, sync */
extern DWORD d3d9_native_Texture9_GetLOD(d3d9_native_handle self);
/* IDirect3DTexture9::GetLevelCount -- slot 13, sync */
extern DWORD d3d9_native_Texture9_GetLevelCount(d3d9_native_handle self);
/* IDirect3DTexture9::SetAutoGenFilterType -- slot 14, defer */
extern HRESULT d3d9_native_Texture9_SetAutoGenFilterType(d3d9_native_handle self, D3DTEXTUREFILTERTYPE FilterType);
/* IDirect3DTexture9::GetAutoGenFilterType -- slot 15, sync */
extern D3DTEXTUREFILTERTYPE d3d9_native_Texture9_GetAutoGenFilterType(d3d9_native_handle self);
/* IDirect3DTexture9::GenerateMipSubLevels -- slot 16, sync */
extern void d3d9_native_Texture9_GenerateMipSubLevels(d3d9_native_handle self);
/* IDirect3DTexture9::GetLevelDesc -- slot 17, sync */
extern HRESULT d3d9_native_Texture9_GetLevelDesc(d3d9_native_handle self, UINT Level, D3DSURFACE_DESC *pDesc);
/* IDirect3DTexture9::GetSurfaceLevel -- slot 18, resolve */
extern HRESULT d3d9_native_Texture9_GetSurfaceLevel(d3d9_native_handle self, UINT Level, d3d9_native_handle *ppSurfaceLevel);
/* IDirect3DTexture9::LockRect -- slot 19, sync */
extern HRESULT d3d9_native_Texture9_LockRect(d3d9_native_handle self, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
/* IDirect3DTexture9::UnlockRect -- slot 20, sync */
extern HRESULT d3d9_native_Texture9_UnlockRect(d3d9_native_handle self, UINT Level);
/* IDirect3DTexture9::AddDirtyRect -- slot 21, defer */
extern HRESULT d3d9_native_Texture9_AddDirtyRect(d3d9_native_handle self, const RECT *dirty_rect);
/* IDirect3DCubeTexture9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_CubeTexture9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DCubeTexture9::AddRef -- slot 1, local */
extern ULONG d3d9_native_CubeTexture9_AddRef(d3d9_native_handle self);
/* IDirect3DCubeTexture9::Release -- slot 2, defer */
extern ULONG d3d9_native_CubeTexture9_Release(d3d9_native_handle self);
/* IDirect3DCubeTexture9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_CubeTexture9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DCubeTexture9::SetPrivateData -- slot 4, sync */
extern HRESULT d3d9_native_CubeTexture9_SetPrivateData(d3d9_native_handle self, const GUID *guid, const BYTE *data, DWORD data_size, DWORD flags);
/* IDirect3DCubeTexture9::GetPrivateData -- slot 5, sync */
extern HRESULT d3d9_native_CubeTexture9_GetPrivateData(d3d9_native_handle self, const GUID *refguid, BYTE *pData, DWORD *pSizeOfData);
/* IDirect3DCubeTexture9::FreePrivateData -- slot 6, sync */
extern HRESULT d3d9_native_CubeTexture9_FreePrivateData(d3d9_native_handle self, const GUID *refguid);
/* IDirect3DCubeTexture9::SetPriority -- slot 7, defer */
extern DWORD d3d9_native_CubeTexture9_SetPriority(d3d9_native_handle self, DWORD PriorityNew);
/* IDirect3DCubeTexture9::GetPriority -- slot 8, sync */
extern DWORD d3d9_native_CubeTexture9_GetPriority(d3d9_native_handle self);
/* IDirect3DCubeTexture9::PreLoad -- slot 9, defer */
extern void d3d9_native_CubeTexture9_PreLoad(d3d9_native_handle self);
/* IDirect3DCubeTexture9::GetType -- slot 10, local */
extern D3DRESOURCETYPE d3d9_native_CubeTexture9_GetType(d3d9_native_handle self);
/* IDirect3DCubeTexture9::SetLOD -- slot 11, defer */
extern DWORD d3d9_native_CubeTexture9_SetLOD(d3d9_native_handle self, DWORD LODNew);
/* IDirect3DCubeTexture9::GetLOD -- slot 12, sync */
extern DWORD d3d9_native_CubeTexture9_GetLOD(d3d9_native_handle self);
/* IDirect3DCubeTexture9::GetLevelCount -- slot 13, sync */
extern DWORD d3d9_native_CubeTexture9_GetLevelCount(d3d9_native_handle self);
/* IDirect3DCubeTexture9::SetAutoGenFilterType -- slot 14, defer */
extern HRESULT d3d9_native_CubeTexture9_SetAutoGenFilterType(d3d9_native_handle self, D3DTEXTUREFILTERTYPE FilterType);
/* IDirect3DCubeTexture9::GetAutoGenFilterType -- slot 15, sync */
extern D3DTEXTUREFILTERTYPE d3d9_native_CubeTexture9_GetAutoGenFilterType(d3d9_native_handle self);
/* IDirect3DCubeTexture9::GenerateMipSubLevels -- slot 16, sync */
extern void d3d9_native_CubeTexture9_GenerateMipSubLevels(d3d9_native_handle self);
/* IDirect3DCubeTexture9::GetLevelDesc -- slot 17, sync */
extern HRESULT d3d9_native_CubeTexture9_GetLevelDesc(d3d9_native_handle self, UINT Level, D3DSURFACE_DESC *pDesc);
/* IDirect3DCubeTexture9::GetCubeMapSurface -- slot 18, resolve */
extern HRESULT d3d9_native_CubeTexture9_GetCubeMapSurface(d3d9_native_handle self, D3DCUBEMAP_FACES FaceType, UINT Level, d3d9_native_handle *ppCubeMapSurface);
/* IDirect3DCubeTexture9::LockRect -- slot 19, sync */
extern HRESULT d3d9_native_CubeTexture9_LockRect(d3d9_native_handle self, D3DCUBEMAP_FACES face, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
/* IDirect3DCubeTexture9::UnlockRect -- slot 20, sync */
extern HRESULT d3d9_native_CubeTexture9_UnlockRect(d3d9_native_handle self, D3DCUBEMAP_FACES FaceType, UINT Level);
/* IDirect3DCubeTexture9::AddDirtyRect -- slot 21, defer */
extern HRESULT d3d9_native_CubeTexture9_AddDirtyRect(d3d9_native_handle self, D3DCUBEMAP_FACES face, const RECT *dirty_rect);
/* IDirect3DVolumeTexture9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_VolumeTexture9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DVolumeTexture9::AddRef -- slot 1, local */
extern ULONG d3d9_native_VolumeTexture9_AddRef(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::Release -- slot 2, defer */
extern ULONG d3d9_native_VolumeTexture9_Release(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_VolumeTexture9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DVolumeTexture9::SetPrivateData -- slot 4, sync */
extern HRESULT d3d9_native_VolumeTexture9_SetPrivateData(d3d9_native_handle self, const GUID *guid, const BYTE *data, DWORD data_size, DWORD flags);
/* IDirect3DVolumeTexture9::GetPrivateData -- slot 5, sync */
extern HRESULT d3d9_native_VolumeTexture9_GetPrivateData(d3d9_native_handle self, const GUID *refguid, BYTE *pData, DWORD *pSizeOfData);
/* IDirect3DVolumeTexture9::FreePrivateData -- slot 6, sync */
extern HRESULT d3d9_native_VolumeTexture9_FreePrivateData(d3d9_native_handle self, const GUID *refguid);
/* IDirect3DVolumeTexture9::SetPriority -- slot 7, defer */
extern DWORD d3d9_native_VolumeTexture9_SetPriority(d3d9_native_handle self, DWORD PriorityNew);
/* IDirect3DVolumeTexture9::GetPriority -- slot 8, sync */
extern DWORD d3d9_native_VolumeTexture9_GetPriority(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::PreLoad -- slot 9, defer */
extern void d3d9_native_VolumeTexture9_PreLoad(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::GetType -- slot 10, local */
extern D3DRESOURCETYPE d3d9_native_VolumeTexture9_GetType(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::SetLOD -- slot 11, defer */
extern DWORD d3d9_native_VolumeTexture9_SetLOD(d3d9_native_handle self, DWORD LODNew);
/* IDirect3DVolumeTexture9::GetLOD -- slot 12, sync */
extern DWORD d3d9_native_VolumeTexture9_GetLOD(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::GetLevelCount -- slot 13, sync */
extern DWORD d3d9_native_VolumeTexture9_GetLevelCount(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::SetAutoGenFilterType -- slot 14, defer */
extern HRESULT d3d9_native_VolumeTexture9_SetAutoGenFilterType(d3d9_native_handle self, D3DTEXTUREFILTERTYPE FilterType);
/* IDirect3DVolumeTexture9::GetAutoGenFilterType -- slot 15, sync */
extern D3DTEXTUREFILTERTYPE d3d9_native_VolumeTexture9_GetAutoGenFilterType(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::GenerateMipSubLevels -- slot 16, sync */
extern void d3d9_native_VolumeTexture9_GenerateMipSubLevels(d3d9_native_handle self);
/* IDirect3DVolumeTexture9::GetLevelDesc -- slot 17, sync */
extern HRESULT d3d9_native_VolumeTexture9_GetLevelDesc(d3d9_native_handle self, UINT Level, D3DVOLUME_DESC *pDesc);
/* IDirect3DVolumeTexture9::GetVolumeLevel -- slot 18, resolve */
extern HRESULT d3d9_native_VolumeTexture9_GetVolumeLevel(d3d9_native_handle self, UINT Level, d3d9_native_handle *ppVolumeLevel);
/* IDirect3DVolumeTexture9::LockBox -- slot 19, sync */
extern HRESULT d3d9_native_VolumeTexture9_LockBox(d3d9_native_handle self, UINT level, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags);
/* IDirect3DVolumeTexture9::UnlockBox -- slot 20, sync */
extern HRESULT d3d9_native_VolumeTexture9_UnlockBox(d3d9_native_handle self, UINT Level);
/* IDirect3DVolumeTexture9::AddDirtyBox -- slot 21, defer */
extern HRESULT d3d9_native_VolumeTexture9_AddDirtyBox(d3d9_native_handle self, const D3DBOX *dirty_box);
/* IDirect3DVolume9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_Volume9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DVolume9::AddRef -- slot 1, local */
extern ULONG d3d9_native_Volume9_AddRef(d3d9_native_handle self);
/* IDirect3DVolume9::Release -- slot 2, defer */
extern ULONG d3d9_native_Volume9_Release(d3d9_native_handle self);
/* IDirect3DVolume9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_Volume9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DVolume9::SetPrivateData -- slot 4, sync */
extern HRESULT d3d9_native_Volume9_SetPrivateData(d3d9_native_handle self, const GUID *guid, const BYTE *data, DWORD data_size, DWORD flags);
/* IDirect3DVolume9::GetPrivateData -- slot 5, sync */
extern HRESULT d3d9_native_Volume9_GetPrivateData(d3d9_native_handle self, const GUID *refguid, BYTE *pData, DWORD *pSizeOfData);
/* IDirect3DVolume9::FreePrivateData -- slot 6, sync */
extern HRESULT d3d9_native_Volume9_FreePrivateData(d3d9_native_handle self, const GUID *refguid);
/* IDirect3DVolume9::GetContainer -- slot 7, local */
extern HRESULT d3d9_native_Volume9_GetContainer(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppContainer);
/* IDirect3DVolume9::GetDesc -- slot 8, sync */
extern HRESULT d3d9_native_Volume9_GetDesc(d3d9_native_handle self, D3DVOLUME_DESC *pDesc);
/* IDirect3DVolume9::LockBox -- slot 9, sync */
extern HRESULT d3d9_native_Volume9_LockBox(d3d9_native_handle self, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags);
/* IDirect3DVolume9::UnlockBox -- slot 10, sync */
extern HRESULT d3d9_native_Volume9_UnlockBox(d3d9_native_handle self);
/* IDirect3DVertexBuffer9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_VertexBuffer9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DVertexBuffer9::AddRef -- slot 1, local */
extern ULONG d3d9_native_VertexBuffer9_AddRef(d3d9_native_handle self);
/* IDirect3DVertexBuffer9::Release -- slot 2, defer */
extern ULONG d3d9_native_VertexBuffer9_Release(d3d9_native_handle self);
/* IDirect3DVertexBuffer9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_VertexBuffer9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DVertexBuffer9::SetPrivateData -- slot 4, sync */
extern HRESULT d3d9_native_VertexBuffer9_SetPrivateData(d3d9_native_handle self, const GUID *guid, const BYTE *data, DWORD data_size, DWORD flags);
/* IDirect3DVertexBuffer9::GetPrivateData -- slot 5, sync */
extern HRESULT d3d9_native_VertexBuffer9_GetPrivateData(d3d9_native_handle self, const GUID *refguid, BYTE *pData, DWORD *pSizeOfData);
/* IDirect3DVertexBuffer9::FreePrivateData -- slot 6, sync */
extern HRESULT d3d9_native_VertexBuffer9_FreePrivateData(d3d9_native_handle self, const GUID *refguid);
/* IDirect3DVertexBuffer9::SetPriority -- slot 7, defer */
extern DWORD d3d9_native_VertexBuffer9_SetPriority(d3d9_native_handle self, DWORD PriorityNew);
/* IDirect3DVertexBuffer9::GetPriority -- slot 8, sync */
extern DWORD d3d9_native_VertexBuffer9_GetPriority(d3d9_native_handle self);
/* IDirect3DVertexBuffer9::PreLoad -- slot 9, defer */
extern void d3d9_native_VertexBuffer9_PreLoad(d3d9_native_handle self);
/* IDirect3DVertexBuffer9::GetType -- slot 10, local */
extern D3DRESOURCETYPE d3d9_native_VertexBuffer9_GetType(d3d9_native_handle self);
/* IDirect3DVertexBuffer9::Lock -- slot 11, sync */
extern HRESULT d3d9_native_VertexBuffer9_Lock(d3d9_native_handle self, UINT OffsetToLock, UINT SizeToLock, void **ppbData, DWORD Flags);
/* IDirect3DVertexBuffer9::Unlock -- slot 12, sync */
extern HRESULT d3d9_native_VertexBuffer9_Unlock(d3d9_native_handle self);
/* IDirect3DVertexBuffer9::GetDesc -- slot 13, sync */
extern HRESULT d3d9_native_VertexBuffer9_GetDesc(d3d9_native_handle self, D3DVERTEXBUFFER_DESC *pDesc);
/* IDirect3DIndexBuffer9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_IndexBuffer9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DIndexBuffer9::AddRef -- slot 1, local */
extern ULONG d3d9_native_IndexBuffer9_AddRef(d3d9_native_handle self);
/* IDirect3DIndexBuffer9::Release -- slot 2, defer */
extern ULONG d3d9_native_IndexBuffer9_Release(d3d9_native_handle self);
/* IDirect3DIndexBuffer9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_IndexBuffer9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DIndexBuffer9::SetPrivateData -- slot 4, sync */
extern HRESULT d3d9_native_IndexBuffer9_SetPrivateData(d3d9_native_handle self, const GUID *guid, const BYTE *data, DWORD data_size, DWORD flags);
/* IDirect3DIndexBuffer9::GetPrivateData -- slot 5, sync */
extern HRESULT d3d9_native_IndexBuffer9_GetPrivateData(d3d9_native_handle self, const GUID *refguid, BYTE *pData, DWORD *pSizeOfData);
/* IDirect3DIndexBuffer9::FreePrivateData -- slot 6, sync */
extern HRESULT d3d9_native_IndexBuffer9_FreePrivateData(d3d9_native_handle self, const GUID *refguid);
/* IDirect3DIndexBuffer9::SetPriority -- slot 7, defer */
extern DWORD d3d9_native_IndexBuffer9_SetPriority(d3d9_native_handle self, DWORD PriorityNew);
/* IDirect3DIndexBuffer9::GetPriority -- slot 8, sync */
extern DWORD d3d9_native_IndexBuffer9_GetPriority(d3d9_native_handle self);
/* IDirect3DIndexBuffer9::PreLoad -- slot 9, defer */
extern void d3d9_native_IndexBuffer9_PreLoad(d3d9_native_handle self);
/* IDirect3DIndexBuffer9::GetType -- slot 10, local */
extern D3DRESOURCETYPE d3d9_native_IndexBuffer9_GetType(d3d9_native_handle self);
/* IDirect3DIndexBuffer9::Lock -- slot 11, sync */
extern HRESULT d3d9_native_IndexBuffer9_Lock(d3d9_native_handle self, UINT OffsetToLock, UINT SizeToLock, void **ppbData, DWORD Flags);
/* IDirect3DIndexBuffer9::Unlock -- slot 12, sync */
extern HRESULT d3d9_native_IndexBuffer9_Unlock(d3d9_native_handle self);
/* IDirect3DIndexBuffer9::GetDesc -- slot 13, sync */
extern HRESULT d3d9_native_IndexBuffer9_GetDesc(d3d9_native_handle self, D3DINDEXBUFFER_DESC *pDesc);
/* IDirect3DVertexDeclaration9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_VertexDeclaration9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DVertexDeclaration9::AddRef -- slot 1, local */
extern ULONG d3d9_native_VertexDeclaration9_AddRef(d3d9_native_handle self);
/* IDirect3DVertexDeclaration9::Release -- slot 2, defer */
extern ULONG d3d9_native_VertexDeclaration9_Release(d3d9_native_handle self);
/* IDirect3DVertexDeclaration9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_VertexDeclaration9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DVertexDeclaration9::GetDeclaration -- slot 4, sync */
extern HRESULT d3d9_native_VertexDeclaration9_GetDeclaration(d3d9_native_handle self, D3DVERTEXELEMENT9 *arg, UINT *pNumElements);
/* IDirect3DVertexShader9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_VertexShader9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DVertexShader9::AddRef -- slot 1, local */
extern ULONG d3d9_native_VertexShader9_AddRef(d3d9_native_handle self);
/* IDirect3DVertexShader9::Release -- slot 2, defer */
extern ULONG d3d9_native_VertexShader9_Release(d3d9_native_handle self);
/* IDirect3DVertexShader9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_VertexShader9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DVertexShader9::GetFunction -- slot 4, sync */
extern HRESULT d3d9_native_VertexShader9_GetFunction(d3d9_native_handle self, BYTE *arg, UINT *pSizeOfData);
/* IDirect3DPixelShader9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_PixelShader9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DPixelShader9::AddRef -- slot 1, local */
extern ULONG d3d9_native_PixelShader9_AddRef(d3d9_native_handle self);
/* IDirect3DPixelShader9::Release -- slot 2, defer */
extern ULONG d3d9_native_PixelShader9_Release(d3d9_native_handle self);
/* IDirect3DPixelShader9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_PixelShader9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DPixelShader9::GetFunction -- slot 4, sync */
extern HRESULT d3d9_native_PixelShader9_GetFunction(d3d9_native_handle self, BYTE *arg, UINT *pSizeOfData);
/* IDirect3DStateBlock9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_StateBlock9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DStateBlock9::AddRef -- slot 1, local */
extern ULONG d3d9_native_StateBlock9_AddRef(d3d9_native_handle self);
/* IDirect3DStateBlock9::Release -- slot 2, defer */
extern ULONG d3d9_native_StateBlock9_Release(d3d9_native_handle self);
/* IDirect3DStateBlock9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_StateBlock9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DStateBlock9::Capture -- slot 4, sync */
extern HRESULT d3d9_native_StateBlock9_Capture(d3d9_native_handle self);
/* IDirect3DStateBlock9::Apply -- slot 5, defer */
extern HRESULT d3d9_native_StateBlock9_Apply(d3d9_native_handle self);
/* IDirect3DQuery9::QueryInterface -- slot 0, local */
extern HRESULT d3d9_native_Query9_QueryInterface(d3d9_native_handle self, const GUID *riid, d3d9_native_handle *ppvObject);
/* IDirect3DQuery9::AddRef -- slot 1, local */
extern ULONG d3d9_native_Query9_AddRef(d3d9_native_handle self);
/* IDirect3DQuery9::Release -- slot 2, defer */
extern ULONG d3d9_native_Query9_Release(d3d9_native_handle self);
/* IDirect3DQuery9::GetDevice -- slot 3, local */
extern HRESULT d3d9_native_Query9_GetDevice(d3d9_native_handle self, d3d9_native_handle *ppDevice);
/* IDirect3DQuery9::GetType -- slot 4, local */
extern D3DQUERYTYPE d3d9_native_Query9_GetType(d3d9_native_handle self);
/* IDirect3DQuery9::GetDataSize -- slot 5, sync */
extern DWORD d3d9_native_Query9_GetDataSize(d3d9_native_handle self);
/* IDirect3DQuery9::Issue -- slot 6, defer */
extern HRESULT d3d9_native_Query9_Issue(d3d9_native_handle self, DWORD dwIssueFlags);
/* IDirect3DQuery9::GetData -- slot 7, sync */
extern HRESULT d3d9_native_Query9_GetData(d3d9_native_handle self, BYTE *pData, DWORD dwSize, DWORD dwGetDataFlags);

/* The three TRANSPORT hooks.  Not vtable methods -- the guest arena
 * registration (8.2(c)), the per-HWND state cache (8.2(d)) and the creation
 * of the IDirect3D9(Ex) every other call self descends from, which is a DLL
 * export rather than a slot. */
/* transport slot 321 -- 0 on success */
extern int d3d9_native_arena_register(uint32_t guest_base, uint64_t size);
/* transport slot 322 -- an HRESULT */
extern HRESULT d3d9_native_window_state(HWND hwnd, uint32_t width, uint32_t height, uint32_t flags);
/* transport slot 323 -- an HRESULT */
extern HRESULT d3d9_native_create_interface(d3d9_native_handle *iface, uint32_t sdk_version, uint32_t is_ex);

#ifdef __cplusplus
}
#endif

#endif /* __MADEIRA_D3D9_NATIVE_HOOKS_H */
