/*
 * d3d9_unix_table.c -- the two dispatch tables
 *
 * GENERATED by research/dxmt/src/d3d9shim/gen_d3d9_thunks.py from
 * research/dxmt/src/d3d9shim/d3d9_api.py.  REGENERATE, DO NOT EDIT.
 *
 * The slot number IS the ABI -- a hand edit that inserts or drops one line
 * silently sends every later call to the wrong function.  d3d9_api.py is the
 * only place any of this may be changed.
 *
 * Copyright 2026 Will Faust
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include "d3d9shim_ops.h"
#include "d3d9_unix_glue.h"

/* WOW64_DESIGN.md 7.4 rule 3: both tables the same length, the 32-bit
 * variant at the SAME index as its 64-bit twin.  Here they are the same
 * FUNCTIONS as well, and that is a property of the wire format rather than
 * a shortcut: a parameter block's pointer fields are uint32_t, so a block
 * can only have been written by a 32-bit caller and there is exactly one
 * correct way to read one.  A _32 variant would have nothing to do
 * differently.  The 64-bit table is present because load_builtin_unixlib
 * binds a PAIR; _d3d9_init refuses any caller whose pointer width is not 4,
 * so the 64-bit table can be entered but never lies about the result. */

/* Defined in d3d9_unix.c, one per slot. */
extern NTSTATUS _d3d9_init(void *args);
extern NTSTATUS _d3d9_D3D9Ex_QueryInterface(void *args);
extern NTSTATUS _d3d9_D3D9Ex_AddRef(void *args);
extern NTSTATUS _d3d9_D3D9Ex_Release(void *args);
extern NTSTATUS _d3d9_D3D9Ex_RegisterSoftwareDevice(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterCount(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterIdentifier(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterModeCount(void *args);
extern NTSTATUS _d3d9_D3D9Ex_EnumAdapterModes(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterDisplayMode(void *args);
extern NTSTATUS _d3d9_D3D9Ex_CheckDeviceType(void *args);
extern NTSTATUS _d3d9_D3D9Ex_CheckDeviceFormat(void *args);
extern NTSTATUS _d3d9_D3D9Ex_CheckDeviceMultiSampleType(void *args);
extern NTSTATUS _d3d9_D3D9Ex_CheckDepthStencilMatch(void *args);
extern NTSTATUS _d3d9_D3D9Ex_CheckDeviceFormatConversion(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetDeviceCaps(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterMonitor(void *args);
extern NTSTATUS _d3d9_D3D9Ex_CreateDevice(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterModeCountEx(void *args);
extern NTSTATUS _d3d9_D3D9Ex_EnumAdapterModesEx(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterDisplayModeEx(void *args);
extern NTSTATUS _d3d9_D3D9Ex_CreateDeviceEx(void *args);
extern NTSTATUS _d3d9_D3D9Ex_GetAdapterLUID(void *args);
extern NTSTATUS _d3d9_Device9Ex_QueryInterface(void *args);
extern NTSTATUS _d3d9_Device9Ex_AddRef(void *args);
extern NTSTATUS _d3d9_Device9Ex_Release(void *args);
extern NTSTATUS _d3d9_Device9Ex_TestCooperativeLevel(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetAvailableTextureMem(void *args);
extern NTSTATUS _d3d9_Device9Ex_EvictManagedResources(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetDirect3D(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetDeviceCaps(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetDisplayMode(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetCreationParameters(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetCursorProperties(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetCursorPosition(void *args);
extern NTSTATUS _d3d9_Device9Ex_ShowCursor(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateAdditionalSwapChain(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetSwapChain(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetNumberOfSwapChains(void *args);
extern NTSTATUS _d3d9_Device9Ex_Reset(void *args);
extern NTSTATUS _d3d9_Device9Ex_Present(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetBackBuffer(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetRasterStatus(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetDialogBoxMode(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetGammaRamp(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetGammaRamp(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateTexture(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateVolumeTexture(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateCubeTexture(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateVertexBuffer(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateIndexBuffer(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateRenderTarget(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateDepthStencilSurface(void *args);
extern NTSTATUS _d3d9_Device9Ex_UpdateSurface(void *args);
extern NTSTATUS _d3d9_Device9Ex_UpdateTexture(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetRenderTargetData(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetFrontBufferData(void *args);
extern NTSTATUS _d3d9_Device9Ex_StretchRect(void *args);
extern NTSTATUS _d3d9_Device9Ex_ColorFill(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateOffscreenPlainSurface(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetRenderTarget(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetRenderTarget(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetDepthStencilSurface(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetDepthStencilSurface(void *args);
extern NTSTATUS _d3d9_Device9Ex_BeginScene(void *args);
extern NTSTATUS _d3d9_Device9Ex_EndScene(void *args);
extern NTSTATUS _d3d9_Device9Ex_Clear(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetTransform(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetTransform(void *args);
extern NTSTATUS _d3d9_Device9Ex_MultiplyTransform(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetViewport(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetViewport(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetMaterial(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetMaterial(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetLight(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetLight(void *args);
extern NTSTATUS _d3d9_Device9Ex_LightEnable(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetLightEnable(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetClipPlane(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetClipPlane(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetRenderState(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetRenderState(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateStateBlock(void *args);
extern NTSTATUS _d3d9_Device9Ex_BeginStateBlock(void *args);
extern NTSTATUS _d3d9_Device9Ex_EndStateBlock(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetClipStatus(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetClipStatus(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetTexture(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetTexture(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetTextureStageState(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetTextureStageState(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetSamplerState(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetSamplerState(void *args);
extern NTSTATUS _d3d9_Device9Ex_ValidateDevice(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetPaletteEntries(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetPaletteEntries(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetCurrentTexturePalette(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetCurrentTexturePalette(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetScissorRect(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetScissorRect(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetSoftwareVertexProcessing(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetSoftwareVertexProcessing(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetNPatchMode(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetNPatchMode(void *args);
extern NTSTATUS _d3d9_Device9Ex_DrawPrimitive(void *args);
extern NTSTATUS _d3d9_Device9Ex_DrawIndexedPrimitive(void *args);
extern NTSTATUS _d3d9_Device9Ex_DrawPrimitiveUP(void *args);
extern NTSTATUS _d3d9_Device9Ex_DrawIndexedPrimitiveUP(void *args);
extern NTSTATUS _d3d9_Device9Ex_ProcessVertices(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateVertexDeclaration(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetVertexDeclaration(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetVertexDeclaration(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetFVF(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetFVF(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateVertexShader(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetVertexShader(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetVertexShader(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetVertexShaderConstantF(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetVertexShaderConstantF(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetVertexShaderConstantI(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetVertexShaderConstantI(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetVertexShaderConstantB(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetVertexShaderConstantB(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetStreamSource(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetStreamSource(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetStreamSourceFreq(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetStreamSourceFreq(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetIndices(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetIndices(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreatePixelShader(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetPixelShader(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetPixelShader(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetPixelShaderConstantF(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetPixelShaderConstantF(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetPixelShaderConstantI(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetPixelShaderConstantI(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetPixelShaderConstantB(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetPixelShaderConstantB(void *args);
extern NTSTATUS _d3d9_Device9Ex_DrawRectPatch(void *args);
extern NTSTATUS _d3d9_Device9Ex_DrawTriPatch(void *args);
extern NTSTATUS _d3d9_Device9Ex_DeletePatch(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateQuery(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetConvolutionMonoKernel(void *args);
extern NTSTATUS _d3d9_Device9Ex_ComposeRects(void *args);
extern NTSTATUS _d3d9_Device9Ex_PresentEx(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetGPUThreadPriority(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetGPUThreadPriority(void *args);
extern NTSTATUS _d3d9_Device9Ex_WaitForVBlank(void *args);
extern NTSTATUS _d3d9_Device9Ex_CheckResourceResidency(void *args);
extern NTSTATUS _d3d9_Device9Ex_SetMaximumFrameLatency(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetMaximumFrameLatency(void *args);
extern NTSTATUS _d3d9_Device9Ex_CheckDeviceState(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateRenderTargetEx(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateOffscreenPlainSurfaceEx(void *args);
extern NTSTATUS _d3d9_Device9Ex_CreateDepthStencilSurfaceEx(void *args);
extern NTSTATUS _d3d9_Device9Ex_ResetEx(void *args);
extern NTSTATUS _d3d9_Device9Ex_GetDisplayModeEx(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_QueryInterface(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_AddRef(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_Release(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_Present(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetFrontBufferData(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetBackBuffer(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetRasterStatus(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetDisplayMode(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetDevice(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetPresentParameters(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetLastPresentCount(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetPresentStats(void *args);
extern NTSTATUS _d3d9_SwapChain9Ex_GetDisplayModeEx(void *args);
extern NTSTATUS _d3d9_Surface9_QueryInterface(void *args);
extern NTSTATUS _d3d9_Surface9_AddRef(void *args);
extern NTSTATUS _d3d9_Surface9_Release(void *args);
extern NTSTATUS _d3d9_Surface9_GetDevice(void *args);
extern NTSTATUS _d3d9_Surface9_SetPrivateData(void *args);
extern NTSTATUS _d3d9_Surface9_GetPrivateData(void *args);
extern NTSTATUS _d3d9_Surface9_FreePrivateData(void *args);
extern NTSTATUS _d3d9_Surface9_SetPriority(void *args);
extern NTSTATUS _d3d9_Surface9_GetPriority(void *args);
extern NTSTATUS _d3d9_Surface9_PreLoad(void *args);
extern NTSTATUS _d3d9_Surface9_GetType(void *args);
extern NTSTATUS _d3d9_Surface9_GetContainer(void *args);
extern NTSTATUS _d3d9_Surface9_GetDesc(void *args);
extern NTSTATUS _d3d9_Surface9_LockRect(void *args);
extern NTSTATUS _d3d9_Surface9_UnlockRect(void *args);
extern NTSTATUS _d3d9_Surface9_GetDC(void *args);
extern NTSTATUS _d3d9_Surface9_ReleaseDC(void *args);
extern NTSTATUS _d3d9_Texture9_QueryInterface(void *args);
extern NTSTATUS _d3d9_Texture9_AddRef(void *args);
extern NTSTATUS _d3d9_Texture9_Release(void *args);
extern NTSTATUS _d3d9_Texture9_GetDevice(void *args);
extern NTSTATUS _d3d9_Texture9_SetPrivateData(void *args);
extern NTSTATUS _d3d9_Texture9_GetPrivateData(void *args);
extern NTSTATUS _d3d9_Texture9_FreePrivateData(void *args);
extern NTSTATUS _d3d9_Texture9_SetPriority(void *args);
extern NTSTATUS _d3d9_Texture9_GetPriority(void *args);
extern NTSTATUS _d3d9_Texture9_PreLoad(void *args);
extern NTSTATUS _d3d9_Texture9_GetType(void *args);
extern NTSTATUS _d3d9_Texture9_SetLOD(void *args);
extern NTSTATUS _d3d9_Texture9_GetLOD(void *args);
extern NTSTATUS _d3d9_Texture9_GetLevelCount(void *args);
extern NTSTATUS _d3d9_Texture9_SetAutoGenFilterType(void *args);
extern NTSTATUS _d3d9_Texture9_GetAutoGenFilterType(void *args);
extern NTSTATUS _d3d9_Texture9_GenerateMipSubLevels(void *args);
extern NTSTATUS _d3d9_Texture9_GetLevelDesc(void *args);
extern NTSTATUS _d3d9_Texture9_GetSurfaceLevel(void *args);
extern NTSTATUS _d3d9_Texture9_LockRect(void *args);
extern NTSTATUS _d3d9_Texture9_UnlockRect(void *args);
extern NTSTATUS _d3d9_Texture9_AddDirtyRect(void *args);
extern NTSTATUS _d3d9_CubeTexture9_QueryInterface(void *args);
extern NTSTATUS _d3d9_CubeTexture9_AddRef(void *args);
extern NTSTATUS _d3d9_CubeTexture9_Release(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetDevice(void *args);
extern NTSTATUS _d3d9_CubeTexture9_SetPrivateData(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetPrivateData(void *args);
extern NTSTATUS _d3d9_CubeTexture9_FreePrivateData(void *args);
extern NTSTATUS _d3d9_CubeTexture9_SetPriority(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetPriority(void *args);
extern NTSTATUS _d3d9_CubeTexture9_PreLoad(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetType(void *args);
extern NTSTATUS _d3d9_CubeTexture9_SetLOD(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetLOD(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetLevelCount(void *args);
extern NTSTATUS _d3d9_CubeTexture9_SetAutoGenFilterType(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetAutoGenFilterType(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GenerateMipSubLevels(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetLevelDesc(void *args);
extern NTSTATUS _d3d9_CubeTexture9_GetCubeMapSurface(void *args);
extern NTSTATUS _d3d9_CubeTexture9_LockRect(void *args);
extern NTSTATUS _d3d9_CubeTexture9_UnlockRect(void *args);
extern NTSTATUS _d3d9_CubeTexture9_AddDirtyRect(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_QueryInterface(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_AddRef(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_Release(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetDevice(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_SetPrivateData(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetPrivateData(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_FreePrivateData(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_SetPriority(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetPriority(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_PreLoad(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetType(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_SetLOD(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetLOD(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetLevelCount(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_SetAutoGenFilterType(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetAutoGenFilterType(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GenerateMipSubLevels(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetLevelDesc(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_GetVolumeLevel(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_LockBox(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_UnlockBox(void *args);
extern NTSTATUS _d3d9_VolumeTexture9_AddDirtyBox(void *args);
extern NTSTATUS _d3d9_Volume9_QueryInterface(void *args);
extern NTSTATUS _d3d9_Volume9_AddRef(void *args);
extern NTSTATUS _d3d9_Volume9_Release(void *args);
extern NTSTATUS _d3d9_Volume9_GetDevice(void *args);
extern NTSTATUS _d3d9_Volume9_SetPrivateData(void *args);
extern NTSTATUS _d3d9_Volume9_GetPrivateData(void *args);
extern NTSTATUS _d3d9_Volume9_FreePrivateData(void *args);
extern NTSTATUS _d3d9_Volume9_GetContainer(void *args);
extern NTSTATUS _d3d9_Volume9_GetDesc(void *args);
extern NTSTATUS _d3d9_Volume9_LockBox(void *args);
extern NTSTATUS _d3d9_Volume9_UnlockBox(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_QueryInterface(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_AddRef(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_Release(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_GetDevice(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_SetPrivateData(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_GetPrivateData(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_FreePrivateData(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_SetPriority(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_GetPriority(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_PreLoad(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_GetType(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_Lock(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_Unlock(void *args);
extern NTSTATUS _d3d9_VertexBuffer9_GetDesc(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_QueryInterface(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_AddRef(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_Release(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_GetDevice(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_SetPrivateData(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_GetPrivateData(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_FreePrivateData(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_SetPriority(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_GetPriority(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_PreLoad(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_GetType(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_Lock(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_Unlock(void *args);
extern NTSTATUS _d3d9_IndexBuffer9_GetDesc(void *args);
extern NTSTATUS _d3d9_VertexDeclaration9_QueryInterface(void *args);
extern NTSTATUS _d3d9_VertexDeclaration9_AddRef(void *args);
extern NTSTATUS _d3d9_VertexDeclaration9_Release(void *args);
extern NTSTATUS _d3d9_VertexDeclaration9_GetDevice(void *args);
extern NTSTATUS _d3d9_VertexDeclaration9_GetDeclaration(void *args);
extern NTSTATUS _d3d9_VertexShader9_QueryInterface(void *args);
extern NTSTATUS _d3d9_VertexShader9_AddRef(void *args);
extern NTSTATUS _d3d9_VertexShader9_Release(void *args);
extern NTSTATUS _d3d9_VertexShader9_GetDevice(void *args);
extern NTSTATUS _d3d9_VertexShader9_GetFunction(void *args);
extern NTSTATUS _d3d9_PixelShader9_QueryInterface(void *args);
extern NTSTATUS _d3d9_PixelShader9_AddRef(void *args);
extern NTSTATUS _d3d9_PixelShader9_Release(void *args);
extern NTSTATUS _d3d9_PixelShader9_GetDevice(void *args);
extern NTSTATUS _d3d9_PixelShader9_GetFunction(void *args);
extern NTSTATUS _d3d9_StateBlock9_QueryInterface(void *args);
extern NTSTATUS _d3d9_StateBlock9_AddRef(void *args);
extern NTSTATUS _d3d9_StateBlock9_Release(void *args);
extern NTSTATUS _d3d9_StateBlock9_GetDevice(void *args);
extern NTSTATUS _d3d9_StateBlock9_Capture(void *args);
extern NTSTATUS _d3d9_StateBlock9_Apply(void *args);
extern NTSTATUS _d3d9_Query9_QueryInterface(void *args);
extern NTSTATUS _d3d9_Query9_AddRef(void *args);
extern NTSTATUS _d3d9_Query9_Release(void *args);
extern NTSTATUS _d3d9_Query9_GetDevice(void *args);
extern NTSTATUS _d3d9_Query9_GetType(void *args);
extern NTSTATUS _d3d9_Query9_GetDataSize(void *args);
extern NTSTATUS _d3d9_Query9_Issue(void *args);
extern NTSTATUS _d3d9_Query9_GetData(void *args);
extern NTSTATUS _d3d9_arena_register(void *args);
extern NTSTATUS _d3d9_window_state(void *args);
extern NTSTATUS _d3d9_create_interface(void *args);

const void *const dxmt_d3d9_unix_call_funcs[D3D9SHIM_OP_COUNT] = {
    /*   0 */ (const void *)_d3d9_init,
    /*   1 */ (const void *)_d3d9_D3D9Ex_QueryInterface,
    /*   2 */ (const void *)_d3d9_D3D9Ex_AddRef,
    /*   3 */ (const void *)_d3d9_D3D9Ex_Release,
    /*   4 */ (const void *)_d3d9_D3D9Ex_RegisterSoftwareDevice,
    /*   5 */ (const void *)_d3d9_D3D9Ex_GetAdapterCount,
    /*   6 */ (const void *)_d3d9_D3D9Ex_GetAdapterIdentifier,
    /*   7 */ (const void *)_d3d9_D3D9Ex_GetAdapterModeCount,
    /*   8 */ (const void *)_d3d9_D3D9Ex_EnumAdapterModes,
    /*   9 */ (const void *)_d3d9_D3D9Ex_GetAdapterDisplayMode,
    /*  10 */ (const void *)_d3d9_D3D9Ex_CheckDeviceType,
    /*  11 */ (const void *)_d3d9_D3D9Ex_CheckDeviceFormat,
    /*  12 */ (const void *)_d3d9_D3D9Ex_CheckDeviceMultiSampleType,
    /*  13 */ (const void *)_d3d9_D3D9Ex_CheckDepthStencilMatch,
    /*  14 */ (const void *)_d3d9_D3D9Ex_CheckDeviceFormatConversion,
    /*  15 */ (const void *)_d3d9_D3D9Ex_GetDeviceCaps,
    /*  16 */ (const void *)_d3d9_D3D9Ex_GetAdapterMonitor,
    /*  17 */ (const void *)_d3d9_D3D9Ex_CreateDevice,
    /*  18 */ (const void *)_d3d9_D3D9Ex_GetAdapterModeCountEx,
    /*  19 */ (const void *)_d3d9_D3D9Ex_EnumAdapterModesEx,
    /*  20 */ (const void *)_d3d9_D3D9Ex_GetAdapterDisplayModeEx,
    /*  21 */ (const void *)_d3d9_D3D9Ex_CreateDeviceEx,
    /*  22 */ (const void *)_d3d9_D3D9Ex_GetAdapterLUID,
    /*  23 */ (const void *)_d3d9_Device9Ex_QueryInterface,
    /*  24 */ (const void *)_d3d9_Device9Ex_AddRef,
    /*  25 */ (const void *)_d3d9_Device9Ex_Release,
    /*  26 */ (const void *)_d3d9_Device9Ex_TestCooperativeLevel,
    /*  27 */ (const void *)_d3d9_Device9Ex_GetAvailableTextureMem,
    /*  28 */ (const void *)_d3d9_Device9Ex_EvictManagedResources,
    /*  29 */ (const void *)_d3d9_Device9Ex_GetDirect3D,
    /*  30 */ (const void *)_d3d9_Device9Ex_GetDeviceCaps,
    /*  31 */ (const void *)_d3d9_Device9Ex_GetDisplayMode,
    /*  32 */ (const void *)_d3d9_Device9Ex_GetCreationParameters,
    /*  33 */ (const void *)_d3d9_Device9Ex_SetCursorProperties,
    /*  34 */ (const void *)_d3d9_Device9Ex_SetCursorPosition,
    /*  35 */ (const void *)_d3d9_Device9Ex_ShowCursor,
    /*  36 */ (const void *)_d3d9_Device9Ex_CreateAdditionalSwapChain,
    /*  37 */ (const void *)_d3d9_Device9Ex_GetSwapChain,
    /*  38 */ (const void *)_d3d9_Device9Ex_GetNumberOfSwapChains,
    /*  39 */ (const void *)_d3d9_Device9Ex_Reset,
    /*  40 */ (const void *)_d3d9_Device9Ex_Present,
    /*  41 */ (const void *)_d3d9_Device9Ex_GetBackBuffer,
    /*  42 */ (const void *)_d3d9_Device9Ex_GetRasterStatus,
    /*  43 */ (const void *)_d3d9_Device9Ex_SetDialogBoxMode,
    /*  44 */ (const void *)_d3d9_Device9Ex_SetGammaRamp,
    /*  45 */ (const void *)_d3d9_Device9Ex_GetGammaRamp,
    /*  46 */ (const void *)_d3d9_Device9Ex_CreateTexture,
    /*  47 */ (const void *)_d3d9_Device9Ex_CreateVolumeTexture,
    /*  48 */ (const void *)_d3d9_Device9Ex_CreateCubeTexture,
    /*  49 */ (const void *)_d3d9_Device9Ex_CreateVertexBuffer,
    /*  50 */ (const void *)_d3d9_Device9Ex_CreateIndexBuffer,
    /*  51 */ (const void *)_d3d9_Device9Ex_CreateRenderTarget,
    /*  52 */ (const void *)_d3d9_Device9Ex_CreateDepthStencilSurface,
    /*  53 */ (const void *)_d3d9_Device9Ex_UpdateSurface,
    /*  54 */ (const void *)_d3d9_Device9Ex_UpdateTexture,
    /*  55 */ (const void *)_d3d9_Device9Ex_GetRenderTargetData,
    /*  56 */ (const void *)_d3d9_Device9Ex_GetFrontBufferData,
    /*  57 */ (const void *)_d3d9_Device9Ex_StretchRect,
    /*  58 */ (const void *)_d3d9_Device9Ex_ColorFill,
    /*  59 */ (const void *)_d3d9_Device9Ex_CreateOffscreenPlainSurface,
    /*  60 */ (const void *)_d3d9_Device9Ex_SetRenderTarget,
    /*  61 */ (const void *)_d3d9_Device9Ex_GetRenderTarget,
    /*  62 */ (const void *)_d3d9_Device9Ex_SetDepthStencilSurface,
    /*  63 */ (const void *)_d3d9_Device9Ex_GetDepthStencilSurface,
    /*  64 */ (const void *)_d3d9_Device9Ex_BeginScene,
    /*  65 */ (const void *)_d3d9_Device9Ex_EndScene,
    /*  66 */ (const void *)_d3d9_Device9Ex_Clear,
    /*  67 */ (const void *)_d3d9_Device9Ex_SetTransform,
    /*  68 */ (const void *)_d3d9_Device9Ex_GetTransform,
    /*  69 */ (const void *)_d3d9_Device9Ex_MultiplyTransform,
    /*  70 */ (const void *)_d3d9_Device9Ex_SetViewport,
    /*  71 */ (const void *)_d3d9_Device9Ex_GetViewport,
    /*  72 */ (const void *)_d3d9_Device9Ex_SetMaterial,
    /*  73 */ (const void *)_d3d9_Device9Ex_GetMaterial,
    /*  74 */ (const void *)_d3d9_Device9Ex_SetLight,
    /*  75 */ (const void *)_d3d9_Device9Ex_GetLight,
    /*  76 */ (const void *)_d3d9_Device9Ex_LightEnable,
    /*  77 */ (const void *)_d3d9_Device9Ex_GetLightEnable,
    /*  78 */ (const void *)_d3d9_Device9Ex_SetClipPlane,
    /*  79 */ (const void *)_d3d9_Device9Ex_GetClipPlane,
    /*  80 */ (const void *)_d3d9_Device9Ex_SetRenderState,
    /*  81 */ (const void *)_d3d9_Device9Ex_GetRenderState,
    /*  82 */ (const void *)_d3d9_Device9Ex_CreateStateBlock,
    /*  83 */ (const void *)_d3d9_Device9Ex_BeginStateBlock,
    /*  84 */ (const void *)_d3d9_Device9Ex_EndStateBlock,
    /*  85 */ (const void *)_d3d9_Device9Ex_SetClipStatus,
    /*  86 */ (const void *)_d3d9_Device9Ex_GetClipStatus,
    /*  87 */ (const void *)_d3d9_Device9Ex_GetTexture,
    /*  88 */ (const void *)_d3d9_Device9Ex_SetTexture,
    /*  89 */ (const void *)_d3d9_Device9Ex_GetTextureStageState,
    /*  90 */ (const void *)_d3d9_Device9Ex_SetTextureStageState,
    /*  91 */ (const void *)_d3d9_Device9Ex_GetSamplerState,
    /*  92 */ (const void *)_d3d9_Device9Ex_SetSamplerState,
    /*  93 */ (const void *)_d3d9_Device9Ex_ValidateDevice,
    /*  94 */ (const void *)_d3d9_Device9Ex_SetPaletteEntries,
    /*  95 */ (const void *)_d3d9_Device9Ex_GetPaletteEntries,
    /*  96 */ (const void *)_d3d9_Device9Ex_SetCurrentTexturePalette,
    /*  97 */ (const void *)_d3d9_Device9Ex_GetCurrentTexturePalette,
    /*  98 */ (const void *)_d3d9_Device9Ex_SetScissorRect,
    /*  99 */ (const void *)_d3d9_Device9Ex_GetScissorRect,
    /* 100 */ (const void *)_d3d9_Device9Ex_SetSoftwareVertexProcessing,
    /* 101 */ (const void *)_d3d9_Device9Ex_GetSoftwareVertexProcessing,
    /* 102 */ (const void *)_d3d9_Device9Ex_SetNPatchMode,
    /* 103 */ (const void *)_d3d9_Device9Ex_GetNPatchMode,
    /* 104 */ (const void *)_d3d9_Device9Ex_DrawPrimitive,
    /* 105 */ (const void *)_d3d9_Device9Ex_DrawIndexedPrimitive,
    /* 106 */ (const void *)_d3d9_Device9Ex_DrawPrimitiveUP,
    /* 107 */ (const void *)_d3d9_Device9Ex_DrawIndexedPrimitiveUP,
    /* 108 */ (const void *)_d3d9_Device9Ex_ProcessVertices,
    /* 109 */ (const void *)_d3d9_Device9Ex_CreateVertexDeclaration,
    /* 110 */ (const void *)_d3d9_Device9Ex_SetVertexDeclaration,
    /* 111 */ (const void *)_d3d9_Device9Ex_GetVertexDeclaration,
    /* 112 */ (const void *)_d3d9_Device9Ex_SetFVF,
    /* 113 */ (const void *)_d3d9_Device9Ex_GetFVF,
    /* 114 */ (const void *)_d3d9_Device9Ex_CreateVertexShader,
    /* 115 */ (const void *)_d3d9_Device9Ex_SetVertexShader,
    /* 116 */ (const void *)_d3d9_Device9Ex_GetVertexShader,
    /* 117 */ (const void *)_d3d9_Device9Ex_SetVertexShaderConstantF,
    /* 118 */ (const void *)_d3d9_Device9Ex_GetVertexShaderConstantF,
    /* 119 */ (const void *)_d3d9_Device9Ex_SetVertexShaderConstantI,
    /* 120 */ (const void *)_d3d9_Device9Ex_GetVertexShaderConstantI,
    /* 121 */ (const void *)_d3d9_Device9Ex_SetVertexShaderConstantB,
    /* 122 */ (const void *)_d3d9_Device9Ex_GetVertexShaderConstantB,
    /* 123 */ (const void *)_d3d9_Device9Ex_SetStreamSource,
    /* 124 */ (const void *)_d3d9_Device9Ex_GetStreamSource,
    /* 125 */ (const void *)_d3d9_Device9Ex_SetStreamSourceFreq,
    /* 126 */ (const void *)_d3d9_Device9Ex_GetStreamSourceFreq,
    /* 127 */ (const void *)_d3d9_Device9Ex_SetIndices,
    /* 128 */ (const void *)_d3d9_Device9Ex_GetIndices,
    /* 129 */ (const void *)_d3d9_Device9Ex_CreatePixelShader,
    /* 130 */ (const void *)_d3d9_Device9Ex_SetPixelShader,
    /* 131 */ (const void *)_d3d9_Device9Ex_GetPixelShader,
    /* 132 */ (const void *)_d3d9_Device9Ex_SetPixelShaderConstantF,
    /* 133 */ (const void *)_d3d9_Device9Ex_GetPixelShaderConstantF,
    /* 134 */ (const void *)_d3d9_Device9Ex_SetPixelShaderConstantI,
    /* 135 */ (const void *)_d3d9_Device9Ex_GetPixelShaderConstantI,
    /* 136 */ (const void *)_d3d9_Device9Ex_SetPixelShaderConstantB,
    /* 137 */ (const void *)_d3d9_Device9Ex_GetPixelShaderConstantB,
    /* 138 */ (const void *)_d3d9_Device9Ex_DrawRectPatch,
    /* 139 */ (const void *)_d3d9_Device9Ex_DrawTriPatch,
    /* 140 */ (const void *)_d3d9_Device9Ex_DeletePatch,
    /* 141 */ (const void *)_d3d9_Device9Ex_CreateQuery,
    /* 142 */ (const void *)_d3d9_Device9Ex_SetConvolutionMonoKernel,
    /* 143 */ (const void *)_d3d9_Device9Ex_ComposeRects,
    /* 144 */ (const void *)_d3d9_Device9Ex_PresentEx,
    /* 145 */ (const void *)_d3d9_Device9Ex_GetGPUThreadPriority,
    /* 146 */ (const void *)_d3d9_Device9Ex_SetGPUThreadPriority,
    /* 147 */ (const void *)_d3d9_Device9Ex_WaitForVBlank,
    /* 148 */ (const void *)_d3d9_Device9Ex_CheckResourceResidency,
    /* 149 */ (const void *)_d3d9_Device9Ex_SetMaximumFrameLatency,
    /* 150 */ (const void *)_d3d9_Device9Ex_GetMaximumFrameLatency,
    /* 151 */ (const void *)_d3d9_Device9Ex_CheckDeviceState,
    /* 152 */ (const void *)_d3d9_Device9Ex_CreateRenderTargetEx,
    /* 153 */ (const void *)_d3d9_Device9Ex_CreateOffscreenPlainSurfaceEx,
    /* 154 */ (const void *)_d3d9_Device9Ex_CreateDepthStencilSurfaceEx,
    /* 155 */ (const void *)_d3d9_Device9Ex_ResetEx,
    /* 156 */ (const void *)_d3d9_Device9Ex_GetDisplayModeEx,
    /* 157 */ (const void *)_d3d9_SwapChain9Ex_QueryInterface,
    /* 158 */ (const void *)_d3d9_SwapChain9Ex_AddRef,
    /* 159 */ (const void *)_d3d9_SwapChain9Ex_Release,
    /* 160 */ (const void *)_d3d9_SwapChain9Ex_Present,
    /* 161 */ (const void *)_d3d9_SwapChain9Ex_GetFrontBufferData,
    /* 162 */ (const void *)_d3d9_SwapChain9Ex_GetBackBuffer,
    /* 163 */ (const void *)_d3d9_SwapChain9Ex_GetRasterStatus,
    /* 164 */ (const void *)_d3d9_SwapChain9Ex_GetDisplayMode,
    /* 165 */ (const void *)_d3d9_SwapChain9Ex_GetDevice,
    /* 166 */ (const void *)_d3d9_SwapChain9Ex_GetPresentParameters,
    /* 167 */ (const void *)_d3d9_SwapChain9Ex_GetLastPresentCount,
    /* 168 */ (const void *)_d3d9_SwapChain9Ex_GetPresentStats,
    /* 169 */ (const void *)_d3d9_SwapChain9Ex_GetDisplayModeEx,
    /* 170 */ (const void *)_d3d9_Surface9_QueryInterface,
    /* 171 */ (const void *)_d3d9_Surface9_AddRef,
    /* 172 */ (const void *)_d3d9_Surface9_Release,
    /* 173 */ (const void *)_d3d9_Surface9_GetDevice,
    /* 174 */ (const void *)_d3d9_Surface9_SetPrivateData,
    /* 175 */ (const void *)_d3d9_Surface9_GetPrivateData,
    /* 176 */ (const void *)_d3d9_Surface9_FreePrivateData,
    /* 177 */ (const void *)_d3d9_Surface9_SetPriority,
    /* 178 */ (const void *)_d3d9_Surface9_GetPriority,
    /* 179 */ (const void *)_d3d9_Surface9_PreLoad,
    /* 180 */ (const void *)_d3d9_Surface9_GetType,
    /* 181 */ (const void *)_d3d9_Surface9_GetContainer,
    /* 182 */ (const void *)_d3d9_Surface9_GetDesc,
    /* 183 */ (const void *)_d3d9_Surface9_LockRect,
    /* 184 */ (const void *)_d3d9_Surface9_UnlockRect,
    /* 185 */ (const void *)_d3d9_Surface9_GetDC,
    /* 186 */ (const void *)_d3d9_Surface9_ReleaseDC,
    /* 187 */ (const void *)_d3d9_Texture9_QueryInterface,
    /* 188 */ (const void *)_d3d9_Texture9_AddRef,
    /* 189 */ (const void *)_d3d9_Texture9_Release,
    /* 190 */ (const void *)_d3d9_Texture9_GetDevice,
    /* 191 */ (const void *)_d3d9_Texture9_SetPrivateData,
    /* 192 */ (const void *)_d3d9_Texture9_GetPrivateData,
    /* 193 */ (const void *)_d3d9_Texture9_FreePrivateData,
    /* 194 */ (const void *)_d3d9_Texture9_SetPriority,
    /* 195 */ (const void *)_d3d9_Texture9_GetPriority,
    /* 196 */ (const void *)_d3d9_Texture9_PreLoad,
    /* 197 */ (const void *)_d3d9_Texture9_GetType,
    /* 198 */ (const void *)_d3d9_Texture9_SetLOD,
    /* 199 */ (const void *)_d3d9_Texture9_GetLOD,
    /* 200 */ (const void *)_d3d9_Texture9_GetLevelCount,
    /* 201 */ (const void *)_d3d9_Texture9_SetAutoGenFilterType,
    /* 202 */ (const void *)_d3d9_Texture9_GetAutoGenFilterType,
    /* 203 */ (const void *)_d3d9_Texture9_GenerateMipSubLevels,
    /* 204 */ (const void *)_d3d9_Texture9_GetLevelDesc,
    /* 205 */ (const void *)_d3d9_Texture9_GetSurfaceLevel,
    /* 206 */ (const void *)_d3d9_Texture9_LockRect,
    /* 207 */ (const void *)_d3d9_Texture9_UnlockRect,
    /* 208 */ (const void *)_d3d9_Texture9_AddDirtyRect,
    /* 209 */ (const void *)_d3d9_CubeTexture9_QueryInterface,
    /* 210 */ (const void *)_d3d9_CubeTexture9_AddRef,
    /* 211 */ (const void *)_d3d9_CubeTexture9_Release,
    /* 212 */ (const void *)_d3d9_CubeTexture9_GetDevice,
    /* 213 */ (const void *)_d3d9_CubeTexture9_SetPrivateData,
    /* 214 */ (const void *)_d3d9_CubeTexture9_GetPrivateData,
    /* 215 */ (const void *)_d3d9_CubeTexture9_FreePrivateData,
    /* 216 */ (const void *)_d3d9_CubeTexture9_SetPriority,
    /* 217 */ (const void *)_d3d9_CubeTexture9_GetPriority,
    /* 218 */ (const void *)_d3d9_CubeTexture9_PreLoad,
    /* 219 */ (const void *)_d3d9_CubeTexture9_GetType,
    /* 220 */ (const void *)_d3d9_CubeTexture9_SetLOD,
    /* 221 */ (const void *)_d3d9_CubeTexture9_GetLOD,
    /* 222 */ (const void *)_d3d9_CubeTexture9_GetLevelCount,
    /* 223 */ (const void *)_d3d9_CubeTexture9_SetAutoGenFilterType,
    /* 224 */ (const void *)_d3d9_CubeTexture9_GetAutoGenFilterType,
    /* 225 */ (const void *)_d3d9_CubeTexture9_GenerateMipSubLevels,
    /* 226 */ (const void *)_d3d9_CubeTexture9_GetLevelDesc,
    /* 227 */ (const void *)_d3d9_CubeTexture9_GetCubeMapSurface,
    /* 228 */ (const void *)_d3d9_CubeTexture9_LockRect,
    /* 229 */ (const void *)_d3d9_CubeTexture9_UnlockRect,
    /* 230 */ (const void *)_d3d9_CubeTexture9_AddDirtyRect,
    /* 231 */ (const void *)_d3d9_VolumeTexture9_QueryInterface,
    /* 232 */ (const void *)_d3d9_VolumeTexture9_AddRef,
    /* 233 */ (const void *)_d3d9_VolumeTexture9_Release,
    /* 234 */ (const void *)_d3d9_VolumeTexture9_GetDevice,
    /* 235 */ (const void *)_d3d9_VolumeTexture9_SetPrivateData,
    /* 236 */ (const void *)_d3d9_VolumeTexture9_GetPrivateData,
    /* 237 */ (const void *)_d3d9_VolumeTexture9_FreePrivateData,
    /* 238 */ (const void *)_d3d9_VolumeTexture9_SetPriority,
    /* 239 */ (const void *)_d3d9_VolumeTexture9_GetPriority,
    /* 240 */ (const void *)_d3d9_VolumeTexture9_PreLoad,
    /* 241 */ (const void *)_d3d9_VolumeTexture9_GetType,
    /* 242 */ (const void *)_d3d9_VolumeTexture9_SetLOD,
    /* 243 */ (const void *)_d3d9_VolumeTexture9_GetLOD,
    /* 244 */ (const void *)_d3d9_VolumeTexture9_GetLevelCount,
    /* 245 */ (const void *)_d3d9_VolumeTexture9_SetAutoGenFilterType,
    /* 246 */ (const void *)_d3d9_VolumeTexture9_GetAutoGenFilterType,
    /* 247 */ (const void *)_d3d9_VolumeTexture9_GenerateMipSubLevels,
    /* 248 */ (const void *)_d3d9_VolumeTexture9_GetLevelDesc,
    /* 249 */ (const void *)_d3d9_VolumeTexture9_GetVolumeLevel,
    /* 250 */ (const void *)_d3d9_VolumeTexture9_LockBox,
    /* 251 */ (const void *)_d3d9_VolumeTexture9_UnlockBox,
    /* 252 */ (const void *)_d3d9_VolumeTexture9_AddDirtyBox,
    /* 253 */ (const void *)_d3d9_Volume9_QueryInterface,
    /* 254 */ (const void *)_d3d9_Volume9_AddRef,
    /* 255 */ (const void *)_d3d9_Volume9_Release,
    /* 256 */ (const void *)_d3d9_Volume9_GetDevice,
    /* 257 */ (const void *)_d3d9_Volume9_SetPrivateData,
    /* 258 */ (const void *)_d3d9_Volume9_GetPrivateData,
    /* 259 */ (const void *)_d3d9_Volume9_FreePrivateData,
    /* 260 */ (const void *)_d3d9_Volume9_GetContainer,
    /* 261 */ (const void *)_d3d9_Volume9_GetDesc,
    /* 262 */ (const void *)_d3d9_Volume9_LockBox,
    /* 263 */ (const void *)_d3d9_Volume9_UnlockBox,
    /* 264 */ (const void *)_d3d9_VertexBuffer9_QueryInterface,
    /* 265 */ (const void *)_d3d9_VertexBuffer9_AddRef,
    /* 266 */ (const void *)_d3d9_VertexBuffer9_Release,
    /* 267 */ (const void *)_d3d9_VertexBuffer9_GetDevice,
    /* 268 */ (const void *)_d3d9_VertexBuffer9_SetPrivateData,
    /* 269 */ (const void *)_d3d9_VertexBuffer9_GetPrivateData,
    /* 270 */ (const void *)_d3d9_VertexBuffer9_FreePrivateData,
    /* 271 */ (const void *)_d3d9_VertexBuffer9_SetPriority,
    /* 272 */ (const void *)_d3d9_VertexBuffer9_GetPriority,
    /* 273 */ (const void *)_d3d9_VertexBuffer9_PreLoad,
    /* 274 */ (const void *)_d3d9_VertexBuffer9_GetType,
    /* 275 */ (const void *)_d3d9_VertexBuffer9_Lock,
    /* 276 */ (const void *)_d3d9_VertexBuffer9_Unlock,
    /* 277 */ (const void *)_d3d9_VertexBuffer9_GetDesc,
    /* 278 */ (const void *)_d3d9_IndexBuffer9_QueryInterface,
    /* 279 */ (const void *)_d3d9_IndexBuffer9_AddRef,
    /* 280 */ (const void *)_d3d9_IndexBuffer9_Release,
    /* 281 */ (const void *)_d3d9_IndexBuffer9_GetDevice,
    /* 282 */ (const void *)_d3d9_IndexBuffer9_SetPrivateData,
    /* 283 */ (const void *)_d3d9_IndexBuffer9_GetPrivateData,
    /* 284 */ (const void *)_d3d9_IndexBuffer9_FreePrivateData,
    /* 285 */ (const void *)_d3d9_IndexBuffer9_SetPriority,
    /* 286 */ (const void *)_d3d9_IndexBuffer9_GetPriority,
    /* 287 */ (const void *)_d3d9_IndexBuffer9_PreLoad,
    /* 288 */ (const void *)_d3d9_IndexBuffer9_GetType,
    /* 289 */ (const void *)_d3d9_IndexBuffer9_Lock,
    /* 290 */ (const void *)_d3d9_IndexBuffer9_Unlock,
    /* 291 */ (const void *)_d3d9_IndexBuffer9_GetDesc,
    /* 292 */ (const void *)_d3d9_VertexDeclaration9_QueryInterface,
    /* 293 */ (const void *)_d3d9_VertexDeclaration9_AddRef,
    /* 294 */ (const void *)_d3d9_VertexDeclaration9_Release,
    /* 295 */ (const void *)_d3d9_VertexDeclaration9_GetDevice,
    /* 296 */ (const void *)_d3d9_VertexDeclaration9_GetDeclaration,
    /* 297 */ (const void *)_d3d9_VertexShader9_QueryInterface,
    /* 298 */ (const void *)_d3d9_VertexShader9_AddRef,
    /* 299 */ (const void *)_d3d9_VertexShader9_Release,
    /* 300 */ (const void *)_d3d9_VertexShader9_GetDevice,
    /* 301 */ (const void *)_d3d9_VertexShader9_GetFunction,
    /* 302 */ (const void *)_d3d9_PixelShader9_QueryInterface,
    /* 303 */ (const void *)_d3d9_PixelShader9_AddRef,
    /* 304 */ (const void *)_d3d9_PixelShader9_Release,
    /* 305 */ (const void *)_d3d9_PixelShader9_GetDevice,
    /* 306 */ (const void *)_d3d9_PixelShader9_GetFunction,
    /* 307 */ (const void *)_d3d9_StateBlock9_QueryInterface,
    /* 308 */ (const void *)_d3d9_StateBlock9_AddRef,
    /* 309 */ (const void *)_d3d9_StateBlock9_Release,
    /* 310 */ (const void *)_d3d9_StateBlock9_GetDevice,
    /* 311 */ (const void *)_d3d9_StateBlock9_Capture,
    /* 312 */ (const void *)_d3d9_StateBlock9_Apply,
    /* 313 */ (const void *)_d3d9_Query9_QueryInterface,
    /* 314 */ (const void *)_d3d9_Query9_AddRef,
    /* 315 */ (const void *)_d3d9_Query9_Release,
    /* 316 */ (const void *)_d3d9_Query9_GetDevice,
    /* 317 */ (const void *)_d3d9_Query9_GetType,
    /* 318 */ (const void *)_d3d9_Query9_GetDataSize,
    /* 319 */ (const void *)_d3d9_Query9_Issue,
    /* 320 */ (const void *)_d3d9_Query9_GetData,
    /* 321 */ (const void *)_d3d9_arena_register,
    /* 322 */ (const void *)_d3d9_window_state,
    /* 323 */ (const void *)_d3d9_create_interface,
};

const void *const dxmt_d3d9_unix_call_wow64_funcs[D3D9SHIM_OP_COUNT] = {
    /*   0 */ (const void *)_d3d9_init,
    /*   1 */ (const void *)_d3d9_D3D9Ex_QueryInterface,
    /*   2 */ (const void *)_d3d9_D3D9Ex_AddRef,
    /*   3 */ (const void *)_d3d9_D3D9Ex_Release,
    /*   4 */ (const void *)_d3d9_D3D9Ex_RegisterSoftwareDevice,
    /*   5 */ (const void *)_d3d9_D3D9Ex_GetAdapterCount,
    /*   6 */ (const void *)_d3d9_D3D9Ex_GetAdapterIdentifier,
    /*   7 */ (const void *)_d3d9_D3D9Ex_GetAdapterModeCount,
    /*   8 */ (const void *)_d3d9_D3D9Ex_EnumAdapterModes,
    /*   9 */ (const void *)_d3d9_D3D9Ex_GetAdapterDisplayMode,
    /*  10 */ (const void *)_d3d9_D3D9Ex_CheckDeviceType,
    /*  11 */ (const void *)_d3d9_D3D9Ex_CheckDeviceFormat,
    /*  12 */ (const void *)_d3d9_D3D9Ex_CheckDeviceMultiSampleType,
    /*  13 */ (const void *)_d3d9_D3D9Ex_CheckDepthStencilMatch,
    /*  14 */ (const void *)_d3d9_D3D9Ex_CheckDeviceFormatConversion,
    /*  15 */ (const void *)_d3d9_D3D9Ex_GetDeviceCaps,
    /*  16 */ (const void *)_d3d9_D3D9Ex_GetAdapterMonitor,
    /*  17 */ (const void *)_d3d9_D3D9Ex_CreateDevice,
    /*  18 */ (const void *)_d3d9_D3D9Ex_GetAdapterModeCountEx,
    /*  19 */ (const void *)_d3d9_D3D9Ex_EnumAdapterModesEx,
    /*  20 */ (const void *)_d3d9_D3D9Ex_GetAdapterDisplayModeEx,
    /*  21 */ (const void *)_d3d9_D3D9Ex_CreateDeviceEx,
    /*  22 */ (const void *)_d3d9_D3D9Ex_GetAdapterLUID,
    /*  23 */ (const void *)_d3d9_Device9Ex_QueryInterface,
    /*  24 */ (const void *)_d3d9_Device9Ex_AddRef,
    /*  25 */ (const void *)_d3d9_Device9Ex_Release,
    /*  26 */ (const void *)_d3d9_Device9Ex_TestCooperativeLevel,
    /*  27 */ (const void *)_d3d9_Device9Ex_GetAvailableTextureMem,
    /*  28 */ (const void *)_d3d9_Device9Ex_EvictManagedResources,
    /*  29 */ (const void *)_d3d9_Device9Ex_GetDirect3D,
    /*  30 */ (const void *)_d3d9_Device9Ex_GetDeviceCaps,
    /*  31 */ (const void *)_d3d9_Device9Ex_GetDisplayMode,
    /*  32 */ (const void *)_d3d9_Device9Ex_GetCreationParameters,
    /*  33 */ (const void *)_d3d9_Device9Ex_SetCursorProperties,
    /*  34 */ (const void *)_d3d9_Device9Ex_SetCursorPosition,
    /*  35 */ (const void *)_d3d9_Device9Ex_ShowCursor,
    /*  36 */ (const void *)_d3d9_Device9Ex_CreateAdditionalSwapChain,
    /*  37 */ (const void *)_d3d9_Device9Ex_GetSwapChain,
    /*  38 */ (const void *)_d3d9_Device9Ex_GetNumberOfSwapChains,
    /*  39 */ (const void *)_d3d9_Device9Ex_Reset,
    /*  40 */ (const void *)_d3d9_Device9Ex_Present,
    /*  41 */ (const void *)_d3d9_Device9Ex_GetBackBuffer,
    /*  42 */ (const void *)_d3d9_Device9Ex_GetRasterStatus,
    /*  43 */ (const void *)_d3d9_Device9Ex_SetDialogBoxMode,
    /*  44 */ (const void *)_d3d9_Device9Ex_SetGammaRamp,
    /*  45 */ (const void *)_d3d9_Device9Ex_GetGammaRamp,
    /*  46 */ (const void *)_d3d9_Device9Ex_CreateTexture,
    /*  47 */ (const void *)_d3d9_Device9Ex_CreateVolumeTexture,
    /*  48 */ (const void *)_d3d9_Device9Ex_CreateCubeTexture,
    /*  49 */ (const void *)_d3d9_Device9Ex_CreateVertexBuffer,
    /*  50 */ (const void *)_d3d9_Device9Ex_CreateIndexBuffer,
    /*  51 */ (const void *)_d3d9_Device9Ex_CreateRenderTarget,
    /*  52 */ (const void *)_d3d9_Device9Ex_CreateDepthStencilSurface,
    /*  53 */ (const void *)_d3d9_Device9Ex_UpdateSurface,
    /*  54 */ (const void *)_d3d9_Device9Ex_UpdateTexture,
    /*  55 */ (const void *)_d3d9_Device9Ex_GetRenderTargetData,
    /*  56 */ (const void *)_d3d9_Device9Ex_GetFrontBufferData,
    /*  57 */ (const void *)_d3d9_Device9Ex_StretchRect,
    /*  58 */ (const void *)_d3d9_Device9Ex_ColorFill,
    /*  59 */ (const void *)_d3d9_Device9Ex_CreateOffscreenPlainSurface,
    /*  60 */ (const void *)_d3d9_Device9Ex_SetRenderTarget,
    /*  61 */ (const void *)_d3d9_Device9Ex_GetRenderTarget,
    /*  62 */ (const void *)_d3d9_Device9Ex_SetDepthStencilSurface,
    /*  63 */ (const void *)_d3d9_Device9Ex_GetDepthStencilSurface,
    /*  64 */ (const void *)_d3d9_Device9Ex_BeginScene,
    /*  65 */ (const void *)_d3d9_Device9Ex_EndScene,
    /*  66 */ (const void *)_d3d9_Device9Ex_Clear,
    /*  67 */ (const void *)_d3d9_Device9Ex_SetTransform,
    /*  68 */ (const void *)_d3d9_Device9Ex_GetTransform,
    /*  69 */ (const void *)_d3d9_Device9Ex_MultiplyTransform,
    /*  70 */ (const void *)_d3d9_Device9Ex_SetViewport,
    /*  71 */ (const void *)_d3d9_Device9Ex_GetViewport,
    /*  72 */ (const void *)_d3d9_Device9Ex_SetMaterial,
    /*  73 */ (const void *)_d3d9_Device9Ex_GetMaterial,
    /*  74 */ (const void *)_d3d9_Device9Ex_SetLight,
    /*  75 */ (const void *)_d3d9_Device9Ex_GetLight,
    /*  76 */ (const void *)_d3d9_Device9Ex_LightEnable,
    /*  77 */ (const void *)_d3d9_Device9Ex_GetLightEnable,
    /*  78 */ (const void *)_d3d9_Device9Ex_SetClipPlane,
    /*  79 */ (const void *)_d3d9_Device9Ex_GetClipPlane,
    /*  80 */ (const void *)_d3d9_Device9Ex_SetRenderState,
    /*  81 */ (const void *)_d3d9_Device9Ex_GetRenderState,
    /*  82 */ (const void *)_d3d9_Device9Ex_CreateStateBlock,
    /*  83 */ (const void *)_d3d9_Device9Ex_BeginStateBlock,
    /*  84 */ (const void *)_d3d9_Device9Ex_EndStateBlock,
    /*  85 */ (const void *)_d3d9_Device9Ex_SetClipStatus,
    /*  86 */ (const void *)_d3d9_Device9Ex_GetClipStatus,
    /*  87 */ (const void *)_d3d9_Device9Ex_GetTexture,
    /*  88 */ (const void *)_d3d9_Device9Ex_SetTexture,
    /*  89 */ (const void *)_d3d9_Device9Ex_GetTextureStageState,
    /*  90 */ (const void *)_d3d9_Device9Ex_SetTextureStageState,
    /*  91 */ (const void *)_d3d9_Device9Ex_GetSamplerState,
    /*  92 */ (const void *)_d3d9_Device9Ex_SetSamplerState,
    /*  93 */ (const void *)_d3d9_Device9Ex_ValidateDevice,
    /*  94 */ (const void *)_d3d9_Device9Ex_SetPaletteEntries,
    /*  95 */ (const void *)_d3d9_Device9Ex_GetPaletteEntries,
    /*  96 */ (const void *)_d3d9_Device9Ex_SetCurrentTexturePalette,
    /*  97 */ (const void *)_d3d9_Device9Ex_GetCurrentTexturePalette,
    /*  98 */ (const void *)_d3d9_Device9Ex_SetScissorRect,
    /*  99 */ (const void *)_d3d9_Device9Ex_GetScissorRect,
    /* 100 */ (const void *)_d3d9_Device9Ex_SetSoftwareVertexProcessing,
    /* 101 */ (const void *)_d3d9_Device9Ex_GetSoftwareVertexProcessing,
    /* 102 */ (const void *)_d3d9_Device9Ex_SetNPatchMode,
    /* 103 */ (const void *)_d3d9_Device9Ex_GetNPatchMode,
    /* 104 */ (const void *)_d3d9_Device9Ex_DrawPrimitive,
    /* 105 */ (const void *)_d3d9_Device9Ex_DrawIndexedPrimitive,
    /* 106 */ (const void *)_d3d9_Device9Ex_DrawPrimitiveUP,
    /* 107 */ (const void *)_d3d9_Device9Ex_DrawIndexedPrimitiveUP,
    /* 108 */ (const void *)_d3d9_Device9Ex_ProcessVertices,
    /* 109 */ (const void *)_d3d9_Device9Ex_CreateVertexDeclaration,
    /* 110 */ (const void *)_d3d9_Device9Ex_SetVertexDeclaration,
    /* 111 */ (const void *)_d3d9_Device9Ex_GetVertexDeclaration,
    /* 112 */ (const void *)_d3d9_Device9Ex_SetFVF,
    /* 113 */ (const void *)_d3d9_Device9Ex_GetFVF,
    /* 114 */ (const void *)_d3d9_Device9Ex_CreateVertexShader,
    /* 115 */ (const void *)_d3d9_Device9Ex_SetVertexShader,
    /* 116 */ (const void *)_d3d9_Device9Ex_GetVertexShader,
    /* 117 */ (const void *)_d3d9_Device9Ex_SetVertexShaderConstantF,
    /* 118 */ (const void *)_d3d9_Device9Ex_GetVertexShaderConstantF,
    /* 119 */ (const void *)_d3d9_Device9Ex_SetVertexShaderConstantI,
    /* 120 */ (const void *)_d3d9_Device9Ex_GetVertexShaderConstantI,
    /* 121 */ (const void *)_d3d9_Device9Ex_SetVertexShaderConstantB,
    /* 122 */ (const void *)_d3d9_Device9Ex_GetVertexShaderConstantB,
    /* 123 */ (const void *)_d3d9_Device9Ex_SetStreamSource,
    /* 124 */ (const void *)_d3d9_Device9Ex_GetStreamSource,
    /* 125 */ (const void *)_d3d9_Device9Ex_SetStreamSourceFreq,
    /* 126 */ (const void *)_d3d9_Device9Ex_GetStreamSourceFreq,
    /* 127 */ (const void *)_d3d9_Device9Ex_SetIndices,
    /* 128 */ (const void *)_d3d9_Device9Ex_GetIndices,
    /* 129 */ (const void *)_d3d9_Device9Ex_CreatePixelShader,
    /* 130 */ (const void *)_d3d9_Device9Ex_SetPixelShader,
    /* 131 */ (const void *)_d3d9_Device9Ex_GetPixelShader,
    /* 132 */ (const void *)_d3d9_Device9Ex_SetPixelShaderConstantF,
    /* 133 */ (const void *)_d3d9_Device9Ex_GetPixelShaderConstantF,
    /* 134 */ (const void *)_d3d9_Device9Ex_SetPixelShaderConstantI,
    /* 135 */ (const void *)_d3d9_Device9Ex_GetPixelShaderConstantI,
    /* 136 */ (const void *)_d3d9_Device9Ex_SetPixelShaderConstantB,
    /* 137 */ (const void *)_d3d9_Device9Ex_GetPixelShaderConstantB,
    /* 138 */ (const void *)_d3d9_Device9Ex_DrawRectPatch,
    /* 139 */ (const void *)_d3d9_Device9Ex_DrawTriPatch,
    /* 140 */ (const void *)_d3d9_Device9Ex_DeletePatch,
    /* 141 */ (const void *)_d3d9_Device9Ex_CreateQuery,
    /* 142 */ (const void *)_d3d9_Device9Ex_SetConvolutionMonoKernel,
    /* 143 */ (const void *)_d3d9_Device9Ex_ComposeRects,
    /* 144 */ (const void *)_d3d9_Device9Ex_PresentEx,
    /* 145 */ (const void *)_d3d9_Device9Ex_GetGPUThreadPriority,
    /* 146 */ (const void *)_d3d9_Device9Ex_SetGPUThreadPriority,
    /* 147 */ (const void *)_d3d9_Device9Ex_WaitForVBlank,
    /* 148 */ (const void *)_d3d9_Device9Ex_CheckResourceResidency,
    /* 149 */ (const void *)_d3d9_Device9Ex_SetMaximumFrameLatency,
    /* 150 */ (const void *)_d3d9_Device9Ex_GetMaximumFrameLatency,
    /* 151 */ (const void *)_d3d9_Device9Ex_CheckDeviceState,
    /* 152 */ (const void *)_d3d9_Device9Ex_CreateRenderTargetEx,
    /* 153 */ (const void *)_d3d9_Device9Ex_CreateOffscreenPlainSurfaceEx,
    /* 154 */ (const void *)_d3d9_Device9Ex_CreateDepthStencilSurfaceEx,
    /* 155 */ (const void *)_d3d9_Device9Ex_ResetEx,
    /* 156 */ (const void *)_d3d9_Device9Ex_GetDisplayModeEx,
    /* 157 */ (const void *)_d3d9_SwapChain9Ex_QueryInterface,
    /* 158 */ (const void *)_d3d9_SwapChain9Ex_AddRef,
    /* 159 */ (const void *)_d3d9_SwapChain9Ex_Release,
    /* 160 */ (const void *)_d3d9_SwapChain9Ex_Present,
    /* 161 */ (const void *)_d3d9_SwapChain9Ex_GetFrontBufferData,
    /* 162 */ (const void *)_d3d9_SwapChain9Ex_GetBackBuffer,
    /* 163 */ (const void *)_d3d9_SwapChain9Ex_GetRasterStatus,
    /* 164 */ (const void *)_d3d9_SwapChain9Ex_GetDisplayMode,
    /* 165 */ (const void *)_d3d9_SwapChain9Ex_GetDevice,
    /* 166 */ (const void *)_d3d9_SwapChain9Ex_GetPresentParameters,
    /* 167 */ (const void *)_d3d9_SwapChain9Ex_GetLastPresentCount,
    /* 168 */ (const void *)_d3d9_SwapChain9Ex_GetPresentStats,
    /* 169 */ (const void *)_d3d9_SwapChain9Ex_GetDisplayModeEx,
    /* 170 */ (const void *)_d3d9_Surface9_QueryInterface,
    /* 171 */ (const void *)_d3d9_Surface9_AddRef,
    /* 172 */ (const void *)_d3d9_Surface9_Release,
    /* 173 */ (const void *)_d3d9_Surface9_GetDevice,
    /* 174 */ (const void *)_d3d9_Surface9_SetPrivateData,
    /* 175 */ (const void *)_d3d9_Surface9_GetPrivateData,
    /* 176 */ (const void *)_d3d9_Surface9_FreePrivateData,
    /* 177 */ (const void *)_d3d9_Surface9_SetPriority,
    /* 178 */ (const void *)_d3d9_Surface9_GetPriority,
    /* 179 */ (const void *)_d3d9_Surface9_PreLoad,
    /* 180 */ (const void *)_d3d9_Surface9_GetType,
    /* 181 */ (const void *)_d3d9_Surface9_GetContainer,
    /* 182 */ (const void *)_d3d9_Surface9_GetDesc,
    /* 183 */ (const void *)_d3d9_Surface9_LockRect,
    /* 184 */ (const void *)_d3d9_Surface9_UnlockRect,
    /* 185 */ (const void *)_d3d9_Surface9_GetDC,
    /* 186 */ (const void *)_d3d9_Surface9_ReleaseDC,
    /* 187 */ (const void *)_d3d9_Texture9_QueryInterface,
    /* 188 */ (const void *)_d3d9_Texture9_AddRef,
    /* 189 */ (const void *)_d3d9_Texture9_Release,
    /* 190 */ (const void *)_d3d9_Texture9_GetDevice,
    /* 191 */ (const void *)_d3d9_Texture9_SetPrivateData,
    /* 192 */ (const void *)_d3d9_Texture9_GetPrivateData,
    /* 193 */ (const void *)_d3d9_Texture9_FreePrivateData,
    /* 194 */ (const void *)_d3d9_Texture9_SetPriority,
    /* 195 */ (const void *)_d3d9_Texture9_GetPriority,
    /* 196 */ (const void *)_d3d9_Texture9_PreLoad,
    /* 197 */ (const void *)_d3d9_Texture9_GetType,
    /* 198 */ (const void *)_d3d9_Texture9_SetLOD,
    /* 199 */ (const void *)_d3d9_Texture9_GetLOD,
    /* 200 */ (const void *)_d3d9_Texture9_GetLevelCount,
    /* 201 */ (const void *)_d3d9_Texture9_SetAutoGenFilterType,
    /* 202 */ (const void *)_d3d9_Texture9_GetAutoGenFilterType,
    /* 203 */ (const void *)_d3d9_Texture9_GenerateMipSubLevels,
    /* 204 */ (const void *)_d3d9_Texture9_GetLevelDesc,
    /* 205 */ (const void *)_d3d9_Texture9_GetSurfaceLevel,
    /* 206 */ (const void *)_d3d9_Texture9_LockRect,
    /* 207 */ (const void *)_d3d9_Texture9_UnlockRect,
    /* 208 */ (const void *)_d3d9_Texture9_AddDirtyRect,
    /* 209 */ (const void *)_d3d9_CubeTexture9_QueryInterface,
    /* 210 */ (const void *)_d3d9_CubeTexture9_AddRef,
    /* 211 */ (const void *)_d3d9_CubeTexture9_Release,
    /* 212 */ (const void *)_d3d9_CubeTexture9_GetDevice,
    /* 213 */ (const void *)_d3d9_CubeTexture9_SetPrivateData,
    /* 214 */ (const void *)_d3d9_CubeTexture9_GetPrivateData,
    /* 215 */ (const void *)_d3d9_CubeTexture9_FreePrivateData,
    /* 216 */ (const void *)_d3d9_CubeTexture9_SetPriority,
    /* 217 */ (const void *)_d3d9_CubeTexture9_GetPriority,
    /* 218 */ (const void *)_d3d9_CubeTexture9_PreLoad,
    /* 219 */ (const void *)_d3d9_CubeTexture9_GetType,
    /* 220 */ (const void *)_d3d9_CubeTexture9_SetLOD,
    /* 221 */ (const void *)_d3d9_CubeTexture9_GetLOD,
    /* 222 */ (const void *)_d3d9_CubeTexture9_GetLevelCount,
    /* 223 */ (const void *)_d3d9_CubeTexture9_SetAutoGenFilterType,
    /* 224 */ (const void *)_d3d9_CubeTexture9_GetAutoGenFilterType,
    /* 225 */ (const void *)_d3d9_CubeTexture9_GenerateMipSubLevels,
    /* 226 */ (const void *)_d3d9_CubeTexture9_GetLevelDesc,
    /* 227 */ (const void *)_d3d9_CubeTexture9_GetCubeMapSurface,
    /* 228 */ (const void *)_d3d9_CubeTexture9_LockRect,
    /* 229 */ (const void *)_d3d9_CubeTexture9_UnlockRect,
    /* 230 */ (const void *)_d3d9_CubeTexture9_AddDirtyRect,
    /* 231 */ (const void *)_d3d9_VolumeTexture9_QueryInterface,
    /* 232 */ (const void *)_d3d9_VolumeTexture9_AddRef,
    /* 233 */ (const void *)_d3d9_VolumeTexture9_Release,
    /* 234 */ (const void *)_d3d9_VolumeTexture9_GetDevice,
    /* 235 */ (const void *)_d3d9_VolumeTexture9_SetPrivateData,
    /* 236 */ (const void *)_d3d9_VolumeTexture9_GetPrivateData,
    /* 237 */ (const void *)_d3d9_VolumeTexture9_FreePrivateData,
    /* 238 */ (const void *)_d3d9_VolumeTexture9_SetPriority,
    /* 239 */ (const void *)_d3d9_VolumeTexture9_GetPriority,
    /* 240 */ (const void *)_d3d9_VolumeTexture9_PreLoad,
    /* 241 */ (const void *)_d3d9_VolumeTexture9_GetType,
    /* 242 */ (const void *)_d3d9_VolumeTexture9_SetLOD,
    /* 243 */ (const void *)_d3d9_VolumeTexture9_GetLOD,
    /* 244 */ (const void *)_d3d9_VolumeTexture9_GetLevelCount,
    /* 245 */ (const void *)_d3d9_VolumeTexture9_SetAutoGenFilterType,
    /* 246 */ (const void *)_d3d9_VolumeTexture9_GetAutoGenFilterType,
    /* 247 */ (const void *)_d3d9_VolumeTexture9_GenerateMipSubLevels,
    /* 248 */ (const void *)_d3d9_VolumeTexture9_GetLevelDesc,
    /* 249 */ (const void *)_d3d9_VolumeTexture9_GetVolumeLevel,
    /* 250 */ (const void *)_d3d9_VolumeTexture9_LockBox,
    /* 251 */ (const void *)_d3d9_VolumeTexture9_UnlockBox,
    /* 252 */ (const void *)_d3d9_VolumeTexture9_AddDirtyBox,
    /* 253 */ (const void *)_d3d9_Volume9_QueryInterface,
    /* 254 */ (const void *)_d3d9_Volume9_AddRef,
    /* 255 */ (const void *)_d3d9_Volume9_Release,
    /* 256 */ (const void *)_d3d9_Volume9_GetDevice,
    /* 257 */ (const void *)_d3d9_Volume9_SetPrivateData,
    /* 258 */ (const void *)_d3d9_Volume9_GetPrivateData,
    /* 259 */ (const void *)_d3d9_Volume9_FreePrivateData,
    /* 260 */ (const void *)_d3d9_Volume9_GetContainer,
    /* 261 */ (const void *)_d3d9_Volume9_GetDesc,
    /* 262 */ (const void *)_d3d9_Volume9_LockBox,
    /* 263 */ (const void *)_d3d9_Volume9_UnlockBox,
    /* 264 */ (const void *)_d3d9_VertexBuffer9_QueryInterface,
    /* 265 */ (const void *)_d3d9_VertexBuffer9_AddRef,
    /* 266 */ (const void *)_d3d9_VertexBuffer9_Release,
    /* 267 */ (const void *)_d3d9_VertexBuffer9_GetDevice,
    /* 268 */ (const void *)_d3d9_VertexBuffer9_SetPrivateData,
    /* 269 */ (const void *)_d3d9_VertexBuffer9_GetPrivateData,
    /* 270 */ (const void *)_d3d9_VertexBuffer9_FreePrivateData,
    /* 271 */ (const void *)_d3d9_VertexBuffer9_SetPriority,
    /* 272 */ (const void *)_d3d9_VertexBuffer9_GetPriority,
    /* 273 */ (const void *)_d3d9_VertexBuffer9_PreLoad,
    /* 274 */ (const void *)_d3d9_VertexBuffer9_GetType,
    /* 275 */ (const void *)_d3d9_VertexBuffer9_Lock,
    /* 276 */ (const void *)_d3d9_VertexBuffer9_Unlock,
    /* 277 */ (const void *)_d3d9_VertexBuffer9_GetDesc,
    /* 278 */ (const void *)_d3d9_IndexBuffer9_QueryInterface,
    /* 279 */ (const void *)_d3d9_IndexBuffer9_AddRef,
    /* 280 */ (const void *)_d3d9_IndexBuffer9_Release,
    /* 281 */ (const void *)_d3d9_IndexBuffer9_GetDevice,
    /* 282 */ (const void *)_d3d9_IndexBuffer9_SetPrivateData,
    /* 283 */ (const void *)_d3d9_IndexBuffer9_GetPrivateData,
    /* 284 */ (const void *)_d3d9_IndexBuffer9_FreePrivateData,
    /* 285 */ (const void *)_d3d9_IndexBuffer9_SetPriority,
    /* 286 */ (const void *)_d3d9_IndexBuffer9_GetPriority,
    /* 287 */ (const void *)_d3d9_IndexBuffer9_PreLoad,
    /* 288 */ (const void *)_d3d9_IndexBuffer9_GetType,
    /* 289 */ (const void *)_d3d9_IndexBuffer9_Lock,
    /* 290 */ (const void *)_d3d9_IndexBuffer9_Unlock,
    /* 291 */ (const void *)_d3d9_IndexBuffer9_GetDesc,
    /* 292 */ (const void *)_d3d9_VertexDeclaration9_QueryInterface,
    /* 293 */ (const void *)_d3d9_VertexDeclaration9_AddRef,
    /* 294 */ (const void *)_d3d9_VertexDeclaration9_Release,
    /* 295 */ (const void *)_d3d9_VertexDeclaration9_GetDevice,
    /* 296 */ (const void *)_d3d9_VertexDeclaration9_GetDeclaration,
    /* 297 */ (const void *)_d3d9_VertexShader9_QueryInterface,
    /* 298 */ (const void *)_d3d9_VertexShader9_AddRef,
    /* 299 */ (const void *)_d3d9_VertexShader9_Release,
    /* 300 */ (const void *)_d3d9_VertexShader9_GetDevice,
    /* 301 */ (const void *)_d3d9_VertexShader9_GetFunction,
    /* 302 */ (const void *)_d3d9_PixelShader9_QueryInterface,
    /* 303 */ (const void *)_d3d9_PixelShader9_AddRef,
    /* 304 */ (const void *)_d3d9_PixelShader9_Release,
    /* 305 */ (const void *)_d3d9_PixelShader9_GetDevice,
    /* 306 */ (const void *)_d3d9_PixelShader9_GetFunction,
    /* 307 */ (const void *)_d3d9_StateBlock9_QueryInterface,
    /* 308 */ (const void *)_d3d9_StateBlock9_AddRef,
    /* 309 */ (const void *)_d3d9_StateBlock9_Release,
    /* 310 */ (const void *)_d3d9_StateBlock9_GetDevice,
    /* 311 */ (const void *)_d3d9_StateBlock9_Capture,
    /* 312 */ (const void *)_d3d9_StateBlock9_Apply,
    /* 313 */ (const void *)_d3d9_Query9_QueryInterface,
    /* 314 */ (const void *)_d3d9_Query9_AddRef,
    /* 315 */ (const void *)_d3d9_Query9_Release,
    /* 316 */ (const void *)_d3d9_Query9_GetDevice,
    /* 317 */ (const void *)_d3d9_Query9_GetType,
    /* 318 */ (const void *)_d3d9_Query9_GetDataSize,
    /* 319 */ (const void *)_d3d9_Query9_Issue,
    /* 320 */ (const void *)_d3d9_Query9_GetData,
    /* 321 */ (const void *)_d3d9_arena_register,
    /* 322 */ (const void *)_d3d9_window_state,
    /* 323 */ (const void *)_d3d9_create_interface,
};

_Static_assert(sizeof(dxmt_d3d9_unix_call_funcs)
               == sizeof(dxmt_d3d9_unix_call_wow64_funcs),
               "the two d3d9 unix tables must be the same length");
_Static_assert(sizeof(dxmt_d3d9_unix_call_funcs) / sizeof(const void *)
               == D3D9SHIM_OP_COUNT,
               "d3d9 unix table length must equal the opcode count");
