#!/usr/bin/env python3
"""Generate the API-census name table FROM the unix dispatch table.

The census indexes by the same integer the PE side passes to UNIX_CALL, which
is a position in __wine_unix_call_funcs[]. Maintaining a second hand-numbered
list of names would drift the moment anyone inserts an entry, and a drifted
census silently attributes calls to the wrong function -- worse than no census.
"""
import re, sys, os

src = os.path.join(os.path.dirname(__file__), 'unix', 'winemetal_unix.c')
text = open(src).read()
m = re.search(r'const void \*__wine_unix_call_funcs\[\] = \{(.*?)\n\};', text, re.S)
if not m:
    sys.exit("dispatch table not found in %s" % src)
# EVERY slot, in order, whatever its shape. Matching only `&_Name` silently
# dropped 12 thunk_SM50* entries and a NULL at slots 74+, which does not shorten
# the table -- it SHIFTS every name after that point onto the wrong slot. A
# census that misnames what it counts is worse than no census.
raw = re.findall(r'^\s*(&?[A-Za-z0-9_]+|NULL)\s*,', m.group(1), re.M)
names = []
for e in raw:
    if e == 'NULL':
        names.append('<null slot>')
    else:
        names.append(e.lstrip('&').lstrip('_'))

out = os.path.join(os.path.dirname(__file__), 'wmt_api_names.h')
with open(out, 'w') as f:
    f.write("/* GENERATED by gen_api_names.py from the unix dispatch table.\n"
            " * Regenerate whenever __wine_unix_call_funcs[] changes. */\n"
            "#ifndef WMT_API_NAMES_H\n#define WMT_API_NAMES_H\n\n")
    f.write("#define WMT_API_COUNT %d\n\n" % len(names))
    f.write("static const char *const wmt_api_names[WMT_API_COUNT] = {\n")
    for n in names:
        f.write('    "%s",\n' % n)
    f.write("};\n\n#endif\n")
print("wrote %s with %d entries" % (os.path.relpath(out), len(names)))
