/*
 * d3d9shim_objects_gen.h -- the shim object model and hooks
 *
 * GENERATED by research/dxmt/src/d3d9shim/gen_d3d9_thunks.py from
 * research/dxmt/src/d3d9shim/d3d9_api.py.  REGENERATE, DO NOT EDIT.
 *
 * The slot number IS the ABI -- a hand edit that inserts or drops one line
 * silently sends every later call to the wrong function.  d3d9_api.py is the
 * only place any of this may be changed.
 *
 * Copyright 2026 Will Faust
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef __MADEIRA_D3D9SHIM_OBJECTS_GEN_H
#define __MADEIRA_D3D9SHIM_OBJECTS_GEN_H

#include "d3d9shim_ops.h"

/* Objects and vtables live in GUEST memory by construction: the image is
 * mapped inside the window and HeapAlloc goes through the window chokepoint
 * (WOW64_DESIGN.md 8.2(b)).  `native` is a HANDLE (index + generation into a
 * native table), never a host pointer -- invariant 4 -- so a stale reference
 * is a validated failure instead of a wild host dereference.
 *
 * Refcounting is entirely guest-side; exactly one native release happens, at
 * zero.  Only state a `local` body reads or a `defer` predicate names is
 * mirrored here; everything else belongs to the native side. */

/* Phase 1 (8.5) is synchronous-everything; phase 2 (8.6) turns the ring on.
 * The generated deferred bodies carry both arms. */
#ifndef D3D9SHIM_PHASE
#define D3D9SHIM_PHASE 1
#endif

enum d3d9shim_kind {
    D3D9SHIM_KIND_D3D9                 = 0,
    D3D9SHIM_KIND_DEVICE               = 1,
    D3D9SHIM_KIND_SWAPCHAIN            = 2,
    D3D9SHIM_KIND_SURFACE              = 3,
    D3D9SHIM_KIND_TEXTURE              = 4,
    D3D9SHIM_KIND_CUBETEXTURE          = 5,
    D3D9SHIM_KIND_VOLUMETEXTURE        = 6,
    D3D9SHIM_KIND_VOLUME               = 7,
    D3D9SHIM_KIND_VERTEXBUFFER         = 8,
    D3D9SHIM_KIND_INDEXBUFFER          = 9,
    D3D9SHIM_KIND_VERTEXDECL           = 10,
    D3D9SHIM_KIND_VERTEXSHADER         = 11,
    D3D9SHIM_KIND_PIXELSHADER          = 12,
    D3D9SHIM_KIND_STATEBLOCK           = 13,
    D3D9SHIM_KIND_QUERY                = 14,
    D3D9SHIM_KIND_COUNT,
    D3D9SHIM_KIND_ANY = 0xffffffffu   /* resolve from the handle */
};

#ifndef D3D9SHIM_MAX_BACK_BUFFERS
#define D3D9SHIM_MAX_BACK_BUFFERS                  8
#endif
#ifndef D3D9SHIM_MAX_SWAPCHAINS
#define D3D9SHIM_MAX_SWAPCHAINS                    8
#endif
#ifndef D3D9SHIM_MAX_TEXTURE_SLOTS
#define D3D9SHIM_MAX_TEXTURE_SLOTS                 20
#endif
#ifndef D3D9_MAX_PS_CONST_B
#define D3D9_MAX_PS_CONST_B                        16
#endif
#ifndef D3D9_MAX_PS_CONST_F
#define D3D9_MAX_PS_CONST_F                        224
#endif
#ifndef D3D9_MAX_PS_CONST_I
#define D3D9_MAX_PS_CONST_I                        16
#endif
#ifndef D3D9_MAX_TRANSFORMS
#define D3D9_MAX_TRANSFORMS                        266
#endif
#ifndef D3D9_MAX_VERTEX_STREAMS
#define D3D9_MAX_VERTEX_STREAMS                    16
#endif
#ifndef D3D9_MAX_VS_CONST_B
#define D3D9_MAX_VS_CONST_B                        16
#endif
#ifndef D3D9_MAX_VS_CONST_I
#define D3D9_MAX_VS_CONST_I                        16
#endif
#ifndef D3D_MAX_SIMULTANEOUS_RENDERTARGETS
#define D3D_MAX_SIMULTANEOUS_RENDERTARGETS         4
#endif

struct d3d9shim_object {
    const void *                 vtbl;              /* guest vtable -- MUST be first; apps cache and patch it */
    int32_t                      refcount;          /* public refcount; entirely guest-side */
    int32_t                      priv_refcount;     /* D3D9 private references (a container's children) */
    uint32_t                     kind;              /* enum d3d9shim_kind */
    uint32_t                     type_value;        /* D3DRESOURCETYPE / D3DQUERYTYPE, for local GetType() */
    uint64_t                     native;            /* native handle (index + generation); 0 = none */
    struct d3d9shim_object *     parent;            /* owning device, or the interface */
};

/* IDirect3D9Ex */
struct d3d9shim_d3d9 {
    struct d3d9shim_object hdr;
};

/* IDirect3DDevice9Ex */
struct d3d9shim_device {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     d3d9;                                         /* GetDirect3D */
    struct d3d9shim_object *     swapchains[D3D9SHIM_MAX_SWAPCHAINS];          /* GetSwapChain */
    uint32_t                     swapchain_count;                              /* GetNumberOfSwapChains cross-check */
    struct d3d9shim_object *     render_targets[D3D_MAX_SIMULTANEOUS_RENDERTARGETS];/* GetRenderTarget */
    struct d3d9shim_object *     depth_stencil;                                /* GetDepthStencilSurface */
    struct d3d9shim_object *     textures[D3D9SHIM_MAX_TEXTURE_SLOTS];         /* GetTexture */
    struct d3d9shim_object *     vertex_declaration;                           /* GetVertexDeclaration, Draw* predicate */
    struct d3d9shim_object *     vertex_shader;                                /* GetVertexShader */
    struct d3d9shim_object *     pixel_shader;                                 /* GetPixelShader */
    struct d3d9shim_object *     stream_buffers[D3D9_MAX_VERTEX_STREAMS];      /* GetStreamSource */
    uint32_t                     stream_offsets[D3D9_MAX_VERTEX_STREAMS];      /* GetStreamSource */
    uint32_t                     stream_strides[D3D9_MAX_VERTEX_STREAMS];      /* GetStreamSource */
    struct d3d9shim_object *     index_buffer;                                 /* GetIndices, DrawIndexed* predicate */
    uint32_t                     vs_const_f_count;                             /* 256 on a HW-VP device, 8192 on SW/MIXED (d3d9_device.cpp:11310) */
    int                          in_scene;                                     /* Begin/EndScene predicate */
    int                          can_software_vp;                              /* created with SOFTWARE or MIXED */
    int                          can_hardware_vp;                              /* created without SOFTWARE */
    int                          multithreaded;                                /* D3DCREATE_MULTITHREADED -- the shim owns the lock */
    uint32_t                     behavior_flags;                               /* the CreateDevice flags, verbatim */
};

/* IDirect3DSwapChain9Ex */
struct d3d9shim_swapchain {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    struct d3d9shim_object *     back_buffers[D3D9SHIM_MAX_BACK_BUFFERS];      /* GetBackBuffer */
    uint32_t                     back_buffer_count;                            /* GetBackBuffer bound */
};

/* IDirect3DSurface9 */
struct d3d9shim_surface {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    struct d3d9shim_object *     container;                                    /* GetContainer */
    uint32_t                     usage;                                        /* SetRenderTarget / SetDepthStencilSurface predicates */
    uint32_t                     priority;                                     /* SetPriority returns the PREVIOUS value */
};

/* IDirect3DTexture9 */
struct d3d9shim_texture {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    struct d3d9shim_object **    sublevels;                                    /* GetSurfaceLevel */
    uint32_t                     level_count;                                  /* GetSurfaceLevel bound */
    uint32_t                     usage;                                        
    uint32_t                     priority;                                     /* SetPriority returns the PREVIOUS value */
    uint32_t                     lod;                                          /* SetLOD returns the PREVIOUS value */
};

/* IDirect3DCubeTexture9 */
struct d3d9shim_cubetexture {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    struct d3d9shim_object **    sublevels;                                    /* GetCubeMapSurface, 6 * level_count */
    uint32_t                     level_count;                                  
    uint32_t                     usage;                                        
    uint32_t                     priority;                                     
    uint32_t                     lod;                                          
};

/* IDirect3DVolumeTexture9 */
struct d3d9shim_volumetexture {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    struct d3d9shim_object **    sublevels;                                    /* GetVolumeLevel */
    uint32_t                     level_count;                                  
    uint32_t                     usage;                                        
    uint32_t                     priority;                                     
    uint32_t                     lod;                                          
};

/* IDirect3DVolume9 */
struct d3d9shim_volume {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    struct d3d9shim_object *     container;                                    /* GetContainer */
};

/* IDirect3DVertexBuffer9 */
struct d3d9shim_vertexbuffer {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    uint32_t                     usage;                                        
    uint32_t                     priority;                                     
};

/* IDirect3DIndexBuffer9 */
struct d3d9shim_indexbuffer {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
    uint32_t                     usage;                                        
    uint32_t                     priority;                                     
};

/* IDirect3DVertexDeclaration9 */
struct d3d9shim_vertexdecl {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
};

/* IDirect3DVertexShader9 */
struct d3d9shim_vertexshader {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
};

/* IDirect3DPixelShader9 */
struct d3d9shim_pixelshader {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
};

/* IDirect3DStateBlock9 */
struct d3d9shim_stateblock {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
};

/* IDirect3DQuery9 */
struct d3d9shim_query {
    struct d3d9shim_object hdr;
    struct d3d9shim_object *     device;                                       /* GetDevice */
};

/* ------------------------------------------------------------------------
 * The hook contract.  Everything below is implemented by the HAND-WRITTEN
 * shim files (d3d9shim_object.c, d3d9shim_arena.c, d3d9shim_lock.c,
 * d3d9shim_window.c, d3d9shim_fpu.c, d3d9shim_main.c); nothing below is
 * generated, and the generated thunks call nothing else.
 * ------------------------------------------------------------------------ */

/* transport ------------------------------------------------------------- */
/* 0 on success; any non-zero value is a transport failure and the thunk
 * turns it into E_FAIL without touching the block's out-parameters. */
extern uint32_t d3d9shim_native_call(unsigned int slot, void *block,
                                     unsigned int size);
/* Append one record to the device's ring.  Returns 0 if it did not fit (the
 * caller then flushes and calls synchronously) and non-zero on success. */
extern int d3d9shim_ring_append(struct d3d9shim_device *dev, unsigned int op,
                                const void *block, unsigned int size);
/* Replay everything queued.  Called before every sync op, Present, Lock,
 * GetData, device teardown and the EndScene watchdog (8.6). */
extern HRESULT d3d9shim_flush(struct d3d9shim_device *dev);
/* Update the shim's shadow of whatever this deferred op changes, so the
 * `local` getters keep answering correctly while the record is still queued.
 * One hook rather than 75: it switches on the opcode. */
extern void d3d9shim_shadow_apply(struct d3d9shim_device *dev, unsigned int op,
                                  const void *block);

/* objects --------------------------------------------------------------- */
extern struct d3d9shim_object *d3d9shim_obj_from_native(unsigned int kind,
                                                        uint64_t handle);
extern uint64_t d3d9shim_obj_native(void *iface);
extern ULONG d3d9shim_obj_addref(struct d3d9shim_object *obj);
/* Decrements; at zero it appends the object's D3D9OP_*_Release record (that
 * is what "every final Release is deferred" means) and frees the wrapper. */
extern ULONG d3d9shim_obj_release(struct d3d9shim_object *obj);
extern HRESULT d3d9shim_obj_query_interface(struct d3d9shim_object *obj,
                                            REFIID riid, void **out);
extern struct d3d9shim_device *d3d9shim_device_of(struct d3d9shim_object *obj);
extern int d3d9shim_same_device(struct d3d9shim_object *self,
                                struct d3d9shim_object *other);
extern int d3d9shim_has_usage(struct d3d9shim_object *obj, uint32_t usage);
/* d3d9_matrix.hpp transform_index(): the compaction SetTransform's
 * D3DTRANSFORMSTATETYPE goes through.  >= D3D9_MAX_TRANSFORMS means "no
 * such transform"; the shim needs its own copy because the predicate for a
 * deferred SetTransform has to be evaluable without a call. */
extern uint32_t d3d9_transform_index(uint32_t state);

/* guest arena (8.2(c) / 7.5): every app-dereferenceable pointer must be in
 * [B, B+4G), so the shim VirtualAllocs the chunks and the native side
 * sub-allocates out of them. */
extern void *d3d9shim_arena_alloc(size_t size, size_t align);
extern void d3d9shim_arena_free(void *p);
extern HRESULT d3d9shim_arena_grow(size_t hint);

/* the D3DCREATE_MULTITHREADED lock; recursive, keyed by thread id (8.2(d)).
 * A single-threaded device's implementation is empty. */
extern void d3d9shim_lock(struct d3d9shim_device *dev);
extern void d3d9shim_unlock(struct d3d9shim_device *dev);

/* diagnostics */
extern void d3d9shim_log_once(const char *what);

/* identity helpers: return a BORROWED reference, or NULL.  The generated
 * body does the AddRef and the store, so these must not.
 *
 * A helper named by a `resolve` slot owes one thing more: on a cache MISS it
 * makes the single synchronous crossing on that slot own opcode --
 * d3d9shim_native_call(op, &block, sizeof(block)) with block.self set to
 * the receiver -- and adopts the native handle the unix entry writes into
 * the block.  That is the ONLY way a child identity can enter the shim,
 * because a child handle is produced by nothing but the method that hands
 * the child out. */
/* container(object, riid)  -- QIs the container to riid */
/* cube_surface(cube, face, level) */
/* device_back_buffer(device, swapchain_idx, backbuffer_idx, backbuffer_type) */
/* device_depth_stencil(device)  -- resolves on a miss */
/* device_render_target(device, idx)  -- resolves on a miss */
/* device_stream_source(device, stream_idx, &offset, &stride) */
/* device_swapchain(device, swapchain_idx)  -- resolves on a miss */
/* device_texture(device, stage)  -- applies texture_stage_to_slot() */
/* swapchain_back_buffer(swapchain, backbuffer_idx, backbuffer_type) */
/* texture_sublevel(texture, level) */
extern struct d3d9shim_object *d3d9shim_device_back_buffer(struct d3d9shim_device *dev, UINT swapchain_idx, UINT backbuffer_idx, D3DBACKBUFFER_TYPE type);
extern struct d3d9shim_object *d3d9shim_device_texture(struct d3d9shim_device *dev, DWORD stage);
extern struct d3d9shim_object *d3d9shim_device_stream_source(struct d3d9shim_device *dev, UINT stream_idx, UINT *offset, UINT *stride);
extern struct d3d9shim_object *d3d9shim_device_swapchain(struct d3d9shim_device *dev, UINT swapchain_idx);
extern struct d3d9shim_object *d3d9shim_device_render_target(struct d3d9shim_device *dev, DWORD idx);
extern struct d3d9shim_object *d3d9shim_device_depth_stencil(struct d3d9shim_device *dev);
extern struct d3d9shim_object *d3d9shim_swapchain_back_buffer(struct d3d9shim_swapchain *sc, UINT backbuffer_idx, D3DBACKBUFFER_TYPE type);
extern struct d3d9shim_object *d3d9shim_texture_sublevel(struct d3d9shim_object *tex, UINT level);
extern struct d3d9shim_object *d3d9shim_cube_surface(struct d3d9shim_cubetexture *tex, D3DCUBEMAP_FACES face, UINT level);
extern struct d3d9shim_object *d3d9shim_container(struct d3d9shim_object *obj, REFIID riid);

/* shim-local bodies: user32/gdi32 work that never crosses (8.2(d)). */
extern void STDMETHODCALLTYPE d3d9shim_shim_cursor_set_position(IDirect3DDevice9Ex *iface, int x, int y, DWORD flags);
extern WINBOOL STDMETHODCALLTYPE d3d9shim_shim_cursor_show(IDirect3DDevice9Ex *iface, WINBOOL show);

/* custom bodies: the guest-side half is not mechanical -- setupFpu, the
 * focus-window hook, fullscreen styles, the cursor, GetDC's
 * D3DKMTCreateDCFromMemory, the per-HWND client-size cache (8.2(b)/(d)). */
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_D3D9Ex_CreateDevice(IDirect3D9Ex *iface, UINT adapter_idx, D3DDEVTYPE device_type, HWND focus_window, DWORD flags, D3DPRESENT_PARAMETERS * parameters, struct IDirect3DDevice9 ** device);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_D3D9Ex_CreateDeviceEx(IDirect3D9Ex *iface, UINT adapter_idx, D3DDEVTYPE device_type, HWND focus_window, DWORD flags, D3DPRESENT_PARAMETERS * parameters, D3DDISPLAYMODEEX * mode, struct IDirect3DDevice9Ex ** device);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Device9Ex_SetCursorProperties(IDirect3DDevice9Ex *iface, UINT hotspot_x, UINT hotspot_y, IDirect3DSurface9 * bitmap);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Device9Ex_Reset(IDirect3DDevice9Ex *iface, D3DPRESENT_PARAMETERS * parameters);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Device9Ex_Present(IDirect3DDevice9Ex *iface, const RECT * src_rect, const RECT * dst_rect, HWND dst_window_override, const RGNDATA * dirty_region);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Device9Ex_SetDialogBoxMode(IDirect3DDevice9Ex *iface, WINBOOL enable);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Device9Ex_PresentEx(IDirect3DDevice9Ex *iface, const RECT * src_rect, const RECT * dst_rect, HWND dst_window_override, const RGNDATA * dirty_region, DWORD flags);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Device9Ex_ResetEx(IDirect3DDevice9Ex *iface, D3DPRESENT_PARAMETERS * parameters, D3DDISPLAYMODEEX * mode);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_SwapChain9Ex_Present(IDirect3DSwapChain9Ex *iface, const RECT * src_rect, const RECT * dst_rect, HWND dst_window_override, const RGNDATA * dirty_region, DWORD flags);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Surface9_GetDC(IDirect3DSurface9 *iface, HDC* phdc);
extern HRESULT STDMETHODCALLTYPE d3d9shim_custom_Surface9_ReleaseDC(IDirect3DSurface9 *iface, HDC hdc);

/* the 15 vtables, defined in d3d9shim_thunks.c */
extern const void *const d3d9shim_vtbl_D3D9Ex[22];
extern const void *const d3d9shim_vtbl_Device9Ex[134];
extern const void *const d3d9shim_vtbl_SwapChain9Ex[13];
extern const void *const d3d9shim_vtbl_Surface9[17];
extern const void *const d3d9shim_vtbl_Texture9[22];
extern const void *const d3d9shim_vtbl_CubeTexture9[22];
extern const void *const d3d9shim_vtbl_VolumeTexture9[22];
extern const void *const d3d9shim_vtbl_Volume9[11];
extern const void *const d3d9shim_vtbl_VertexBuffer9[14];
extern const void *const d3d9shim_vtbl_IndexBuffer9[14];
extern const void *const d3d9shim_vtbl_VertexDeclaration9[5];
extern const void *const d3d9shim_vtbl_VertexShader9[5];
extern const void *const d3d9shim_vtbl_PixelShader9[5];
extern const void *const d3d9shim_vtbl_StateBlock9[6];
extern const void *const d3d9shim_vtbl_Query9[8];

#endif /* __MADEIRA_D3D9SHIM_OBJECTS_GEN_H */
