#!/usr/bin/env python3
#
# gen_d3d9_thunks.py -- emit both sides of the Madeira D3D9 shim boundary
# from d3d9_api.py.
#
# Copyright 2026 Will Faust
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the D3D9 shim thunks, parameter blocks and unix tables.

Outputs (WOW64_DESIGN.md 8.7):

  src/d3d9shim/d3d9shim_ops.h          parameter blocks, opcode enum, the
                                       mirror structs and every _Static_assert
                                       -- included by BOTH sides
  src/d3d9shim/d3d9shim_objects_gen.h  the shim object model and the extern
                                       hook contract the hand-written files
                                       must satisfy
  src/d3d9shim/d3d9shim_thunks.c       15 vtables, 320 bodies (i386 PE)
  src/d3d9/unix/d3d9_unix.c            324 unix entries (320 vtable slots, the
                                       init handshake, the three transport
                                       slots) + the ring replay
  src/d3d9/unix/d3d9_unix_table.c      both dispatch tables
  src/d3d9/unix/d3d9_native_hooks.h    the per-method native hook prototypes

Guard rails: the generator runs d3d9_api.validate() first and writes NOTHING
if it reports anything.  It then re-checks, on the data it is about to emit,
that opcodes are dense and unique, that both tables come out the same length,
and that every mirror's 32-bit image is exactly 4-byte packed.  Output is
deterministic: no dict iteration order, no timestamps, no paths.

Usage:  python3 gen_d3d9_thunks.py [--check] [-o <repo root>]
        --check  regenerate into memory and diff against what is on disk;
                 exit 1 if they differ (for CI / a pre-commit hook).
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import d3d9_api as api                                      # noqa: E402

BANNER = """/*
 * %s
 *
 * GENERATED by research/dxmt/src/d3d9shim/gen_d3d9_thunks.py from
 * research/dxmt/src/d3d9shim/d3d9_api.py.  REGENERATE, DO NOT EDIT.
 *
 * The slot number IS the ABI -- a hand edit that inserts or drops one line
 * silently sends every later call to the wrong function.  d3d9_api.py is the
 * only place any of this may be changed.
 *
 * Copyright 2026 Will Faust
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
"""

# --------------------------------------------------------------------------
# Small helpers over the description
# --------------------------------------------------------------------------

AMBIGUOUS_IFACES = ("IDirect3DBaseTexture9", "IDirect3DResource9", "IUnknown")


def iface_kinds():
    """Every interface name that can appear in an iface_in/iface_out tag."""
    out = {}
    for it in api.INTERFACES:
        out[it["iface"]] = it["kind"]
        if it["iface"].endswith("Ex"):
            out[it["iface"][:-2]] = it["kind"]
    for name in AMBIGUOUS_IFACES:
        out[name] = "ANY"
    return out


KINDS = iface_kinds()


def kind_enum(kind):
    return "D3D9SHIM_KIND_" + kind


def state_struct(kind):
    return "d3d9shim_" + kind.lower()


def opcodes():
    """[(name, it, m)] in canonical order; index IS the unix table slot.

    Slot 0 is the init handshake, 1..320 the vtable methods, and then the
    three TRANSPORT slots -- the things the boundary needs that are not
    vtable methods.  They come last so no generated slot number moves, which
    is how they keep the numbers (321, 322, 323) the hand-written half already
    ships against; a transport entry is (name, None, <TRANSPORT_SLOTS dict>).
    """
    out = [("D3D9OP_init", None, None)]
    for it, m in api.iter_methods():
        out.append((api.opcode_name(it, m), it, m))
    for t in api.TRANSPORT_SLOTS:
        out.append((t["op"], None, t))
    return out


OPS = opcodes()
TRANSPORT_BASE = 1 + api.EXPECTED_TOTAL_SLOTS


def is_transport(it, m):
    return it is None and m is not None


def op_symbol(it, m):
    """The _d3d9_<sym> / d3d9_call_<sym> stem for one table slot."""
    if m is None:
        return "init"
    if it is None:
        return m["name"]
    return api.symbol(it, m)


def transport_params(t):
    """The transport hook's C parameter list, from the field roles."""
    ps = []
    for ctype, name, role in t["fields"]:
        base = role.split(":", 1)[0]
        if base == "scalar":
            ps.append("%s %s" % (role.split(":", 1)[1], name))
        elif base == "hwnd32":
            ps.append("HWND " + name)
        elif base == "guest_ptr":
            ps.append("void *" + name)
        elif base == "handle_out":
            ps.append("d3d9_native_handle *" + name)
        else:
            raise SystemExit("unknown transport role %r" % role)
        del ctype
    return ", ".join(ps)


def mirror_of(shape):
    t = shape.split(":", 1)[-1]
    for s in api.MIRROR_STRUCTS:
        if s["name"] == t:
            return s
    return None


MIRROR_BY_NAME = {s["name"]: s for s in api.MIRROR_STRUCTS}
PADDING_ONLY = {p[0] for p in api.PADDING_ONLY_STRUCTS}
IDENTICAL_BY_NAME = {s[0]: s[1] for s in api.IDENTICAL_STRUCTS}
LOCKED = {"locked_rect_out": "D3DLOCKED_RECT", "locked_box_out": "D3DLOCKED_BOX"}


def arg_target(a):
    """The pointed-at type for a shaped pointer argument."""
    if a["tag"] in LOCKED:
        return LOCKED[a["tag"]]
    if a["tag"] in ("in_struct", "out_struct", "inout_struct", "out_ptr"):
        return a["shape"].split(":", 1)[1]
    if a["tag"] in ("in_array", "out_array"):
        return a["shape"].split(":")[1]
    return None


def guest_ptr_target(a):
    """`void **ppbData` -> `void *`: the type the OUT pointer points at."""
    base = a["ctype"].strip()
    assert base.endswith("**"), a["ctype"]
    return base[:-2].strip() + " *"


def is_iface_array(a):
    """An in_array whose elements are guest interface pointers."""
    return a["tag"] == "in_array" and a["shape"].split(":")[1] in KINDS


def count_expr(a):
    if a["tag"] in ("in_array", "out_array"):
        return a["shape"].split(":", 2)[2]
    if a["tag"] == "user_mem_in":
        return a["shape"].split(":", 1)[1]
    return None


def shim_params(it, m):
    """The shim thunk's C parameter list, matching the SDK vtable exactly."""
    ps = ["%s *iface" % it["iface"]]
    for a in m["args"]:
        ctype = a["ctype"]
        ps.append(("%s %s" if ctype.endswith(("*", "&")) else "%s %s")
                  % (ctype, a["name"]))
    return ", ".join(ps)


def native_ret(m):
    return "void" if m["ret"] == "void" else m["ret"]


def native_params(it, m):
    """The native hook's C parameter list: host types, handles for objects."""
    ps = ["d3d9_native_handle self"]
    for a in m["args"]:
        t, n = a["tag"], a["name"]
        if t == "iface_in":
            ps.append("d3d9_native_handle " + n)
        elif t == "iface_out":
            ps.append("d3d9_native_handle *" + n)
        elif t in ("handle", "hwnd"):
            ps.append("%s %s" % ("HWND" if t == "hwnd" else "HANDLE", n))
        elif t == "shared_handle_inout":
            ps.append("HANDLE *" + n)
        elif t == "user_mem_in":
            ps.append("const void *" + n)
        elif t in LOCKED:
            ps.append("%s *%s" % (LOCKED[t], n))
        elif t == "guest_ptr_out":
            # The mapped-memory OUT pointer.  A HOST pointer here: the unix
            # entry is what turns it back into a guest address, exactly as it
            # does for D3DLOCKED_RECT::pBits.
            ps.append("%s*%s" % (guest_ptr_target(a), n))
        elif t == "in_array" and is_iface_array(a):
            ps.append("const uint32_t *" + n)   # guest interface pointers
        elif t in ("in_struct", "in_array"):
            ps.append("const %s *%s" % (arg_target(a), n))
        elif t in ("out_struct", "inout_struct", "out_array", "out_ptr"):
            ps.append("%s *%s" % (arg_target(a), n))
        else:
            ps.append("%s %s" % (a["ctype"], n))
    return ", ".join(ps)


# --------------------------------------------------------------------------
# Predicate / count-expression translation.  The grammar d3d9_api.validate()
# enforces is small on purpose, so this is a token rewrite, not a parser.
# --------------------------------------------------------------------------

import re                                                    # noqa: E402

_CALL_REWRITE = [
    (r"\bis_null\s*\(([^()]*)\)", r"((\1) == NULL)"),
    (r"\bsame_device\s*\(([^()]*)\)",
     r"d3d9shim_same_device(&_self->hdr, (struct d3d9shim_object *)(\1))"),
    (r"\bhas_usage\s*\(([^()]*),([^()]*)\)",
     r"d3d9shim_has_usage((struct d3d9shim_object *)(\1), (\2))"),
]


def to_c(expr):
    """Python-syntax predicate / count expression -> C."""
    out = expr
    for pat, rep in _CALL_REWRITE:
        prev = None
        while prev != out:
            prev, out = out, re.sub(pat, rep, out)
    out = re.sub(r"\bself\.(\w+)", r"_self->\1", out)
    out = re.sub(r"\bUINT_MAX\b", "0xffffffffu", out)
    out = re.sub(r"\bTrue\b", "1", out)
    out = re.sub(r"\bFalse\b", "0", out)
    out = re.sub(r"\bnot\b", "!", out)
    out = re.sub(r"\band\b", "&&", out)
    out = re.sub(r"\bor\b", "||", out)
    return out


POINTER_TAGS = ("in_struct", "out_struct", "inout_struct", "in_array",
                "out_array", "out_ptr", "user_mem_in", "locked_rect_out",
                "locked_box_out", "shared_handle_inout", "guest_ptr_out")


def to_c_size(expr, m):
    """A count/size expression, evaluated in a unix entry.

    An argument that is a POINTER becomes the entry's converted host pointer
    (`_name`); a scalar becomes the parameter-block field (`_p->name`).  A
    leading `*name` with no space means "the count is read through that
    out_ptr argument" -- D3D9's query-size-then-fill idiom -- and becomes
    D3D9_DEREF32(), which the glue defines to be NULL- and window-safe so the
    read is valid even though that argument's own validation has not run yet.
    Multiplication must be written with spaces (`count * 4`), which is what
    keeps `*x` unambiguous.
    """
    ptr = {a["name"] for a in m["args"] if a["tag"] in POINTER_TAGS}

    out = re.sub(r"\*(\w+)", "\x01" + r"\1" + "\x02", expr)

    def name(mo):
        n = mo.group(1)
        return ("_" + n) if n in ptr else ("_p->" + n)

    # \b after \w* stops the engine backtracking into the middle of an
    # identifier to satisfy the "not a call" lookahead, which would turn
    # d3d9_up_vertex_bytes(...) into _p->d3d9_up_vertex_byte + "s(...)".
    out = re.sub(r"(?<![\w.\x01])([A-Za-z_]\w*)\b(?!\s*\()", name, out)
    out = re.sub("\x01(\\w+)\x02",
                 lambda mo: "D3D9_DEREF32(%s)"
                 % (("_" + mo.group(1)) if mo.group(1) in ptr
                    else ("_p->" + mo.group(1))), out)
    return out


# --------------------------------------------------------------------------
# d3d9shim_ops.h
# --------------------------------------------------------------------------

def emit_ops_h():
    o = [BANNER % "d3d9shim_ops.h -- the D3D9 shim wire format, both sides"]
    o.append("""#ifndef __MADEIRA_D3D9SHIM_OPS_H
#define __MADEIRA_D3D9SHIM_OPS_H

#include <stddef.h>
#include <stdint.h>

#include <windows.h>
#include <d3d9.h>

/* Every parameter-block field is fixed width, so ONE struct definition is
 * correct on i386 and on LP64 and there is no *_params32 mirror: the
 * winemetal WMTMemoryPointer trick (winemetal.h:132-200) applied to the whole
 * block.  Guest pointers are uint32_t, handles and native object references
 * uint64_t, and the 64-bit fields are emitted FIRST so each one lands on a
 * multiple of 8 whatever the target's alignment rule for 64-bit types is.
 *
 * The consequence, and the reason d3d9_unix_table.c can point both tables at
 * the same functions: a block can only ever be written by a 32-bit caller,
 * because a 64-bit pointer does not fit in it.  There is exactly one correct
 * reading of a block, so there is nothing for a _32 variant to do
 * differently.  _d3d9_init refuses a caller whose pointer width is not 4
 * rather than pretending otherwise (WOW64_DESIGN.md 7.4 rule 4). */
""")
    o.append("#define D3D9SHIM_API_VERSION %du" % api.API_VERSION)
    o.append("#define D3D9SHIM_API_HASH 0x%016xull" % api.api_hash())
    o.append("#define D3D9SHIM_OP_COUNT %du\n" % len(OPS))

    o.append("enum d3d9shim_op {")
    for i, (name, it, m) in enumerate(OPS):
        if is_transport(it, m) and i == TRANSPORT_BASE:
            o.append("    /* The TRANSPORT slots: not vtable methods, so no")
            o.append("     * interface in the description produces them.  They")
            o.append("     * come after the whole generated range, which is what")
            o.append("     * fixes their numbers at %d.. and leaves every"
                     % TRANSPORT_BASE)
            o.append("     * generated slot -- the slot number IS the ABI --")
            o.append("     * exactly where it was. */")
        o.append("    %-56s = %3d," % (name, i))
    o.append("    D3D9OP_COUNT_ = %d" % len(OPS))
    o.append("};\n")

    o.append("""/* _d3d9_init status codes. */
enum d3d9shim_init_status {
    D3D9SHIM_INIT_OK = 0,
    D3D9SHIM_INIT_HASH_MISMATCH = 1,
    D3D9SHIM_INIT_BAD_PTR_SIZE = 2,
    D3D9SHIM_INIT_NATIVE_FAILED = 3
};

struct d3d9_init_params {
    uint64_t api_hash;       /* IN:  the shim's D3D9SHIM_API_HASH */
    uint64_t native_hash;    /* OUT: the native side's, on a mismatch */
    uint32_t api_version;    /* IN:  D3D9SHIM_API_VERSION */
    uint32_t ptr_size;       /* IN:  sizeof(void *) in the calling module */
    uint32_t op_count;       /* IN:  D3D9SHIM_OP_COUNT */
    uint32_t status;         /* OUT: enum d3d9shim_init_status */
};
_Static_assert(sizeof(struct d3d9_init_params) == 32, "d3d9_init_params");
""")

    # ---- mirrors -------------------------------------------------------
    o.append("""/* ------------------------------------------------------------------------
 * Mirrors.  The wire form of each of these is the i386 MEMORY IMAGE of the
 * SDK struct; the unix entry expands it into a host one.  The macro follows
 * airconv_thunks.h:164-168: on a 64-bit build assert the mirror, on the
 * 32-bit build assert the mirror AND the SDK struct it is an image of.
 * ------------------------------------------------------------------------ */

#if defined(__LP64__) || defined(_WIN64)
#define D3D9SHIM_COMPATIBLE_STRUCT32(native, mirror, size) \\
    _Static_assert(sizeof(struct mirror) == (size), "incompatible struct size");
#else
#define D3D9SHIM_COMPATIBLE_STRUCT32(native, mirror, size) \\
    _Static_assert(sizeof(struct mirror) == (size), "incompatible struct size"); \\
    _Static_assert(sizeof(native) == (size), "incompatible struct size");
#endif
""")
    for s in api.MIRROR_STRUCTS:
        mirror = "d3d9_%s32" % s["name"]
        o.append("/* %s */" % s["note"].replace("*/", "* /"))
        o.append("struct %s {" % mirror)
        for ctype, name, _o32, _o64, role in s["fields"]:
            o.append("    %-10s %-30s /* %s */" % (ctype, name + ";", role))
        o.append("};")
        o.append("D3D9SHIM_COMPATIBLE_STRUCT32(%s, %s, %d)"
                 % (s["name"], mirror, s["size32"]))
        for ctype, name, off32, _off64, _role in s["fields"]:
            o.append("_Static_assert(offsetof(struct %s, %s) == %d, "
                     '"%s.%s");' % (mirror, name, off32, mirror, name))
        o.append("#if defined(__LP64__) || defined(_WIN64)")
        o.append("_Static_assert(sizeof(%s) == %d, \"%s host layout\");"
                 % (s["name"], s["size64"], s["name"]))
        o.append("#endif")
        o.append("")

    # ---- layout-identical ---------------------------------------------
    o.append("""/* ------------------------------------------------------------------------
 * Layout-identical: same size AND same field offsets under both ABIs, so the
 * unix entry points at the converted guest address in place rather than
 * copying.  If one of these ever stops matching, the assert fires on
 * whichever side changed and the in-place pointer stops being emitted.
 * ------------------------------------------------------------------------ */
""")
    for name, size in api.IDENTICAL_STRUCTS:
        o.append('_Static_assert(sizeof(%s) == %d, "%s is not layout-identical");'
                 % (name, size, name))
    o.append("")
    o.append("""/* Field offsets identical, TAIL PADDING not: a LARGE_INTEGER member gives
 * the struct 8-byte alignment on LP64 and 4 on i386.  So the fields may be
 * read and written at the same offsets, but the struct MAY NOT be pointed at
 * in place across the boundary: a host-typed write to a guest buffer runs
 * sizeof() bytes, which is past the end of the i386 image.
 * D3DADAPTER_IDENTIFIER9 lives on the stack in every title that calls
 * GetAdapterIdentifier, and the frontend opens with
 * memset(p, 0, sizeof(*p)) -- four bytes onto the caller's /GS cookie, which
 * surfaces as a 0xC0000409 fast-fail in the application's own epilogue with
 * no D3D9 frame anywhere near it.  Hence the bounce below. */""")
    for name, size32, size64, offs in api.PADDING_ONLY_STRUCTS:
        o.append("#define D3D9SHIM_SIZE32_%s %d" % (name, size32))
        o.append("#define D3D9SHIM_SIZE64_%s %d" % (name, size64))
        for fname, off in offs:
            o.append('_Static_assert(offsetof(%s, %s) == %d, "%s.%s moved");'
                     % (name, fname, off, name, fname))
        o.append("#if defined(__LP64__) || defined(_WIN64)")
        o.append('_Static_assert(sizeof(%s) == %d, "%s");' % (name, size64, name))
        o.append("#else")
        o.append('_Static_assert(sizeof(%s) == %d, "%s");' % (name, size32, name))
        o.append("#endif")
        o.append('_Static_assert(D3D9SHIM_SIZE32_%s <= D3D9SHIM_SIZE64_%s,'
                 ' "the i386 image of %s must fit in the host struct");'
                 % (name, name, name))
    o.append("")
    o.append("""/* The ONLY way a padding-only struct crosses.  Both directions copy exactly
 * D3D9SHIM_SIZE32_<T> bytes -- the i386 image -- and the assert inside the
 * macro is what makes "never touch a guest buffer with the host sizeof()" a
 * build failure instead of a review item.  The generator refuses to emit an
 * in-place pointer for one of these (generator_self_check), so these two
 * macros are the whole copy surface. */
#define D3D9_COPY32_OUT(T, guest, host_struct)                                \\
    do {                                                                      \\
        _Static_assert(D3D9SHIM_SIZE32_##T <= sizeof(T),                      \\
                       "the i386 image of " #T " must fit in the host struct");\\
        memcpy((void *)(guest), (const void *)(host_struct),                  \\
               (size_t)D3D9SHIM_SIZE32_##T);                                  \\
    } while (0)

#define D3D9_COPY32_IN(T, host_struct, guest)                                 \\
    do {                                                                      \\
        _Static_assert(D3D9SHIM_SIZE32_##T <= sizeof(T),                      \\
                       "the i386 image of " #T " must fit in the host struct");\\
        memcpy((void *)(host_struct), (const void *)(guest),                  \\
               (size_t)D3D9SHIM_SIZE32_##T);                                  \\
    } while (0)
""")

    # ---- parameter blocks ---------------------------------------------
    o.append("""/* ------------------------------------------------------------------------
 * Parameter blocks, one per vtable slot.  Also the ring record payloads for
 * the deferred ops: a ring record is `struct d3d9_ring_record` followed by
 * the block for its opcode, which is why every block size is a multiple of 8.
 * ------------------------------------------------------------------------ */

struct d3d9_ring_record {
    uint16_t op;             /* enum d3d9shim_op */
    uint16_t len;            /* sizeof(record) + sizeof(block), 8-aligned */
    uint32_t seq;            /* monotonic; asserted at replay (8.6) */
};
_Static_assert(sizeof(struct d3d9_ring_record) == 8, "d3d9_ring_record");
""")
    for it, m in api.iter_methods():
        name = api.block_struct(it, m)
        o.append("/* %s::%s -- slot %d, %s%s */"
                 % (it["iface"], m["name"], m["slot"], m["disp"],
                    ", flushes" if m["flush"] else ""))
        o.append("struct %s {" % name)
        for ctype, fname, role in api.block_fields(m):
            note = {"self": "receiving object's native handle",
                    "ret": "result"}.get(role, "")
            if role == "arg":
                a = next(x for x in m["args"] if x["name"] == fname)
                note = a["shape"]
            o.append("    %-10s %-30s /* %s */" % (ctype, fname + ";", note))
        for i in range(api.pad_words(m)):
            o.append("    uint32_t   _pad%d;" % i)
        o.append("};")
        o.append('_Static_assert(sizeof(struct %s) == %d, "%s");'
                 % (name, api.block_size(m), name))
        off = 0
        for ctype, fname, _role in api.block_fields(m):
            width = 8 if ctype == "uint64_t" else 4
            off = (off + width - 1) // width * width
            o.append('_Static_assert(offsetof(struct %s, %s) == %d, "%s.%s");'
                     % (name, fname, off, name, fname))
            off += width
        o.append("")

    # ---- transport blocks ----------------------------------------------
    o.append("""/* ------------------------------------------------------------------------
 * Transport blocks.  Same fixed-width rule as a vtable block -- uint64_t
 * fields first, then the 4-byte ones, then the result, then padding to a
 * multiple of 8 -- so one definition is right on i386 and on LP64 here too.
 *
 * These three were hand-written in d3d9shim_object.h and sat PAST the end of
 * a table sized D3D9SHIM_OP_COUNT, so neither dispatch table had an entry for
 * them and every call on one failed the bind.  d3d9_api.py now describes
 * them, which is what gets them entries; the layouts below are the ones the
 * hand-written header _Static_asserted, unchanged.
 * ------------------------------------------------------------------------ */
""")
    for name, value in api.WINDOW_STATE_FLAGS:
        o.append("#define %-30s 0x%xu" % (name, value))
    o.append("")
    o.append("""/* The distinguished status a unix entry returns when THIS call could not be
 * served because the guest arena is empty or full.  d3d9shim_native_call()
 * answers it by growing the arena and retrying the same block exactly once
 * (8.2(c): grow-and-retry, no upcall machinery).  It is emitted here rather
 * than declared once per side so the two halves cannot disagree about the
 * value; the entry only raises it on a call that already FAILED, so the retry
 * can never double work that succeeded. */
#ifndef D3D9SHIM_STATUS_ARENA_EXHAUSTED
#define D3D9SHIM_STATUS_ARENA_EXHAUSTED  0xC0000017u  /* STATUS_NO_MEMORY */
#endif
""")
    for i, t in enumerate(api.TRANSPORT_SLOTS):
        o.append("/* slot %d -- %s */" % (TRANSPORT_BASE + i,
                                          t["note"].replace("*/", "* /")))
        o.append("struct %s {" % t["block"])
        roles = {f[1]: f[2] for f in t["fields"]}
        for ctype, fname, role in api.transport_fields(t):
            note = "OUT: result" if role == "ret" else roles[fname]
            o.append("    %-10s %-30s /* %s */" % (ctype, fname + ";", note))
        for j in range(api.transport_pad_words(t)):
            o.append("    uint32_t   _pad%d;" % j)
        o.append("};")
        o.append('_Static_assert(sizeof(struct %s) == %d, "%s");'
                 % (t["block"], t["size"], t["block"]))
        off = 0
        for ctype, fname, _role in api.transport_fields(t):
            width = 8 if ctype == "uint64_t" else 4
            off = (off + width - 1) // width * width
            o.append('_Static_assert(offsetof(struct %s, %s) == %d, "%s.%s");'
                     % (t["block"], fname, off, t["block"], fname))
            off += width
        o.append("")

    o.append("#endif /* __MADEIRA_D3D9SHIM_OPS_H */")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------
# d3d9shim_objects_gen.h
# --------------------------------------------------------------------------

def emit_objects_h():
    o = [BANNER % "d3d9shim_objects_gen.h -- the shim object model and hooks"]
    o.append("""#ifndef __MADEIRA_D3D9SHIM_OBJECTS_GEN_H
#define __MADEIRA_D3D9SHIM_OBJECTS_GEN_H

#include "d3d9shim_ops.h"

/* Objects and vtables live in GUEST memory by construction: the image is
 * mapped inside the window and HeapAlloc goes through the window chokepoint
 * (WOW64_DESIGN.md 8.2(b)).  `native` is a HANDLE (index + generation into a
 * native table), never a host pointer -- invariant 4 -- so a stale reference
 * is a validated failure instead of a wild host dereference.
 *
 * Refcounting is entirely guest-side; exactly one native release happens, at
 * zero.  Only state a `local` body reads or a `defer` predicate names is
 * mirrored here; everything else belongs to the native side. */

/* Phase 1 (8.5) is synchronous-everything; phase 2 (8.6) turns the ring on.
 * The generated deferred bodies carry both arms. */
#ifndef D3D9SHIM_PHASE
#define D3D9SHIM_PHASE 1
#endif
""")
    o.append("enum d3d9shim_kind {")
    kinds = [it["kind"] for it in api.INTERFACES]
    for i, k in enumerate(kinds):
        o.append("    %-34s = %d," % (kind_enum(k), i))
    o.append("    D3D9SHIM_KIND_COUNT,")
    o.append("    D3D9SHIM_KIND_ANY = 0xffffffffu   /* resolve from the handle */")
    o.append("};\n")

    for k in sorted(api.LIMITS):
        o.append("#ifndef %s" % k)
        o.append("#define %-42s %d" % (k, api.LIMITS[k]))
        o.append("#endif")
    o.append("")

    o.append("struct d3d9shim_object {")
    for ctype, name, note in api.OBJECT_HEADER:
        o.append("    %-28s %-18s /* %s */" % (ctype, name + ";", note))
    o.append("};\n")

    for it in api.INTERFACES:
        k = it["kind"]
        o.append("/* %s */" % it["iface"])
        o.append("struct %s {" % state_struct(k))
        o.append("    struct d3d9shim_object hdr;")
        for ctype, name, note in api.OBJECT_STATE[k]:
            o.append("    %-28s %-46s%s"
                     % (ctype, name + ";", ("/* %s */" % note) if note else ""))
        o.append("};\n")

    o.append("""/* ------------------------------------------------------------------------
 * The hook contract.  Everything below is implemented by the HAND-WRITTEN
 * shim files (d3d9shim_object.c, d3d9shim_arena.c, d3d9shim_lock.c,
 * d3d9shim_window.c, d3d9shim_fpu.c, d3d9shim_main.c); nothing below is
 * generated, and the generated thunks call nothing else.
 * ------------------------------------------------------------------------ */

/* transport ------------------------------------------------------------- */
/* 0 on success; any non-zero value is a transport failure and the thunk
 * turns it into E_FAIL without touching the block's out-parameters. */
extern uint32_t d3d9shim_native_call(unsigned int slot, void *block,
                                     unsigned int size);
/* Append one record to the device's ring.  Returns 0 if it did not fit (the
 * caller then flushes and calls synchronously) and non-zero on success. */
extern int d3d9shim_ring_append(struct d3d9shim_device *dev, unsigned int op,
                                const void *block, unsigned int size);
/* Replay everything queued.  Called before every sync op, Present, Lock,
 * GetData, device teardown and the EndScene watchdog (8.6). */
extern HRESULT d3d9shim_flush(struct d3d9shim_device *dev);
/* Update the shim's shadow of whatever this deferred op changes, so the
 * `local` getters keep answering correctly while the record is still queued.
 * One hook rather than 75: it switches on the opcode. */
extern void d3d9shim_shadow_apply(struct d3d9shim_device *dev, unsigned int op,
                                  const void *block);

/* objects --------------------------------------------------------------- */
extern struct d3d9shim_object *d3d9shim_obj_from_native(unsigned int kind,
                                                        uint64_t handle);
extern uint64_t d3d9shim_obj_native(void *iface);
extern ULONG d3d9shim_obj_addref(struct d3d9shim_object *obj);
/* Decrements; at zero it appends the object's D3D9OP_*_Release record (that
 * is what "every final Release is deferred" means) and frees the wrapper. */
extern ULONG d3d9shim_obj_release(struct d3d9shim_object *obj);
extern HRESULT d3d9shim_obj_query_interface(struct d3d9shim_object *obj,
                                            REFIID riid, void **out);
extern struct d3d9shim_device *d3d9shim_device_of(struct d3d9shim_object *obj);
extern int d3d9shim_same_device(struct d3d9shim_object *self,
                                struct d3d9shim_object *other);
extern int d3d9shim_has_usage(struct d3d9shim_object *obj, uint32_t usage);
/* d3d9_matrix.hpp transform_index(): the compaction SetTransform's
 * D3DTRANSFORMSTATETYPE goes through.  >= D3D9_MAX_TRANSFORMS means "no
 * such transform"; the shim needs its own copy because the predicate for a
 * deferred SetTransform has to be evaluable without a call. */
extern uint32_t d3d9_transform_index(uint32_t state);

/* guest arena (8.2(c) / 7.5): every app-dereferenceable pointer must be in
 * [B, B+4G), so the shim VirtualAllocs the chunks and the native side
 * sub-allocates out of them. */
extern void *d3d9shim_arena_alloc(size_t size, size_t align);
extern void d3d9shim_arena_free(void *p);
extern HRESULT d3d9shim_arena_grow(size_t hint);

/* the D3DCREATE_MULTITHREADED lock; recursive, keyed by thread id (8.2(d)).
 * A single-threaded device's implementation is empty. */
extern void d3d9shim_lock(struct d3d9shim_device *dev);
extern void d3d9shim_unlock(struct d3d9shim_device *dev);

/* diagnostics */
extern void d3d9shim_log_once(const char *what);

/* identity helpers: return a BORROWED reference, or NULL.  The generated
 * body does the AddRef and the store, so these must not.
 *
 * A helper named by a `resolve` slot owes one thing more: on a cache MISS it
 * makes the single synchronous crossing on that slot own opcode --
 * d3d9shim_native_call(op, &block, sizeof(block)) with block.self set to
 * the receiver -- and adopts the native handle the unix entry writes into
 * the block.  That is the ONLY way a child identity can enter the shim,
 * because a child handle is produced by nothing but the method that hands
 * the child out. */""")
    for name, sig in sorted(api.IDENTITY_HELPERS.items()):
        o.append("/* %s%s */" % (name, sig))
    o.append("extern struct d3d9shim_object *d3d9shim_device_back_buffer("
             "struct d3d9shim_device *dev, UINT swapchain_idx, "
             "UINT backbuffer_idx, D3DBACKBUFFER_TYPE type);")
    o.append("extern struct d3d9shim_object *d3d9shim_device_texture("
             "struct d3d9shim_device *dev, DWORD stage);")
    o.append("extern struct d3d9shim_object *d3d9shim_device_stream_source("
             "struct d3d9shim_device *dev, UINT stream_idx, UINT *offset, "
             "UINT *stride);")
    o.append("extern struct d3d9shim_object *d3d9shim_device_swapchain("
             "struct d3d9shim_device *dev, UINT swapchain_idx);")
    o.append("extern struct d3d9shim_object *d3d9shim_device_render_target("
             "struct d3d9shim_device *dev, DWORD idx);")
    o.append("extern struct d3d9shim_object *d3d9shim_device_depth_stencil("
             "struct d3d9shim_device *dev);")
    o.append("extern struct d3d9shim_object *d3d9shim_swapchain_back_buffer("
             "struct d3d9shim_swapchain *sc, UINT backbuffer_idx, "
             "D3DBACKBUFFER_TYPE type);")
    o.append("extern struct d3d9shim_object *d3d9shim_texture_sublevel("
             "struct d3d9shim_object *tex, UINT level);")
    o.append("extern struct d3d9shim_object *d3d9shim_cube_surface("
             "struct d3d9shim_cubetexture *tex, D3DCUBEMAP_FACES face, "
             "UINT level);")
    o.append("extern struct d3d9shim_object *d3d9shim_container("
             "struct d3d9shim_object *obj, REFIID riid);")
    o.append("")

    # shim-local (user32/gdi32) bodies
    shim_local = [(it, m) for it, m in api.iter_methods()
                  if m["local"] and m["local"].startswith("shim:")]
    if shim_local:
        o.append("/* shim-local bodies: user32/gdi32 work that never crosses "
                 "(8.2(d)). */")
        for it, m in shim_local:
            o.append("extern %s STDMETHODCALLTYPE d3d9shim_shim_%s(%s);"
                     % (native_ret(m), m["local"].split(":", 1)[1],
                        shim_params(it, m)))
        o.append("")

    custom = [(it, m) for it, m in api.iter_methods() if m["custom"]]
    o.append("/* custom bodies: the guest-side half is not mechanical -- "
             "setupFpu, the\n * focus-window hook, fullscreen styles, the "
             "cursor, GetDC's\n * D3DKMTCreateDCFromMemory, the per-HWND "
             "client-size cache (8.2(b)/(d)). */")
    for it, m in custom:
        o.append("extern %s STDMETHODCALLTYPE d3d9shim_custom_%s(%s);"
                 % (native_ret(m), api.symbol(it, m), shim_params(it, m)))
    o.append("")

    o.append("/* the 15 vtables, defined in d3d9shim_thunks.c */")
    for it in api.INTERFACES:
        o.append("extern const void *const d3d9shim_vtbl_%s[%d];"
                 % (it["short"], len(it["methods"])))
    o.append("")
    o.append("#endif /* __MADEIRA_D3D9SHIM_OBJECTS_GEN_H */")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------
# d3d9shim_thunks.c
# --------------------------------------------------------------------------

def pack_stmt(a):
    """Shim-side: argument -> parameter-block field."""
    n, t = a["name"], a["tag"]
    if t == "iface_in":
        return "    _p.%s = d3d9shim_obj_native(%s);" % (n, n)
    if t in ("iface_out", "guest_ptr_out"):
        return None
    if t in ("handle", "hwnd"):
        return "    _p.%s = (uint64_t)(ULONG_PTR)%s;" % (n, n)
    if t == "u64":
        return "    _p.%s = (uint64_t)%s;" % (n, n)
    if t == "u32":
        if a["ctype"].strip() == "float":
            return "    _p.%s = %s;" % (n, n)
        return "    _p.%s = (uint32_t)%s;" % (n, n)
    # everything else is a guest pointer; the shim IS the guest, so this is
    # just a truncation to the block's fixed width.
    return "    _p.%s = (uint32_t)(ULONG_PTR)%s;" % (n, n)


def unpack_stmts(m):
    out = []
    for a in m["args"]:
        if a["tag"] == "guest_ptr_out":
            # The mapped-memory pointer, already a GUEST address: the unix
            # entry ran it through ios_wow_guest_ptr32(), so the shim -- which
            # IS the guest -- only has to widen it back to a pointer.  This is
            # D3DLOCKED_RECT::pBits with no struct around it.
            out.append("    *%s = (%s)(ULONG_PTR)_p.%s;"
                       % (a["name"], guest_ptr_target(a).strip(), a["name"]))
            continue
        if a["tag"] != "iface_out":
            continue
        iface = a["shape"].split(":", 1)[1]
        ctype = a["ctype"].replace("struct ", "").replace("**", "").strip()
        out.append("    if (%s)" % a["name"])
        out.append("        *%s = (%s *)(_p.%s ? d3d9shim_obj_from_native(%s, "
                   "_p.%s) : NULL);"
                   % (a["name"], ctype, a["name"], kind_enum(KINDS[iface]),
                      a["name"]))
    return out


def ret_stmt(m):
    if m["ret"] == "void":
        return "    return;"
    if m["ret"] == "HRESULT":
        return "    return (HRESULT)_p.ret;"
    if m["ret"] == "HMONITOR":
        return "    return (HMONITOR)(ULONG_PTR)_p.ret;"
    if m["ret"] == "float":
        return "    return _p.ret;"
    return "    return (%s)_p.ret;" % m["ret"]


def fail_ret(m, hr="E_FAIL"):
    if m["ret"] == "void":
        return "return;"
    if m["ret"] == "HRESULT":
        return "return %s;" % hr
    if m["ret"] == "HMONITOR":
        return "return NULL;"
    if m["ret"] == "float":
        return "return 0.0f;"
    return "return 0;"


def emit_body(it, m):
    o = []
    self_t = state_struct(it["kind"])
    o.append("    struct %s *_self = (struct %s *)iface;" % (self_t, self_t))

    if m["unimplemented"]:
        o.append('    d3d9shim_log_once("%s::%s is not implemented");'
                 % (it["iface"], m["name"]))
        for a in m["args"]:
            o.append("    (void)%s;" % a["name"])
        o.append("    (void)_self;")
        o.append("    " + fail_ret(m, "E_NOTIMPL"))
        return o

    if m["custom"]:
        args = ", ".join(["iface"] + [a["name"] for a in m["args"]])
        o.append("    (void)_self;")
        o.append("    %sd3d9shim_custom_%s(%s);"
                 % ("" if m["ret"] == "void" else "return ",
                    api.symbol(it, m), args))
        return o

    if m["disp"] in ("local", "resolve"):
        if m["disp"] == "resolve":
            o.insert(0, "    /* resolve: the identity cache answers, and on a "
                        "miss the helper")
            o.insert(1, "     * makes one crossing on this opcode and adopts "
                        "the handle the")
            o.insert(2, "     * unix entry returns -- nothing else in the "
                        "system can tell the")
            o.insert(3, "     * shim what a child native handle is. */")
        return o + emit_local(it, m)

    pack = [s for s in (pack_stmt(a) for a in m["args"]) if s]
    block = api.block_struct(it, m)

    if m["disp"] == "defer":
        o += emit_defer(it, m, pack, block)
        return o

    # ---- sync -----------------------------------------------------------
    o.append("    struct %s _p;" % block)
    o.append("    struct d3d9shim_device *_dev = d3d9shim_device_of(&_self->hdr);")
    o.append("    HRESULT _hr;")
    o.append("")
    for a in m["args"]:
        if a["tag"] == "guest_ptr_out":
            # Nothing is packed for it, so a NULL one would otherwise cross as
            # a request the native side cannot refuse on the caller behalf.
            o.append("    if (!%s)" % a["name"])
            o.append("        return D3DERR_INVALIDCALL;")
    o.append("    _hr = d3d9shim_flush(_dev);")
    o.append("    if (FAILED(_hr))")
    o.append("        %s" % fail_ret(m, "_hr"))
    o.append("    memset(&_p, 0, sizeof(_p));")
    o.append("    _p.self = _self->hdr.native;")
    o += pack
    o.append("    if (d3d9shim_native_call(%s, &_p, sizeof(_p))) {"
             % api.opcode_name(it, m))
    o.append('        d3d9shim_log_once("unix call failed: %s::%s");'
             % (it["iface"], m["name"]))
    o.append("        %s" % fail_ret(m))
    o.append("    }")
    o += unpack_stmts(m)
    o.append(ret_stmt(m))
    return o


def emit_local(it, m):
    o = []
    kind = m["local"]
    if kind == "qi":
        o.append("    return d3d9shim_obj_query_interface(&_self->hdr, %s, %s);"
                 % (m["args"][0]["name"], m["args"][1]["name"]))
        return o
    if kind == "addref":
        o.append("    return d3d9shim_obj_addref(&_self->hdr);")
        return o
    if kind == "gettype":
        o.append("    return (%s)_self->hdr.type_value;" % m["ret"])
        return o
    if kind.startswith("const:"):
        for a in m["args"]:
            o.append("    (void)%s;" % a["name"])
        o.append("    (void)_self;")
        o.append("    return %s;" % kind.split(":", 1)[1])
        return o
    if kind.startswith("shim:"):
        args = ", ".join(["iface"] + [a["name"] for a in m["args"]])
        o.append("    (void)_self;")
        o.append("    %sd3d9shim_shim_%s(%s);"
                 % ("" if m["ret"] == "void" else "return ",
                    kind.split(":", 1)[1], args))
        return o

    assert kind.startswith("identity")
    out = next(a for a in m["args"] if a["tag"] == "iface_out")
    out_ct = out["ctype"].replace("struct ", "").replace("**", "").strip()
    extra = [a for a in m["args"] if a["tag"] == "out_ptr"]

    o.append("    struct d3d9shim_object *_child;")
    o.append("    struct d3d9shim_device *_dev = d3d9shim_device_of(&_self->hdr);")
    o.append("")
    o.append("    if (!%s)" % out["name"])
    o.append("        return D3DERR_INVALIDCALL;")
    o.append("    d3d9shim_lock(_dev);")

    if kind.startswith("identity:helper:"):
        helper = kind.split(":", 2)[2]
        an = [a["name"] for a in m["args"]]
        if helper == "device_back_buffer":
            call = "d3d9shim_device_back_buffer(_self, %s, %s, %s)" % tuple(an[:3])
        elif helper == "device_texture":
            call = "d3d9shim_device_texture(_self, %s)" % an[0]
        elif helper == "device_stream_source":
            call = ("d3d9shim_device_stream_source(_self, %s, %s, %s)"
                    % (an[0], an[2], an[3]))
        elif helper == "device_swapchain":
            call = "d3d9shim_device_swapchain(_self, %s)" % an[0]
        elif helper == "device_render_target":
            call = "d3d9shim_device_render_target(_self, %s)" % an[0]
        elif helper == "device_depth_stencil":
            call = "d3d9shim_device_depth_stencil(_self)"
        elif helper == "swapchain_back_buffer":
            call = ("d3d9shim_swapchain_back_buffer(_self, %s, %s)"
                    % (an[0], an[1]))
        elif helper == "texture_sublevel":
            call = "d3d9shim_texture_sublevel(&_self->hdr, %s)" % an[0]
        elif helper == "cube_surface":
            call = "d3d9shim_cube_surface(_self, %s, %s)" % (an[0], an[1])
        elif helper == "container":
            call = "d3d9shim_container(&_self->hdr, %s)" % an[0]
        else:
            raise SystemExit("unknown identity helper %r" % helper)
        o.append("    _child = %s;" % call)
    else:
        field = kind.split(":", 1)[1]
        if "[" in field:
            arr, idx = field[:-1].split("[")
            bound = None
            for ctype, decl, _note in api.OBJECT_STATE[it["kind"]]:
                if decl.startswith(arr + "["):
                    bound = decl[len(arr) + 1:-1]
            assert bound, (it["kind"], arr)
            o.append("    _child = (%s < %s) ? _self->%s[%s] : NULL;"
                     % (idx, bound, arr, idx))
        else:
            o.append("    _child = _self->%s;" % field)

    o.append("    if (_child)")
    o.append("        d3d9shim_obj_addref(_child);")
    o.append("    d3d9shim_unlock(_dev);")
    for a in extra:
        o.append("    /* %s filled by the helper above */" % a["name"])
    o.append("    *%s = (%s *)_child;" % (out["name"], out_ct))
    if m["null_hr"] == "D3D_OK":
        o.append("    return D3D_OK;")
    else:
        o.append("    return _child ? D3D_OK : %s;" % m["null_hr"])
    return o


def emit_defer(it, m, pack, block):
    o = []
    if m["ret_const"] == "refcount":
        # Release: the hand-written releaser owns the whole dance, because
        # only it knows whether this is the LAST reference -- that is what
        # "every final Release is deferred" means (8.6).  It builds the
        # D3D9OP_*_Release record itself.
        o.append("    return d3d9shim_obj_release(&_self->hdr);")
        return o
    o.append("    struct %s _p;" % block)
    o.append("    struct d3d9shim_device *_dev = d3d9shim_device_of(&_self->hdr);")
    shadow_field = None
    if m["ret_const"] and m["ret_const"].startswith("shadow:"):
        shadow_field = m["ret_const"].split(":", 1)[1]
    o.append("    HRESULT _hr;")
    o.append("")
    o.append("#if D3D9SHIM_PHASE >= 2")
    if shadow_field:
        o.append("    %s _prev;" % m["ret"])
        o.append("")
    o.append("    d3d9shim_lock(_dev);")
    if m["pred"] and m["pred"] != "True":
        o.append("    if (!(%s)) {" % to_c(m["pred"]))
        o.append("        d3d9shim_unlock(_dev);")
        o.append("        return D3DERR_INVALIDCALL;")
        o.append("    }")
    o.append("    memset(&_p, 0, sizeof(_p));")
    o.append("    _p.self = _self->hdr.native;")
    o += pack
    if shadow_field:
        o.append("    _prev = (%s)_self->%s;" % (m["ret"], shadow_field))
    o.append("    d3d9shim_shadow_apply(_dev, %s, &_p);" % api.opcode_name(it, m))
    o.append("    if (d3d9shim_ring_append(_dev, %s, &_p, sizeof(_p))) {"
             % api.opcode_name(it, m))
    o.append("        d3d9shim_unlock(_dev);")
    if shadow_field:
        o.append("        return _prev;")
    elif m["ret"] == "void":
        o.append("        return;")
    else:
        o.append("        return %s;" % m["ret_const"])
    o.append("    }")
    o.append("    /* did not fit: flush and fall through to the direct call "
             "(8.6). */")
    o.append("    d3d9shim_unlock(_dev);")
    o.append("#endif")
    o.append("    _hr = d3d9shim_flush(_dev);")
    o.append("    if (FAILED(_hr))")
    o.append("        %s" % fail_ret(m, "_hr"))
    o.append("    memset(&_p, 0, sizeof(_p));")
    o.append("    _p.self = _self->hdr.native;")
    o += pack
    o.append("    if (d3d9shim_native_call(%s, &_p, sizeof(_p))) {"
             % api.opcode_name(it, m))
    o.append('        d3d9shim_log_once("unix call failed: %s::%s");'
             % (it["iface"], m["name"]))
    o.append("        %s" % fail_ret(m))
    o.append("    }")
    # The shadow has to be maintained on BOTH arms.  Phase 1 is
    # synchronous-everything, so if only the phase-2 arm applied it the
    # bindings the `local` and `resolve` getters read would never be updated
    # and GetTexture would answer NULL right after a successful SetTexture.
    # This is the single call site: it is the one that is always taken.
    if m["ret"] == "HRESULT":
        o.append("    if (SUCCEEDED((HRESULT)_p.ret))")
        o.append("        d3d9shim_shadow_apply(_dev, %s, &_p);"
                 % api.opcode_name(it, m))
    else:
        o.append("    d3d9shim_shadow_apply(_dev, %s, &_p);"
                 % api.opcode_name(it, m))
    o += unpack_stmts(m)
    o.append(ret_stmt(m))
    return o


def emit_thunks_c():
    o = [BANNER % "d3d9shim_thunks.c -- 15 vtables, 320 bodies (i386 PE)"]
    o.append("""#define CINTERFACE
#define COBJMACROS

#include <string.h>

#include "d3d9shim_objects_gen.h"

/* A slot with no body at all is impossible: the vtable initialisers below
 * are emitted from the same table the bodies are, and the _Static_assert on
 * each array's length is what proves it.  This stub exists so a slot marked
 * `unimplemented=True` in d3d9_api.py has somewhere to go -- and nothing is,
 * deliberately: d3d9_device.cpp's own stubs (SetConvolutionMonoKernel,
 * DrawRectPatch, DeletePatch) all say in as many words that E_NOTIMPL sends
 * hr-strict application initialisation into unrecoverable failure, so those
 * slots return a per-spec HRESULT from the native side instead. */
static HRESULT STDMETHODCALLTYPE d3d9shim_slot_unimplemented(void *iface)
{
    (void)iface;
    d3d9shim_log_once("d3d9shim: unimplemented vtable slot reached");
    return E_NOTIMPL;
}
""")
    for it, m in api.iter_methods():
        o.append("static %s STDMETHODCALLTYPE d3d9shim_%s(%s)"
                 % (native_ret(m), api.symbol(it, m), shim_params(it, m)))
        o.append("{")
        o += emit_body(it, m)
        o.append("}")
        o.append("")

    for it in api.INTERFACES:
        n = len(it["methods"])
        o.append("const void *const d3d9shim_vtbl_%s[%d] = {" % (it["short"], n))
        for m in it["methods"]:
            o.append("    /* %3d */ (const void *)d3d9shim_%s,"
                     % (m["slot"], api.symbol(it, m)))
        o.append("};")
        o.append('_Static_assert(sizeof(d3d9shim_vtbl_%s) / sizeof(const void *)'
                 ' == %d,\n               "%s vtable length");'
                 % (it["short"], n, it["iface"]))
        o.append("")
    o.append("/* silence -Wunused-function when nothing is marked "
             "unimplemented. */")
    o.append("static const void *const d3d9shim_unimplemented_ref ="
             " (const void *)d3d9shim_slot_unimplemented;")
    o.append("const void *d3d9shim_unimplemented_slot(void)"
             " { return d3d9shim_unimplemented_ref; }")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------
# d3d9_native_hooks.h
# --------------------------------------------------------------------------

def emit_native_hooks_h():
    o = [BANNER % "d3d9_native_hooks.h -- per-method native entry points"]
    o.append("""#ifndef __MADEIRA_D3D9_NATIVE_HOOKS_H
#define __MADEIRA_D3D9_NATIVE_HOOKS_H

#include "d3d9shim_ops.h"

/* A native object reference: an index + generation into the native table,
 * never a host pointer (invariant 4).  0 is "none". */
typedef uint64_t d3d9_native_handle;
""")
    o.append("""/* What a handle points at.  The glue stores the CANONICAL interface pointer
 * for the kind (the one named beside each value below) and every lookup is
 * checked against it, so a handle of the wrong kind is D3DERR_INVALIDCALL
 * rather than a wild cast.  0 is reserved: d3d9_native_handle_lookup() reads
 * it as "any kind", which only the teardown sweep ever asks for. */
enum d3d9_native_kind {
    D3D9_NATIVE_KIND_NONE = 0,""")
    for i, it in enumerate(api.INTERFACES):
        o.append("    %-38s = %2d, /* %s */"
                 % ("D3D9_NATIVE_KIND_" + it["kind"], i + 1, it["iface"]))
    o.append("""    D3D9_NATIVE_KIND_COUNT
};

#ifdef __cplusplus
extern "C" {
#endif
""")
    o.append("""
/* Called once, from _d3d9_init, after the hash handshake passes. */
extern int d3d9_native_init(void);
/* Called from ios_wow_reclaim_dead_windows() BEFORE the PROT_NONE replace
 * and before ios_jit_purge_window() -- native objects hold host pointers
 * INTO the arena (8.9-5). */
extern void d3d9_native_process_teardown(void *peb);

/* One hook per vtable slot.  The glue implements these against MTLD3D9* in
 * step 4; `local` slots are listed too, so the table below is total and a
 * later reclassification is a one-line change in d3d9_api.py. */
""")
    for it, m in api.iter_methods():
        o.append("/* %s::%s -- slot %d, %s */"
                 % (it["iface"], m["name"], m["slot"], m["disp"]))
        o.append("extern %s d3d9_native_%s(%s);"
                 % (native_ret(m), api.symbol(it, m), native_params(it, m)))
    o.append("")
    o.append("""/* The three TRANSPORT hooks.  Not vtable methods -- the guest arena
 * registration (8.2(c)), the per-HWND state cache (8.2(d)) and the creation
 * of the IDirect3D9(Ex) every other call self descends from, which is a DLL
 * export rather than a slot. */""")
    for i, t in enumerate(api.TRANSPORT_SLOTS):
        o.append("/* transport slot %d -- %s */"
                 % (TRANSPORT_BASE + i,
                    "0 on success" if t["ret_zero_ok"] else "an HRESULT"))
        o.append("extern %s %s(%s);"
                 % (t["ret"], t["hook"], transport_params(t)))
    o.append("""
#ifdef __cplusplus
}
#endif

#endif /* __MADEIRA_D3D9_NATIVE_HOOKS_H */""")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------
# d3d9_unix.c
# --------------------------------------------------------------------------

def unix_bail(it, m, n, indent):
    """The "this guest pointer is not usable" arm of a unix entry.

    A converted pointer that is not inside the window is D3DERR_INVALIDCALL,
    never a host dereference: after the frontend moves natively a bad app
    pointer faults in HOST code rather than as a guest c0000005 the app's SEH
    could catch (8.9-4), so the entry has to be the one that says no.
    """
    pad = " " * indent
    out = [pad + 'D3D9_LOG("%s::%s: %s is not a usable guest pointer");'
           % (it["iface"], m["name"], n)]
    if m["ret"] != "void":
        out.append(pad + "_p->ret = D3DERR_INVALIDCALL;")
    out.append(pad + "return;")
    return out


def unix_convert(it, m):
    """Locals + conversions for one unix entry.  Returns (decls, pre, post,
    callargs)."""
    decls, pre, post, callargs = [], [], [], ["_p->self"]
    pool = "_p->pool" if any(a["name"] == "pool" for a in m["args"]) \
        else "D3D9_NO_POOL"
    for a in m["args"]:
        n, t = a["name"], a["tag"]
        if t == "iface_in":
            callargs.append("_p->%s" % n)
        elif t == "iface_out":
            decls.append("    d3d9_native_handle _%s = 0;" % n)
            callargs.append("&_%s" % n)
            post.append("    _p->%s = _%s;" % (n, n))
        elif t == "hwnd":
            callargs.append("(HWND)(ULONG_PTR)_p->%s" % n)
        elif t == "handle":
            callargs.append("(HANDLE)(ULONG_PTR)_p->%s" % n)
        elif t == "u64":
            callargs.append("_p->%s" % n)
        elif t == "u32":
            callargs.append("(%s)_p->%s" % (a["ctype"].strip(), n))
        elif t == "shared_handle_inout":
            decls.append("    ULONG *_%s_g = D3D9_HOST_PTR(_p->%s);" % (n, n))
            decls.append("    HANDLE _%s = NULL;" % n)
            pre.append("    if (_%s_g) {" % n)
            pre.append("        if (!D3D9_IN_WINDOW(_%s_g, sizeof(ULONG))) {" % n)
            pre += unix_bail(it, m, n, 12)
            pre.append("        }")
            pre.append("        _%s = D3D9_SHARED_IN(_%s_g, %s);" % (n, n, pool))
            pre.append("    }")
            callargs.append("_%s_g ? &_%s : NULL" % (n, n))
            post.append("    if (_%s_g)" % n)
            post.append("        D3D9_SHARED_OUT(_%s_g, _%s, %s);" % (n, n, pool))
        elif t == "guest_ptr_out":
            # The mapped-memory OUT pointer.  Nothing comes IN -- the shim
            # packs nothing and refuses a NULL out-parameter itself -- so the
            # entry hands the hook a host slot and converts the answer back
            # with ios_wow_guest_ptr32(), which is the same rule as
            # D3DLOCKED_RECT::pBits and the same guarantee: the pointer the
            # native allocator hands out is always inside the guest arena.
            decls.append("    %s_%s = NULL;" % (guest_ptr_target(a), n))
            callargs.append("&_%s" % n)
            post.append("    _p->%s = %s ? D3D9_GUEST_PTR32(_%s) : 0;"
                        % (n, "SUCCEEDED(_p->ret)" if m["ret"] == "HRESULT"
                           else "1", n))
        elif t in LOCKED:
            host = LOCKED[t]
            mirror = "d3d9_%s32" % host
            decls.append("    %s _%s;" % (host, n))
            decls.append("    struct %s *_%s_g = D3D9_HOST_PTR(_p->%s);"
                         % (mirror, n, n))
            pre.append("    memset(&_%s, 0, sizeof(_%s));" % (n, n))
            pre.append("    if (_%s_g && !D3D9_IN_WINDOW(_%s_g, sizeof(*_%s_g))) {"
                       % (n, n, n))
            pre += unix_bail(it, m, n, 8)
            pre.append("    }")
            callargs.append("_%s_g ? &_%s : NULL" % (n, n))
            post.append("    if (_%s_g && SUCCEEDED(_p->ret))" % n)
            post.append("        d3d9_mirror_out_%s(_%s_g, &_%s);" % (host, n, n))
        elif t in ("in_struct", "out_struct", "inout_struct") \
                and arg_target(a) in MIRROR_BY_NAME:
            host = arg_target(a)
            mirror = "d3d9_%s32" % host
            decls.append("    %s _%s;" % (host, n))
            decls.append("    struct %s *_%s_g = D3D9_HOST_PTR(_p->%s);"
                         % (mirror, n, n))
            pre.append("    memset(&_%s, 0, sizeof(_%s));" % (n, n))
            pre.append("    if (_%s_g) {" % n)
            pre.append("        if (!D3D9_IN_WINDOW(_%s_g, sizeof(*_%s_g))) {"
                       % (n, n))
            pre += unix_bail(it, m, n, 12)
            pre.append("        }")
            if t in ("in_struct", "inout_struct"):
                pre.append("        d3d9_mirror_in_%s(&_%s, _%s_g);" % (host, n, n))
            pre.append("    }")
            callargs.append("_%s_g ? &_%s : NULL" % (n, n))
            if t in ("out_struct", "inout_struct"):
                post.append("    if (_%s_g)" % n)
                post.append("        d3d9_mirror_out_%s(_%s_g, &_%s);"
                            % (host, n, n))
        elif t in ("in_struct", "out_struct", "inout_struct") \
                and arg_target(a) in PADDING_ONLY:
            # A PADDING-ONLY struct: every field is at the same offset, but the
            # host sizeof() is LARGER than the i386 image (D3DADAPTER_IDENTIFIER9
            # is 1104 / 1100).  It used to be pointed at in place, which handed
            # the frontend a host-typed pointer into a guest buffer that is
            # short by the tail padding -- and MTLD3D9Interface::
            # GetAdapterIdentifier opens with memset(p, 0, sizeof(*p)), so the
            # application's D3DADAPTER_IDENTIFIER9 (a stack local in every title
            # that calls it) lost four bytes past its end: the /GS cookie, i.e.
            # a 0xC0000409 fast-fail in the caller's epilogue with no D3D9 call
            # anywhere near the faulting address.
            #
            # So it BOUNCES, exactly like a mirror: the frontend writes a host
            # struct and D3D9_COPY32_OUT copies back D3D9SHIM_SIZE32_<T> bytes
            # and not one more.  That macro is the only copy path for these and
            # carries its own _Static_assert (d3d9shim_ops.h).
            host = arg_target(a)
            decls.append("    %s _%s;" % (host, n))
            decls.append("    void *_%s_g = D3D9_HOST_PTR(_p->%s);" % (n, n))
            pre.append("    memset(&_%s, 0, sizeof(_%s));" % (n, n))
            pre.append("    if (_%s_g) {" % n)
            pre.append("        if (!D3D9_IN_WINDOW(_%s_g, D3D9SHIM_SIZE32_%s)) {"
                       % (n, host))
            pre += unix_bail(it, m, n, 12)
            pre.append("        }")
            if t in ("in_struct", "inout_struct"):
                pre.append("        D3D9_COPY32_IN(%s, &_%s, _%s_g);"
                           % (host, n, n))
            pre.append("    }")
            callargs.append("_%s_g ? &_%s : NULL" % (n, n))
            if t in ("out_struct", "inout_struct"):
                post.append("    if (_%s_g)" % n)
                post.append("        D3D9_COPY32_OUT(%s, _%s_g, &_%s);"
                            % (host, n, n))
        else:
            # layout-identical: point at the converted guest address in place
            target = arg_target(a) or "void"
            elem = target
            const = "const " if t in ("in_struct", "in_array", "user_mem_in") \
                else ""
            if t == "user_mem_in":
                base = "void"
            elif is_iface_array(a):
                # an array of GUEST interface pointers: 4 bytes each, and the
                # per-element handle translation is the glue's job (this is
                # the API's only 2-level IN array).
                base = elem = "uint32_t"
            else:
                base = target
            cast = "%s%s *" % (const, base)
            decls.append("    %s_%s = D3D9_HOST_PTR(_p->%s);" % (cast, n, n))
            size = count_expr(a)
            if size is None:
                # A padding-only struct is LARGER on the host than in the
                # guest, so its window check must use the i386 size or a
                # buffer at the very end of a mapping is falsely rejected --
                # and the native hook must not write past it either.
                size = ("D3D9SHIM_SIZE32_%s" % target) if target in PADDING_ONLY \
                    else "sizeof(%s)" % target
            elif t == "user_mem_in":
                size = "(size_t)(%s)" % to_c_size(size, m)
            else:
                size = "(size_t)(%s) * sizeof(%s)" % (to_c_size(size, m), elem)
            pre.append("    if (_%s && !D3D9_IN_WINDOW(_%s, %s)) {" % (n, n, size))
            pre += unix_bail(it, m, n, 8)
            pre.append("    }")
            callargs.append("_%s" % n)
    return decls, pre, post, callargs


def emit_unix_c():
    o = [BANNER % "d3d9_unix.c -- one unix entry per D3D9 vtable slot"]
    o.append("""#include <string.h>

#include "d3d9shim_ops.h"
#include "d3d9_native_hooks.h"

/* The hand-written glue (d3d9_native_glue.cpp + d3d9_unix_glue.h) must
 * define, before this file is compiled:
 *
 *   NTSTATUS, STATUS_SUCCESS, STATUS_REVISION_MISMATCH, STATUS_NOT_SUPPORTED,
 *   STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED
 *   D3D9_HOST_PTR(u32)        -> void *, NULL-preserving; ios_wow_host_ptr()
 *   D3D9_GUEST_PTR32(void *)  -> ULONG;  ios_wow_guest_ptr32()
 *   D3D9_IN_WINDOW(p, bytes)  -> int; false for anything outside [B, B+4G)
 *   D3D9_DEREF32(p)           -> the ULONG at a validated guest address
 *   D3D9_SHARED_IN(slot, pool) / D3D9_SHARED_OUT(slot, h, pool)
 *   D3D9_NO_POOL, D3D9_LOG(msg)
 *   D3D9_ARENA_TAKE_STARVED()  -> non-zero if an app-visible allocation on
 *                                 THIS thread could not be served since the
 *                                 last call; reading it clears it.
 *
 * EVERY embedded pointer is converted before any dereference and NULL stays
 * NULL (7.4 rule 1); every converted pointer is range-checked before it is
 * handed to the frontend, so a bad guest pointer is D3DERR_INVALIDCALL and
 * not a host fault the application's SEH can never see (8.9-4). */

#include "d3d9_unix_glue.h"

/* Variable-length input scanners, named by the count expressions in
 * d3d9_api.py.  The glue implements them; each walks GUEST memory, so each
 * must window-check as it walks and return 0 for anything it cannot follow.
 * D3D9_IN_WINDOW(p, 0) still validates the base address, so a 0 from one of
 * these does not weaken the check that follows it. */
extern size_t d3d9_decl_element_count(const D3DVERTEXELEMENT9 *elements);
extern size_t d3d9_shader_token_count(const DWORD *byte_code);
extern size_t d3d9_up_vertex_bytes(D3DPRIMITIVETYPE type, UINT primitive_count,
                                   UINT stride);
extern size_t d3d9_up_index_bytes(D3DPRIMITIVETYPE type, UINT primitive_count,
                                  D3DFORMAT index_format);
""")
    # mirror conversions
    o.append("/* ---- mirror conversions "
             "-------------------------------------------- */\n")
    used_in, used_out = set(), set()
    for it, m in api.iter_methods():
        for a in m["args"]:
            target = LOCKED.get(a["tag"]) or arg_target(a)
            if target not in MIRROR_BY_NAME:
                continue
            if a["tag"] in ("in_struct", "inout_struct"):
                used_in.add(target)
            if a["tag"] in LOCKED or a["tag"] in ("out_struct", "inout_struct"):
                used_out.add(target)
    for s in api.MIRROR_STRUCTS:
        host, mirror = s["name"], "d3d9_%s32" % s["name"]
        assert host in used_out, host
        if host not in used_in:
            o.append("/* %s never crosses INWARD, so it has no "
                     "d3d9_mirror_in_%s(). */" % (host, host))
            o.append("")
        if host in used_in:
            o.append("static void d3d9_mirror_in_%s(%s *dst, const struct %s *src)"
                     % (host, host, mirror))
            o.append("{")
            o.append("    memset(dst, 0, sizeof(*dst));")
            done = set()
            for ctype, name, _o32, _o64, role in s["fields"]:
                if role == "scalar":
                    o.append("    dst->%s = src->%s;" % (name, name))
                elif role == "hwnd":
                    o.append("    dst->%s = (HWND)(ULONG_PTR)src->%s;"
                             % (name, name))
                elif role == "guest_ptr":
                    o.append("    dst->%s = D3D9_HOST_PTR(src->%s);"
                             % (name, name))
                elif role == "u64_lo":
                    base = name[:-3]
                    if base in done:
                        continue
                    done.add(base)
                    o.append("    dst->%s.LowPart = src->%s_lo;" % (base, base))
                    o.append("    dst->%s.HighPart = (LONG)src->%s_hi;"
                             % (base, base))
            o.append("}\n")
        o.append("static void d3d9_mirror_out_%s(struct %s *dst, const %s *src)"
                 % (host, mirror, host))
        o.append("{")
        done = set()
        for ctype, name, _o32, _o64, role in s["fields"]:
            if role == "scalar":
                o.append("    dst->%s = src->%s;" % (name, name))
            elif role == "hwnd":
                o.append("    dst->%s = (uint32_t)(ULONG_PTR)src->%s;"
                         % (name, name))
            elif role == "guest_ptr":
                o.append("    dst->%s = D3D9_GUEST_PTR32(src->%s);" % (name, name))
            elif role == "u64_lo":
                base = name[:-3]
                if base in done:
                    continue
                done.add(base)
                o.append("    dst->%s_lo = src->%s.LowPart;" % (base, base))
                o.append("    dst->%s_hi = (uint32_t)src->%s.HighPart;"
                         % (base, base))
        o.append("}\n")

    # init
    o.append("""/* ---- the init handshake ------------------------------------------------ */

NTSTATUS _d3d9_init(void *args)
{
    struct d3d9_init_params *_p = args;

    _p->native_hash = D3D9SHIM_API_HASH;
    if (_p->api_hash != D3D9SHIM_API_HASH || _p->api_version != D3D9SHIM_API_VERSION
        || _p->op_count != D3D9SHIM_OP_COUNT) {
        D3D9_LOG("d3d9: shim/native API description mismatch; refusing");
        _p->status = D3D9SHIM_INIT_HASH_MISMATCH;
        return STATUS_REVISION_MISMATCH;
    }
    /* This wire format cannot express a 64-bit pointer, so a 64-bit caller
     * has no correct reading of a parameter block.  Fail loudly rather than
     * zero-extend something (7.4 rule 4). */
    if (_p->ptr_size != 4) {
        D3D9_LOG("d3d9: the shim ABI is 32-bit only");
        _p->status = D3D9SHIM_INIT_BAD_PTR_SIZE;
        return STATUS_NOT_SUPPORTED;
    }
    if (!d3d9_native_init()) {
        _p->status = D3D9SHIM_INIT_NATIVE_FAILED;
        return STATUS_UNSUCCESSFUL;
    }
    _p->status = D3D9SHIM_INIT_OK;
    return STATUS_SUCCESS;
}

/* ---- one entry per slot ------------------------------------------------ */
""")

    for it, m in api.iter_methods():
        sym = api.symbol(it, m)
        block = api.block_struct(it, m)
        o.append("/* %s::%s -- slot %d, %s */"
                 % (it["iface"], m["name"], m["slot"], m["disp"]))
        if m["disp"] == "resolve":
            # A real entry, and the reason `resolve` exists as a disposition:
            # the shim answers this method from its identity cache, but a
            # child native handle is produced by NOTHING ELSE, so the one
            # crossing that fills the cache lands here.
            o.append("/* Answers the identity cache in the shim on a miss; "
                     "the handle it\n * writes into the block is what the "
                     "guest wrapper is built from. */")
        if m["disp"] == "local":
            o.append("NTSTATUS _d3d9_%s(void *args)" % sym)
            o.append("{")
            o.append("    /* answered in the shim (%s); reaching the unix side "
                     "means the\n     * two halves disagree about the "
                     "description. */" % m["local"])
            o.append("    (void)args;")
            o.append('    D3D9_LOG("d3d9: %s::%s crossed but is local");'
                     % (it["iface"], m["name"]))
            o.append("    return STATUS_NOT_IMPLEMENTED;")
            o.append("}")
            o.append("")
            continue

        decls, pre, post, callargs = unix_convert(it, m)
        o.append("static void d3d9_call_%s(struct %s *_p)" % (sym, block))
        o.append("{")
        for d in decls:
            o.append(d)
        if decls:
            o.append("")
        for p in pre:
            o.append(p)
        call = "d3d9_native_%s(%s);" % (sym, ", ".join(callargs))
        if m["ret"] == "void":
            o.append("    " + call)
        else:
            o.append("    _p->ret = d3d9_native_%s(%s);"
                     % (sym, ", ".join(callargs))
                     if m["ret"] != "HMONITOR" else
                     "    _p->ret = (uint64_t)(ULONG_PTR)d3d9_native_%s(%s);"
                     % (sym, ", ".join(callargs)))
        for p in post:
            o.append(p)
        o.append("}")
        o.append("")
        o.append("NTSTATUS _d3d9_%s(void *args)" % sym)
        o.append("{")
        if m["ret"] == "HRESULT":
            # An app-visible allocation that could not be served leaves a
            # per-thread mark.  If it also made THIS call fail, say so with
            # the distinguished status instead of an opaque E_OUTOFMEMORY:
            # the shim grows the arena and retries the same block once
            # (8.2(c)).  The mark is taken unconditionally so it cannot leak
            # into the next call, and acted on only on a failed HRESULT, so a
            # retry can never repeat work that succeeded.
            o.append("    struct d3d9_%s_params *_p = args;" % sym)
            o.append("    int _starved;")
            o.append("")
            o.append("    d3d9_call_%s(_p);" % sym)
            o.append("    _starved = D3D9_ARENA_TAKE_STARVED();")
            o.append("    if (_starved && FAILED((HRESULT)_p->ret))")
            o.append("        return (NTSTATUS)D3D9SHIM_STATUS_ARENA_EXHAUSTED;")
            o.append("    return STATUS_SUCCESS;")
        else:
            o.append("    d3d9_call_%s(args);" % sym)
            o.append("    return STATUS_SUCCESS;")
        o.append("}")
        o.append("")

    # ---- the transport slots --------------------------------------------
    o.append("""/* ---- the transport slots -----------------------------------------------
 * Not vtable methods, so nothing in the interface description produces them;
 * see TRANSPORT_SLOTS in d3d9_api.py.  They keep the numbers the hand-written
 * shim half already calls with, immediately after the generated range. */
""")
    for i, t in enumerate(api.TRANSPORT_SLOTS):
        o.append("/* %s -- slot %d, transport */" % (t["name"], TRANSPORT_BASE + i))
        o.append("static void d3d9_call_%s(struct %s *_p)" % (t["name"], t["block"]))
        o.append("{")
        decls, pre, callargs = [], [], []
        for ctype, fname, role in t["fields"]:
            base = role.split(":", 1)[0]
            if base == "scalar":
                callargs.append("(%s)_p->%s" % (role.split(":", 1)[1], fname))
            elif base == "hwnd32":
                callargs.append("(HWND)(ULONG_PTR)_p->%s" % fname)
            elif base == "guest_ptr":
                size = role.split(":", 1)[1]
                size = size if size.isdigit() else "_p->" + size
                decls.append("    void *_%s = D3D9_HOST_PTR(_p->%s);" % (fname, fname))
                pre.append("    if (!_%s || !D3D9_IN_WINDOW(_%s, %s)) {"
                           % (fname, fname, size))
                pre.append('        D3D9_LOG("d3d9: %s: %s is not a usable '
                           'guest pointer");' % (t["name"], fname))
                pre.append("        _p->ret = D3DERR_INVALIDCALL;")
                pre.append("        return;")
                pre.append("    }")
                callargs.append("_%s" % fname)
            elif base == "handle_out":
                decls.append("    d3d9_native_handle _%s = 0;" % fname)
                callargs.append("&_%s" % fname)
            del ctype
        for d in decls:
            o.append(d)
        if decls:
            o.append("")
        o += pre
        if t["ret_zero_ok"]:
            o.append("    _p->ret = %s(%s) ? E_FAIL : D3D_OK;"
                     % (t["hook"], ", ".join(callargs)))
        else:
            o.append("    _p->ret = %s(%s);" % (t["hook"], ", ".join(callargs)))
        for _ctype, fname, role in t["fields"]:
            if role.split(":", 1)[0] == "handle_out":
                o.append("    _p->%s = _%s;" % (fname, fname))
        o.append("}")
        o.append("")
        o.append("NTSTATUS _d3d9_%s(void *args)" % t["name"])
        o.append("{")
        o.append("    d3d9_call_%s(args);" % t["name"])
        o.append("    return STATUS_SUCCESS;")
        o.append("}")
        o.append("")

    # ---- ring replay ----------------------------------------------------
    o.append("""/* ---- ring replay -------------------------------------------------------
 * The ring is a TRANSPORT, not a re-implementation: replay calls exactly the
 * same d3d9_call_* the synchronous entry does (8.6).  `seq` is monotonic and
 * asserted here, which is what turns a ring bug into a refused batch rather
 * than a wrong frame. */

NTSTATUS d3d9_ring_replay(void *base, uint32_t bytes, uint32_t *seq_io)
{
    unsigned char *_p = base, *_end = _p + bytes;

    if (((uintptr_t)base & 7u) || (bytes & 7u))
        return STATUS_INVALID_PARAMETER;
    while (_p + sizeof(struct d3d9_ring_record) <= _end) {
        struct d3d9_ring_record *_r = (struct d3d9_ring_record *)_p;
        void *_blk = _r + 1;

        if (_r->len < sizeof(struct d3d9_ring_record) || (_r->len & 7u)
            || _p + _r->len > _end)
            return STATUS_INVALID_PARAMETER;
        if (_r->seq != *seq_io)
            return STATUS_INVALID_PARAMETER;
        ++*seq_io;
        switch (_r->op) {""")
    for it, m in api.iter_methods():
        if m["disp"] != "defer":
            continue
        sym = api.symbol(it, m)
        block = api.block_struct(it, m)
        o.append("        case %s:" % api.opcode_name(it, m))
        o.append("            if (_r->len != sizeof(struct d3d9_ring_record)"
                 " + sizeof(struct %s))" % block)
        o.append("                return STATUS_INVALID_PARAMETER;")
        o.append("            d3d9_call_%s(_blk);" % sym)
        o.append("            break;")
    o.append("""        default:
            D3D9_LOG("d3d9: ring record with a non-deferrable opcode");
            return STATUS_INVALID_PARAMETER;
        }
        _p += _r->len;
    }
    return _p == _end ? STATUS_SUCCESS : STATUS_INVALID_PARAMETER;
}
""")

    o.append("/* The two dispatch tables are in d3d9_unix_table.c, which "
             "declares every\n * _d3d9_* above itself -- also generated, so "
             "the two cannot drift. */")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------
# d3d9_unix_table.c
# --------------------------------------------------------------------------

def emit_unix_table_c():
    o = [BANNER % "d3d9_unix_table.c -- the two dispatch tables"]
    o.append("""#include "d3d9shim_ops.h"
#include "d3d9_unix_glue.h"

/* WOW64_DESIGN.md 7.4 rule 3: both tables the same length, the 32-bit
 * variant at the SAME index as its 64-bit twin.  Here they are the same
 * FUNCTIONS as well, and that is a property of the wire format rather than
 * a shortcut: a parameter block's pointer fields are uint32_t, so a block
 * can only have been written by a 32-bit caller and there is exactly one
 * correct way to read one.  A _32 variant would have nothing to do
 * differently.  The 64-bit table is present because load_builtin_unixlib
 * binds a PAIR; _d3d9_init refuses any caller whose pointer width is not 4,
 * so the 64-bit table can be entered but never lies about the result. */

/* Defined in d3d9_unix.c, one per slot. */""")
    for i, (opname, it, m) in enumerate(OPS):
        o.append("extern NTSTATUS _d3d9_%s(void *args);" % op_symbol(it, m))
        del opname, i
    o.append("")
    for table in ("dxmt_d3d9_unix_call_funcs", "dxmt_d3d9_unix_call_wow64_funcs"):
        o.append("const void *const %s[D3D9SHIM_OP_COUNT] = {" % table)
        for i, (opname, it, m) in enumerate(OPS):
            o.append("    /* %3d */ (const void *)_d3d9_%s,"
                     % (i, op_symbol(it, m)))
            del opname
        o.append("};")
        o.append("")
    o.append("""_Static_assert(sizeof(dxmt_d3d9_unix_call_funcs)
               == sizeof(dxmt_d3d9_unix_call_wow64_funcs),
               "the two d3d9 unix tables must be the same length");
_Static_assert(sizeof(dxmt_d3d9_unix_call_funcs) / sizeof(const void *)
               == D3D9SHIM_OP_COUNT,
               "d3d9 unix table length must equal the opcode count");""")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------
# d3d9_native_gen.inc -- the mechanical native bodies (WOW64_DESIGN.md 8.5)
#
# 8.5 asks for one d3d9_native_<Iface>_<Method> per slot, implemented against
# the MTLD3D9* classes.  All but five of them are the same three lines -- look
# the receiver up in the handle table, look every interface argument up,
# forward, intern whatever came back -- because d3d9_unix.c has already
# converted, validated and (where a mirror needs it) expanded everything else.
# Writing 315 of those by hand is exactly the drift this generator exists to
# prevent, so they are emitted from the same description the entries come
# from and d3d9_native_glue.cpp hand-writes only what is not mechanical.
# --------------------------------------------------------------------------

KIND_IFACE = {it["kind"]: it["iface"] for it in api.INTERFACES}

# `any`-kind interface arguments (IDirect3DBaseTexture9 / IDirect3DResource9 /
# IUnknown): the handle does not say which concrete class it is, so the glue
# resolves those through a kind switch.
ANY_IN_HELPER = {
    "IDirect3DBaseTexture9": "d3d9_native_as_base_texture",
    "IDirect3DResource9": "d3d9_native_as_resource",
    "IUnknown": "d3d9_native_as_unknown",
}

# Slots whose native body is HAND-WRITTEN in d3d9_native_glue.cpp, and why.
NATIVE_HANDWRITTEN = {
    ("D3D9Ex", "CreateDevice"):
        "the shim owns D3DCREATE_MULTITHREADED (is_protected=false) and the "
        "window-size cache is seeded before the swapchain is built",
    ("D3D9Ex", "CreateDeviceEx"):
        "same as CreateDevice",
    ("Device9Ex", "GetCreationParameters"):
        "CreateDevice strips D3DCREATE_MULTITHREADED before the native "
        "device sees it, so the flag has to be put back here",
    ("Device9Ex", "CheckResourceResidency"):
        "its array holds GUEST interface pointers, which have no native "
        "meaning; only the NULL-with-a-count rule is answerable here",
    ("Surface9", "GetDC"):
        "shim-local: D3DKMTCreateDCFromMemory runs on the guest thread",
    ("Surface9", "ReleaseDC"):
        "shim-local, like GetDC",
}

# What a hook returns when its receiver or one of its arguments does not
# resolve (a validated failure, never a host fault -- 8.9-4), and what it
# returns when a C++ exception would otherwise escape into 32-bit code.
NATIVE_FAIL = {
    "HRESULT": "D3DERR_INVALIDCALL",
    "ULONG": "0",
    "UINT": "0",
    "DWORD": "0",
    "WINBOOL": "FALSE",
    "float": "0.0f",
    "HMONITOR": "NULL",
    "D3DRESOURCETYPE": "(D3DRESOURCETYPE)0",
    "D3DTEXTUREFILTERTYPE": "(D3DTEXTUREFILTERTYPE)0",
    "D3DQUERYTYPE": "(D3DQUERYTYPE)0",
    "int": "0",
}
NATIVE_CATCH = dict(NATIVE_FAIL, HRESULT="E_FAIL")


def native_handwritten(it, m):
    return (it["short"], m["name"]) in NATIVE_HANDWRITTEN


def any_iface_out(m):
    """True when a slot hands out an interface whose concrete kind the handle
    table cannot know (QueryInterface, GetContainer, GetTexture).  Every one
    of them is `local` -- answered in the shim, never crossing -- which
    generator_self_check() enforces."""
    for a in m["args"]:
        if a["tag"] == "iface_out" and KINDS[a["shape"].split(":", 1)[1]] == "ANY":
            return True
    return False


def has_iface_array(m):
    return any(is_iface_array(a) for a in m["args"])


def not_mechanical(m):
    """A shape no forwarding body can carry.  Always `local` or hand-written."""
    return m["name"] == "QueryInterface" or any_iface_out(m) or has_iface_array(m)


def deref_type(ctype, stars):
    t = ctype.strip()
    assert t.endswith(stars), (ctype, stars)
    return t[: -len(stars)].strip()


# REFIID / REFGUID are `const GUID &` behind a typedef.  The wire shape is a
# pointer (it has to be: the block carries a guest address), and the hook takes
# one, so the forwarding body dereferences -- after checking, because the unix
# entry lets a NULL in_struct through as the NULL the application passed.
REFERENCE_CTYPES = ("REFIID", "REFGUID", "REFCLSID")


def is_reference_arg(a):
    return a["ctype"].strip() in REFERENCE_CTYPES or a["ctype"].strip().endswith("&")


def pass_expr(a):
    """How one already-converted argument is handed to the native method.

    The SDK is not consistent about const on INPUT parameters -- ResetEx takes
    a `D3DDISPLAYMODEEX *` it only reads, SetConvolutionMonoKernel a
    `float *` -- while the description (correctly) calls them inputs, so the
    hook's parameter is const.  Casting the const away at the call is the only
    thing that can bridge that, and it is safe in the direction that matters:
    where the SDK does say const, the cast is a no-op the conversion undoes.
    """
    t, n = a["tag"], a["name"]
    if t in ("in_struct", "in_array"):
        if is_reference_arg(a):
            return "*" + n
        return "const_cast<%s *>(%s)" % (arg_target(a), n)
    if t == "user_mem_in":
        return "const_cast<void *>(%s)" % n
    return n


def emit_native_body(it, m):
    sym = api.symbol(it, m)
    ret = native_ret(m)
    void = ret == "void"
    fail = "" if void else " " + NATIVE_FAIL[m["ret"]]
    caught = "" if void else " " + NATIVE_CATCH[m["ret"]]
    kind = "D3D9_NATIVE_KIND_" + it["kind"]

    o = ["/* %s::%s -- slot %d, %s */"
         % (it["iface"], m["name"], m["slot"], m["disp"])]
    o.append(ret)
    o.append("d3d9_native_%s(%s)" % (sym, native_params(it, m)))
    o.append("{")
    o.append("  D3D9_NATIVE_ENTER(%s);" % api.opcode_name(it, m))

    if not_mechanical(m):
        for a in m["args"]:
            o.append("  (void)%s;" % a["name"])
        o.append("  (void)self;")
        o.append('  D3D9_NATIVE_LOCAL("%s::%s");' % (it["iface"], m["name"]))
        o.append("  return%s;" % (" E_NOTIMPL" if m["ret"] == "HRESULT" else fail))
        o.append("}")
        return o

    if m["name"] == "Release":
        # Retiring the handle is what drops the native reference; the guest
        # refcount is the shim's business and only the LAST release crosses.
        o.append("  return d3d9_native_retire(self, %s);" % kind)
        o.append("}")
        return o

    o.append("  try {")
    o.append("    %s *_self = d3d9_native_lookup<%s>(self, %s);"
             % (it["iface"], it["iface"], kind))
    o.append("    if (!_self)")
    o.append("      return%s;" % fail)

    call = []
    adopt = []
    for a in m["args"]:
        t, n = a["tag"], a["name"]
        if t == "iface_in":
            iface = a["shape"].split(":", 1)[1]
            k = KINDS[iface]
            ctype = a["ctype"].rstrip("* ") + " *"
            if k == "ANY":
                o.append("    %s _a_%s = %s(%s);"
                         % (ctype, n, ANY_IN_HELPER[iface], n))
            else:
                o.append("    %s _a_%s = d3d9_native_lookup<%s>(%s, "
                         "D3D9_NATIVE_KIND_%s);"
                         % (ctype, n, KIND_IFACE[k], n, k))
            # A NULL handle is a legal argument (SetTexture(stage, NULL));
            # a non-NULL one that does not resolve is not.
            o.append("    if (%s && !_a_%s)" % (n, n))
            o.append("      return%s;" % fail)
            call.append("_a_" + n)
        elif t == "iface_out":
            inner = deref_type(a["ctype"], "**")
            k = KINDS[a["shape"].split(":", 1)[1]]
            o.append("    %s *_o_%s = nullptr;" % (inner, n))
            o.append("    if (%s)" % n)
            o.append("      *%s = 0;" % n)
            call.append("&_o_" + n)
            adopt.append((n, KIND_IFACE[k], "D3D9_NATIVE_KIND_" + k))
        else:
            if is_reference_arg(a):
                o.append("    if (!%s)" % n)
                o.append("      return%s;" % fail)
            call.append(pass_expr(a))

    invoke = "_self->%s(%s)" % (m["name"], ", ".join(call))
    if void:
        o.append("    %s;" % invoke)
        o.append("    return;")
    elif adopt:
        o.append("    HRESULT _hr = %s;" % invoke)
        for n, canon, k in adopt:
            o.append("    d3d9_native_adopt<%s>(_o_%s, %s, %s, SUCCEEDED(_hr));"
                     % (canon, n, k, n))
        o.append("    return _hr;")
    else:
        o.append("    return %s;" % invoke)

    o.append("  } catch (...) {")
    o.append('    D3D9_NATIVE_CAUGHT("%s::%s");' % (it["iface"], m["name"]))
    o.append("    return%s;" % caught)
    o.append("  }")
    o.append("}")
    return o


def emit_native_gen_inc():
    o = [BANNER % "d3d9_native_gen.inc -- the mechanical native bodies"]
    o.append("""/* Included ONCE, from research/dxmt/src/d3d9/unix/d3d9_native_glue.cpp,
 * inside its extern "C" block and after the helpers every body below calls.
 * Not a header: no include guard, and nothing else may include it.
 *
 * One body per vtable slot whose shape is mechanical -- look the receiver up
 * in the handle table, look every interface argument up, forward to the
 * MTLD3D9* object, intern whatever came back.  d3d9_unix.c has already
 * converted, validated and expanded everything else, so there is nothing
 * left for these to decide.  Every one wraps the call in try/catch, because
 * no C++ exception may escape into 32-bit code (8.9-4).
 *
 * HAND-WRITTEN in d3d9_native_glue.cpp instead:""")
    for (short, name), why in sorted(NATIVE_HANDWRITTEN.items()):
        o.append(" *   %s::%s -- %s" % (short, name, why))
    o.append(" */\n")

    o.append("/* Opcode names, for the [d3d9-native-census] summary: emitted "
             "here so a\n * counter cannot name a slot other than the one it "
             "counted. */")
    o.append("static const char *const d3d9_native_op_names[D3D9SHIM_OP_COUNT] = {")
    for i, (name, it, m) in enumerate(OPS):
        if m is None:
            label = "init"
        elif it is None:
            label = m["name"]
        else:
            label = "%s::%s" % (it["iface"], m["name"])
        o.append('    /* %3d */ "%s",' % (i, label))
    o.append("};")
    o.append("")

    for it, m in api.iter_methods():
        if native_handwritten(it, m):
            o.append("/* %s::%s -- slot %d, %s: HAND-WRITTEN in "
                     "d3d9_native_glue.cpp. */"
                     % (it["iface"], m["name"], m["slot"], m["disp"]))
            o.append("")
            continue
        o += emit_native_body(it, m)
        o.append("")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def generator_self_check():
    """Re-check, on the data about to be emitted, what 8.7 requires."""
    bad = []
    seen = {}
    for i, (name, it, m) in enumerate(OPS):
        if name in seen:
            bad.append("duplicate opcode name %s (slots %d and %d)"
                       % (name, seen[name], i))
        seen[name] = i
    if OPS[0][0] != "D3D9OP_init":
        bad.append("slot 0 must be the init handshake")
    if len(OPS) != 1 + api.EXPECTED_TOTAL_SLOTS + len(api.TRANSPORT_SLOTS):
        bad.append("opcode count %d, expected %d"
                   % (len(OPS),
                      1 + api.EXPECTED_TOTAL_SLOTS + len(api.TRANSPORT_SLOTS)))
    # The transport slots are an ABI the hand-written half already calls
    # with: they must come AFTER the whole generated range and in order, so
    # arena_register stays 321, window_state 322, create_interface 323.
    for t in api.TRANSPORT_SLOTS:
        want = t["slot"]
        if want >= len(OPS) or OPS[want][0] != t["op"]:
            bad.append("transport slot %s is not at index %d" % (t["op"], want))
        if OPS[want][1] is not None or not is_transport(*OPS[want][1:]):
            bad.append("transport slot %s is not marked as one" % t["op"])
    for i, (name, it, m) in enumerate(OPS):
        if is_transport(it, m) and i < TRANSPORT_BASE:
            bad.append("transport slot %s inside the generated range" % name)
    for it, m in api.iter_methods():
        for a in m["args"]:
            if a["tag"] in ("iface_in", "iface_out"):
                iface = a["shape"].split(":", 1)[1]
                if iface not in KINDS:
                    bad.append("%s::%s: %s names an interface with no kind"
                               % (it["iface"], m["name"], a["shape"]))
            # Every struct the native side WRITES into must be one the
            # boundary knows the i386 size of, and the entry must write that
            # many bytes and no more.  Three legal shapes:
            #   mirror       -> d3d9_mirror_out_<T>, field by field
            #   padding-only -> D3D9_COPY32_OUT, exactly D3D9SHIM_SIZE32_<T>
            #   identical    -> in place, one size on both ABIs
            # Anything else is a host-sized write into a guest buffer, which
            # is the 0xC0000409 class of bug.
            if a["tag"] in ("out_struct", "inout_struct"):
                target = arg_target(a)
                if target in MIRROR_BY_NAME or target in PADDING_ONLY:
                    continue
                if target in IDENTICAL_BY_NAME:
                    continue
                bad.append("%s::%s: %s is written back in place but its i386 "
                           "size is not declared in d3d9_api.py -- add it to "
                           "IDENTICAL_STRUCTS, MIRROR_STRUCTS or "
                           "PADDING_ONLY_STRUCTS"
                           % (it["iface"], m["name"], target))
        if m["disp"] in ("local", "resolve") and (m["local"] or "").startswith("identity"):
            if not any(a["tag"] == "iface_out" for a in m["args"]):
                bad.append("%s::%s: identity local with no iface_out argument"
                           % (it["iface"], m["name"]))
        if m["disp"] == "resolve":
            # The shim resolve reads the child handle as the block SECOND
            # 64-bit word -- it has one generic reader, not one per slot -- so
            # the iface_out must be the first field after `self`.  The layout
            # rule (64-bit fields first) gives that for free today; this is
            # what catches the day a second u64 argument quietly takes the
            # place.
            fields = api.block_fields(m)
            outs = [a["name"] for a in m["args"] if a["tag"] == "iface_out"]
            if len(outs) != 1:
                bad.append("%s::%s: a resolve needs exactly one iface_out"
                           % (it["iface"], m["name"]))
            elif len(fields) < 2 or fields[1][1] != outs[0] \
                    or fields[1][0] != "uint64_t":
                bad.append("%s::%s: the resolved handle must be the block "
                           "second 64-bit word, found %r"
                           % (it["iface"], m["name"],
                              fields[1][1] if len(fields) > 1 else None))
        # The native side of step 4: a shape no forwarding body can carry has
        # to be answered in the shim (`local`) or named in NATIVE_HANDWRITTEN.
        # Reclassifying one of them to `sync` without doing either would emit
        # an E_NOTIMPL that silently crossed, which is the one failure mode
        # 8.5's "unimplemented = never a hole" rule exists to prevent.
        if not_mechanical(m) and m["disp"] != "local" \
                and not native_handwritten(it, m):
            bad.append("%s::%s: %s but its shape (an any-kind iface_out or an "
                       "interface array) cannot be forwarded mechanically -- "
                       "keep it local or add it to NATIVE_HANDWRITTEN"
                       % (it["iface"], m["name"], m["disp"]))
        for a in m["args"]:
            if a["tag"] == "iface_in" \
                    and KINDS[a["shape"].split(":", 1)[1]] == "ANY" \
                    and a["shape"].split(":", 1)[1] not in ANY_IN_HELPER:
                bad.append("%s::%s: %s has no entry in ANY_IN_HELPER"
                           % (it["iface"], m["name"], a["shape"]))
            if a["tag"] == "guest_ptr_out" and not a["ctype"].count("*") == 2:
                bad.append("%s::%s: %s is a guest_ptr_out but its C type %r is "
                           "not a pointer to a pointer"
                           % (it["iface"], m["name"], a["name"], a["ctype"]))
    for s in api.MIRROR_STRUCTS:
        off = 0
        for _ctype, _n, off32, _off64, _role in s["fields"]:
            if off32 != off:
                bad.append("%s: mirror is not 4-byte packed" % s["name"])
            off += 4
    return bad


OUTPUTS = [
    ("research/dxmt/src/d3d9shim/d3d9shim_ops.h", emit_ops_h),
    ("research/dxmt/src/d3d9shim/d3d9shim_objects_gen.h", emit_objects_h),
    ("research/dxmt/src/d3d9shim/d3d9shim_thunks.c", emit_thunks_c),
    ("research/dxmt/src/d3d9/unix/d3d9_native_hooks.h", emit_native_hooks_h),
    ("research/dxmt/src/d3d9/unix/d3d9_unix.c", emit_unix_c),
    ("research/dxmt/src/d3d9/unix/d3d9_unix_table.c", emit_unix_table_c),
    ("research/dxmt/src/d3d9/unix/d3d9_native_gen.inc", emit_native_gen_inc),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="diff against what is on disk; exit 1 if it differs")
    ap.add_argument("-o", "--root", default=None,
                    help="repository root (default: inferred from this file)")
    args = ap.parse_args()

    root = args.root or os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "..", "..", "..", ".."))

    problems = api.validate() + generator_self_check()
    if problems:
        sys.stderr.write("gen_d3d9_thunks.py: REFUSING to emit, %d problem(s):\n"
                         % len(problems))
        for p in problems:
            sys.stderr.write("  " + p + "\n")
        return 1

    rendered = [(rel, fn()) for rel, fn in OUTPUTS]

    if args.check:
        differs = 0
        for rel, text in rendered:
            path = os.path.join(root, rel)
            try:
                on_disk = open(path, encoding="utf-8", newline="").read()
            except OSError:
                on_disk = None
            if on_disk != text:
                sys.stderr.write("STALE: %s\n" % rel)
                differs += 1
        if differs:
            sys.stderr.write("run gen_d3d9_thunks.py to regenerate\n")
            return 1
        print("up to date (%d files), D3D9SHIM_API_HASH = 0x%016x"
              % (len(rendered), api.api_hash()))
        return 0

    for rel, text in rendered:
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("%-52s %7d bytes  %5d lines"
              % (rel, len(text), text.count("\n")))
    print("D3D9SHIM_API_HASH = 0x%016x" % api.api_hash())
    return 0


if __name__ == "__main__":
    sys.exit(main())
