/* GENERATED by gen_remote_guard.py from the unix dispatch table.
 * Regenerate whenever __wine_unix_call_funcs[] or the routed set changes.
 * Do not hand-edit. */

static NTSTATUS _rmg_NSObject_description(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_obj_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("NSObject_description");
  }
  return _NSObject_description(obj);
}
static NTSTATUS _rmg_MTLTexture_pixelFormat(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLTexture_pixelFormat");
  }
  return _MTLTexture_pixelFormat(obj);
}
static NTSTATUS _rmg_MTLTexture_depth(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLTexture_depth");
  }
  return _MTLTexture_depth(obj);
}
static NTSTATUS _rmg_MTLTexture_arrayLength(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLTexture_arrayLength");
  }
  return _MTLTexture_arrayLength(obj);
}
static NTSTATUS _rmg_MTLBuffer_didModifyRange(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLBuffer_didModifyRange");
  }
  return _MTLBuffer_didModifyRange(obj);
}
static NTSTATUS _rmg_MTLCommandBuffer_presentDrawableAfterMinimumDuration(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLCommandBuffer_presentDrawableAfterMinimumDuration");
  }
  return _MTLCommandBuffer_presentDrawableAfterMinimumDuration(obj);
}
static NTSTATUS _rmg_MTLCaptureManager_sharedCaptureManager(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLCaptureManager_sharedCaptureManager");
  }
  return _MTLCaptureManager_sharedCaptureManager(obj);
}
static NTSTATUS _rmg_MTLCaptureManager_startCapture(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtlcapturemanager_startcapture *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLCaptureManager_startCapture");
  }
  return _MTLCaptureManager_startCapture(obj);
}
static NTSTATUS _rmg_MTLCaptureManager_stopCapture(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLCaptureManager_stopCapture");
  }
  return _MTLCaptureManager_stopCapture(obj);
}
static NTSTATUS _rmg_MTLDevice_newTemporalScaler(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_newfxtemporalscaler *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newTemporalScaler");
  }
  return _MTLDevice_newTemporalScaler(obj);
}
static NTSTATUS _rmg_MTLDevice_newSpatialScaler(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_newfxspatialscaler *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newSpatialScaler");
  }
  return _MTLDevice_newSpatialScaler(obj);
}
static NTSTATUS _rmg_MTLCommandBuffer_encodeTemporalScale(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLCommandBuffer_encodeTemporalScale");
  }
  return _MTLCommandBuffer_encodeTemporalScale(obj);
}
static NTSTATUS _rmg_MTLCommandBuffer_encodeSpatialScale(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLCommandBuffer_encodeSpatialScale");
  }
  return _MTLCommandBuffer_encodeSpatialScale(obj);
}
static NTSTATUS _rmg_MTLDevice_supportsFXSpatialScaler(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_supportsFXSpatialScaler");
  }
  return _MTLDevice_supportsFXSpatialScaler(obj);
}
static NTSTATUS _rmg_MTLDevice_supportsFXTemporalScaler(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_supportsFXTemporalScaler");
  }
  return _MTLDevice_supportsFXTemporalScaler(obj);
}
static NTSTATUS _rmg_MTLCommandBuffer_error(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_obj_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLCommandBuffer_error");
  }
  return _MTLCommandBuffer_error(obj);
}
static NTSTATUS _rmg_MTLCommandBuffer_logs(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_obj_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLCommandBuffer_logs");
  }
  return _MTLCommandBuffer_logs(obj);
}
static NTSTATUS _rmg_MTLLogContainer_enumerate(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_enumerate *p = obj;
    p->ret_read = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLLogContainer_enumerate");
  }
  return _MTLLogContainer_enumerate(obj);
}
static NTSTATUS _rmg_CGColorSpace_checkColorSpaceSupported(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("CGColorSpace_checkColorSpaceSupported");
  }
  return _CGColorSpace_checkColorSpaceSupported(obj);
}
static NTSTATUS _rmg_MetalLayer_setColorSpace(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_uint64_uint64_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MetalLayer_setColorSpace");
  }
  return _MetalLayer_setColorSpace(obj);
}
static NTSTATUS _rmg_WMTGetSecondaryDisplayId(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("WMTGetSecondaryDisplayId");
  }
  return _WMTGetSecondaryDisplayId(obj);
}
static NTSTATUS _rmg_WMTQueryDisplaySetting(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_query_display_setting *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("WMTQueryDisplaySetting");
  }
  return _WMTQueryDisplaySetting(obj);
}
static NTSTATUS _rmg_WMTUpdateDisplaySetting(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("WMTUpdateDisplaySetting");
  }
  return _WMTUpdateDisplaySetting(obj);
}
static NTSTATUS _rmg_MTLSharedEvent_signalValue(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLSharedEvent_signalValue");
  }
  return _MTLSharedEvent_signalValue(obj);
}
static NTSTATUS _rmg_MTLSharedEvent_setWin32EventAtValue(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLSharedEvent_setWin32EventAtValue");
  }
  return _MTLSharedEvent_setWin32EventAtValue(obj);
}
static NTSTATUS _rmg_MTLDevice_newFence(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_obj_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newFence");
  }
  return _MTLDevice_newFence(obj);
}
static NTSTATUS _rmg_MTLDevice_newEvent(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_generic_obj_obj_ret *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newEvent");
  }
  return _MTLDevice_newEvent(obj);
}
static NTSTATUS _rmg_MTLDevice_newBinaryArchive(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_newbinaryarchive *p = obj;
    p->ret_archive = 0;   /* never hand back uninitialised stack */
    p->ret_error = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newBinaryArchive");
  }
  return _MTLDevice_newBinaryArchive(obj);
}
static NTSTATUS _rmg_MTLBinaryArchive_serialize(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtlbinaryarchive_serialize *p = obj;
    p->ret_error = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLBinaryArchive_serialize");
  }
  return _MTLBinaryArchive_serialize(obj);
}
static NTSTATUS _rmg_WMTBootstrapRegister(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("WMTBootstrapRegister");
  }
  return _WMTBootstrapRegister(obj);
}
static NTSTATUS _rmg_WMTBootstrapLookUp(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("WMTBootstrapLookUp");
  }
  return _WMTBootstrapLookUp(obj);
}
static NTSTATUS _rmg_MTLSharedEvent_createMachPort(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtlsharedevent_createmachport *p = obj;
    p->ret_mach_port = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLSharedEvent_createMachPort");
  }
  return _MTLSharedEvent_createMachPort(obj);
}
static NTSTATUS _rmg_MTLDevice_newSharedEventWithMachPort(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_newsharedeventwithmachport *p = obj;
    p->ret_event = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newSharedEventWithMachPort");
  }
  return _MTLDevice_newSharedEventWithMachPort(obj);
}
static NTSTATUS _rmg_MTLSharedEvent_waitUntilSignaledValue(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtlsharedevent_waituntilsignaledvalue *p = obj;
    p->ret_timeout = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLSharedEvent_waitUntilSignaledValue");
  }
  return _MTLSharedEvent_waitUntilSignaledValue(obj);
}
static NTSTATUS _rmg_MTLResidencySet_removeAllocation(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLResidencySet_removeAllocation");
  }
  return _MTLResidencySet_removeAllocation(obj);
}
static NTSTATUS _rmg_MTLDevice_heapTextureSizeAndAlign(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_heaptexturesizealign *p = obj;
    p->ret_size = 0;   /* never hand back uninitialised stack */
    p->ret_align = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_heapTextureSizeAndAlign");
  }
  return _MTLDevice_heapTextureSizeAndAlign(obj);
}
static NTSTATUS _rmg_MTLDevice_newPlacementHeap(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_newplacementheap *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newPlacementHeap");
  }
  return _MTLDevice_newPlacementHeap(obj);
}
static NTSTATUS _rmg_MTLHeap_newTextureAtOffset(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtlheap_newtextureatoffset *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLHeap_newTextureAtOffset");
  }
  return _MTLHeap_newTextureAtOffset(obj);
}
static NTSTATUS _rmg_madeira_ctl(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("madeira_ctl");
  }
  return _madeira_ctl(obj);
}
static NTSTATUS _rmg_MTLDevice_heapBufferSizeAndAlign(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_heapbuffersizealign *p = obj;
    p->ret_size = 0;   /* never hand back uninitialised stack */
    p->ret_align = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_heapBufferSizeAndAlign");
  }
  return _MTLDevice_heapBufferSizeAndAlign(obj);
}
static NTSTATUS _rmg_MTLHeap_newBufferAtOffset(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtlheap_newbufferatoffset *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLHeap_newBufferAtOffset");
  }
  return _MTLHeap_newBufferAtOffset(obj);
}
#ifndef DXMT_NATIVE
static NTSTATUS _rmg_MTLCaptureManager_startCapture32(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtlcapturemanager_startcapture *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLCaptureManager_startCapture32");
  }
  return _MTLCaptureManager_startCapture32(obj);
}
static NTSTATUS _rmg_MTLDevice_newTemporalScaler32(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_newfxtemporalscaler *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newTemporalScaler32");
  }
  return _MTLDevice_newTemporalScaler32(obj);
}
static NTSTATUS _rmg_MTLDevice_newSpatialScaler32(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_mtldevice_newfxspatialscaler *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLDevice_newSpatialScaler32");
  }
  return _MTLDevice_newSpatialScaler32(obj);
}
static NTSTATUS _rmg_MTLCommandBuffer_encodeTemporalScale32(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("MTLCommandBuffer_encodeTemporalScale32");
  }
  return _MTLCommandBuffer_encodeTemporalScale32(obj);
}
static NTSTATUS _rmg_MTLLogContainer_enumerate32(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_enumerate *p = obj;
    p->ret_read = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("MTLLogContainer_enumerate32");
  }
  return _MTLLogContainer_enumerate32(obj);
}
static NTSTATUS _rmg_WMTQueryDisplaySetting32(void *obj) {
  if (wmtr_enabled()) {
    struct unixcall_query_display_setting *p = obj;
    p->ret = 0;   /* never hand back uninitialised stack */
    return wmtr_unimplemented("WMTQueryDisplaySetting32");
  }
  return _WMTQueryDisplaySetting32(obj);
}
static NTSTATUS _rmg_WMTUpdateDisplaySetting32(void *obj) {
  if (wmtr_enabled()) {
    return wmtr_unimplemented("WMTUpdateDisplaySetting32");
  }
  return _WMTUpdateDisplaySetting32(obj);
}
#endif /* DXMT_NATIVE */
